ceramicnetwork/js-ceramic

.circleci/config.yml, lerna.json, package.json, packages/3id-did-resolver/CHANGELOG.md, packages/3id-did-resolver/package-lock.json, packages/3id-did-resolver/package.json, packages/ceramic-cli/CHANGELOG.md, packages/ceramic-cli/package-lock.json, packages/ceramic-cli/package.json, packages/ceramic-core/CHANGELOG.md, packages/ceramic-core/package.json, packages/ceramic-http-client/CHANGELOG.md, packages/ceramic-http-client/package-lock.json, packages/ceramic-http-client/package.json
Ok, this has been a bit of a pain to set up and I'm not totally happy yet. 
Main problem is if we create the release on a release branch as we have been practicing before with 3box repos it will tag the release in the current branch. When the branch is then merged to master this will cause an issue in most cases since the tags will remain on this branch if the commit hashes changes. 
It seems like the proper way to do releases in lerna is to actually just do the release directly on the master branch. 
Would love some thought @msterle @zachferland @simonovic86 
Btw, @msterle I created a prerelease that you can use 👍 (0.1.0-alpha.0), 0.1.0 has not been released yet.
Also note that we can generate automatic release notes and github releases using lerna.
I believe this should now be set up …
=> Release/all 0.1.0

package-lock.json, packages/ceramic-cli/package-lock.json, packages/ceramic-core/package-lock.json, packages/ceramic-core/package.json
This was missing, but error obscured when packages are hoisted
=> fix: add node-fetch types to ceramic core

packages/ceramic-core/package-lock.json, packages/ceramic-core/package.json, packages/ceramic-core/src/anchor/ethereum/ethereum-anchor-service.ts
so we can call the anchoring service from a browser
executed the tests & ran the cli / daemon + an anchoring node. Seems to work like that ;) node-fetch unfortunately doesn't support isomorphic browser & node fetching, cross-fetch falls back to a whatwg brower fetch when it detects a windows object (think it's also officially used by js-ipfs)
=> node-fetch -> cross-fetch

packages/ceramic-core/src/ceramic.ts
There is a typo that prevents Ceramic CLI to use correct pinning configuration.
=> Pinning, not pinnings

packages/3id-did-resolver/package-lock.json, packages/3id-did-resolver/package.json, packages/3id-did-resolver/src/__tests__/__snapshots__/index.test.ts.snap, packages/3id-did-resolver/src/__tests__/index.test.ts, packages/3id-did-resolver/src/index.ts
Add support for multcodec encoded keys in the `3id-did-resolver` in a backwards compatible manner. Backwards compatibility can be removed once we use js-did everywhere, as all documents will use the multcodec keys at that point.
=> feat(3id-did-resolver): Support new multicodec key format

packages/ceramic-cli/src/ceramic-cli-utils.ts
Without this change `pin ls` command emits an error on invalid docId.
=> `pin ls` arguments are optional. No arguments means list all documents.

packages/ceramic-common/src/doctype.ts, packages/ceramic-core/package-lock.json, packages/ceramic-core/package.json
The doctype class getters now return the pending state in `next` if present. Just as already done in the `document` class previously.
=> fix: doctype getters now returns next state

packages/ceramic-common/src/utils/doctype-utils.ts
toISOString always uses UTC+0. Changed to use local time instead.
=> fix(common): Output time in local timezone

packages/ceramic-cli/package.json, packages/ceramic-core/src/store/pin-store.ts, packages/ceramic-doctype-three-id/package.json, packages/ceramic-doctype-tile/package.json, packages/ceramic-http-client/package.json
Somehow, these were missing, yet are required for packages to work.
And by the way remove lodash dependency. It was used just for `_.noop`.
=> Specify actually used dependencies in corresponding package.json

packages/ceramic-core/src/__tests__/document.test.ts, packages/ceramic-doctype-three-id/src/__tests__/__snapshots__/three-id-doctype.test.ts.snap, packages/ceramic-doctype-three-id/src/__tests__/three-id-doctype.test.ts, packages/ceramic-doctype-three-id/src/three-id-doctype-handler.ts, packages/ceramic-doctype-three-id/src/three-id-doctype.ts, packages/ceramic-doctype-tile/src/__tests__/tile-doctype.test.ts, packages/ceramic-doctype-tile/src/tile-doctype-handler.ts, packages/ceramic-doctype-tile/src/tile-doctype.ts
This PR addresses two issues:
1. Actually verify that the signature was made by the DID that created the document
2. Don't add existing metadata to new records
=> fix: verify that signatures where made by correct DID

packages/ceramic-cli/README.md
npm install -g ceramic-cli fails with `'ceramic-cli@latest' is not in the npm registry.`
prepended `@ceramicnetwork/`
=> update npm name

packages/ceramic-cli/src/bin/ceramic.ts, packages/ceramic-cli/src/ceramic-daemon.ts
Closes #350 
- Ran into lockfile issue when trying to run two versions of Ceramic bc the pinning store path argument wasn't working
- Logs from the gateway were not being prefixed with "GATEWAY"
- Changed the arg `stateStorePath` to `pinningStorePath`
- Added the `gateway` option to `ceramicConfig`
=> fix: add gateway to ceramic config and use pinningStorePath for cli

packages/ceramic-cli/src/__tests__/ceramic-daemon.test.ts, packages/ceramic-cli/src/ceramic-daemon.ts, packages/ceramic-common/package.json, packages/ceramic-common/src/ceramic-api.ts, packages/ceramic-common/src/declarations.d.ts, packages/ceramic-common/src/utils/doctype-utils.ts, packages/ceramic-core/src/__tests__/ceramic-api.test.ts, packages/ceramic-core/src/__tests__/ceramic.test.ts, packages/ceramic-core/src/ceramic.ts, packages/ceramic-core/src/document.ts, packages/ceramic-http-client/src/ceramic-http-client.ts, packages/ceramic-http-client/src/document.ts
- implement `loadDocumentRecords` API
- implement full serialize/deserialize record functionality
- use `uint8arrays` instead of `Buffer`
- add and adapt tests
=> Implement loadDocumentRecords API

packages/3id-did-resolver/src/index.ts, packages/ceramic-common/src/utils/doctype-utils.ts, packages/ceramic-core/src/document.ts, packages/ceramic-doctype-tile/src/tile-doctype-handler.ts, packages/ceramic-doctype-tile/src/tile-doctype.ts
Fixes:
* resolve DIDs correctly in tile handler
* resolve DIDs with `version-id` parameter
* `version = '0'` should refer to the genesis version of a document
* properly rotate keys `owners` in tile doctype
=> fix: properly handle versions and key rotations

packages/ceramic-cli/src/ceramic-logger-plugins.ts, packages/ceramic-common/src/logger-provider.ts, packages/ceramic-core/src/ceramic.ts
Keep log file names consistent across all instances of ceramic. Most people are not running both a node and a gateway so we don't need to add those labels to log file names.
If you do run both you can always set different paths  with the `--log-path` flag or use different filesystems (e.g. running ceramic in containers).
- Removed component name from log filename
=> feat: remove log differentiation for gateway

packages/ceramic-cli/src/__mocks__/fs.ts, packages/ceramic-cli/src/__tests__/ceramic-logger-plugins.test.ts, packages/ceramic-cli/src/ceramic-daemon.ts, packages/ceramic-cli/src/ceramic-logger-plugins.ts
1. We don't want to keep log files to for a long time (they will get large and take up space unnecessarily). We also don't want to implement full rotation because it can be complicated and is not needed atm.
2. With loki 2.0, arrays in json log messages are ignored, so we want to use dictionaries as much as possible.
1. "Rotate" logs--so we maintain 2 files per filename, the first `*.log` is being actively written to and the second `*.log.old` contains logs from the previous 60 minutes
2. Use `headers` dictionary instead of `rawHeaders` array
=> Log file rotation and small improvement

packages/docid/src/index.ts
re @PaulLeCam 
Changes docid.toUrl() to not require a base, and now always returns base36 so that always urls safe
=> feat(docid): base36 toUrl

packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/http-client/src/ceramic-http-client.ts, packages/http-client/src/document.ts, packages/http-client/src/utils.ts
- add Ceramic client configuration
- replace `setInterval` with `setTimeout`
- disable Ceramic client document polling by default - issue [499](https://github.com/ceramicnetwork/js-ceramic/issues/499)
- fix `applyRecord` functionality - issue [534](https://github.com/ceramicnetwork/js-ceramic/issues/534)
=> Ceramic client config

packages/3id-did-resolver/package-lock.json, packages/3id-did-resolver/package.json, packages/3id-did-resolver/src/__tests__/__snapshots__/index.test.ts.snap, packages/3id-did-resolver/src/__tests__/index.test.ts, packages/3id-did-resolver/src/index.ts, packages/3id-did-resolver/src/legacyResolver.ts, packages/core/src/__tests__/document.test.ts, packages/core/src/store/__tests__/state-store-integration.test.ts, packages/doctype-tile/src/__tests__/__snapshots__/tile-doctype.test.ts.snap, packages/doctype-tile/src/__tests__/tile-doctype.test.ts
Resolves v0 3ids through api, likely in future will want make sure all existing did docs are available in ipfs elsewhere (ie our ceramic ipfs node), and ipfs instance can be passed from ceramic instance already passed to resolver. Likely would not be reliable to resolve through existing 3box ipfs node, as have to directly connect and ipfs ceramic/3box versions diverging.
=> feat: 3id resolve v0 and v1 3ids

packages/cli/package-lock.json, packages/cli/package.json, packages/common/package-lock.json, packages/common/package.json, packages/core/package-lock.json, packages/core/package.json, packages/core/src/__tests__/document.test.ts, packages/core/src/ceramic.ts, packages/core/src/store/__tests__/state-store-integration.test.ts, packages/doctype-tile/package-lock.json, packages/doctype-tile/package.json, packages/doctype-tile/src/__tests__/three-id.test.ts, packages/doctype-tile/src/__tests__/tile-doctype.test.ts, packages/http-client/package-lock.json, packages/http-client/package.json, packages/http-client/src/ceramic-http-client.ts
Bump DIDs to the latest version. Also bumps `key-did-provider-ed25519`.
In addition we also set the resolvers to the DID instance, in both http-client and core.
=> chore: bump to dids@1.0.0

packages/doctype-tile/src/tile-doctype-handler.ts
* Allow both `null` and `undefined` in genesis record
* Properly apply the first signed record if genesis record has no content
=> fix(doctype-tile): properly handle unsigned genesis records

packages/doctype-tile/src/tile-doctype.ts
Main painpoint was that `family` could not be set. But we should not restrict what could be set in the metadata header.
=> fix(doctype-tile): unbreak tile makeGenesis metadata

packages/common/src/utils/doctype-utils.ts, packages/doctype-caip10-link/src/__tests__/__snapshots__/caip10-link-doctype.test.ts.snap, packages/doctype-caip10-link/src/__tests__/caip10-link-doctype.test.ts, packages/doctype-caip10-link/src/caip10-link-doctype.ts
Some small changes to the `caip10-link` doctype:
* Don't allow arbitrary data in the genesis header
* Include a family to make indexing easier
* No need to include past header in the new record
=> fix(doctype-caip10-link): solidify data structure

packages/3id-did-resolver/package.json, packages/common/package.json, packages/core/package.json, packages/docid/package.json, packages/doctype-caip10-link/package.json, packages/doctype-tile/package.json, packages/http-client/package.json, packages/pinning-aggregation/package.json, packages/pinning-ipfs-backend/package.json, packages/pinning-powergate-backend/package.json
- use `1.0.2` version of `cids` dependency until IPFS update (IPFS depends on earlier version of `cids`)
=> CID version fix

packages/cli/package.json, packages/core/package.json, packages/docid/package.json, packages/key-did-resolver/package.json
- use specific versions for `multiformats` dependencies
--`multiformats: 3.0.3`
--`multibase: 3.0.1`
=> Use specific versions for multiformats dependencies

packages/docid/package.json
This is causing issues when importing some ceramic packages.
=> fix(docid): Add missing uint8array dep

packages/core/src/__tests__/document.test.ts, packages/core/src/document.ts
This does 2 things. First it cleans up the conflict resolution code so _pickLogToAccept returns which log it chose rather than a boolean, to increase code readability.  It also changes the conflict resolution fallback to compare the CIDs of the last log entries rather than the first, to match what the CAS does.
This PR should not be considered a blocker to releasing tomorrow
=> feat(core): Cleanup and fix conflict resolution

packages/cli/src/ceramic-daemon.ts
Just wanted to group the health check under the `/node` path.
=> fix(cli): rename healthcheck endpoint

packages/key-did-resolver/package.json
This PR renames the `@ceramicnetwork/key-did-resolver` package to `key-did-resolver`. The reason for this is to make the name symmetrical with packages like `key-did-provider-ed25519`, `3id-did-provider`. Also in the future we might want to move this package into a separate repo that is more focused on DID related things.
=> chore(key-did-resolver): rename package

packages/cli/src/ceramic-daemon.ts
Closes #703 
In gateway mode ceramic should not be able to publish or anchor documents
- Replaced handler for `/documents` endpoint when in gateway mode to use `createDocumentFromGenesis` with publish and anchor set to false
=> Fix gateway endpoints

README.md, packages/common/src/utils/doctype-utils.ts, packages/core/package.json, packages/core/src/ceramic.ts, packages/doctype-tile/package.json, packages/doctype-tile/src/__tests__/three-id.test.ts, packages/doctype-tile/src/__tests__/tile-doctype.test.ts, packages/http-client/package.json, packages/http-client/src/ceramic-http-client.ts, packages/http-client/src/document.ts, packages/key-did-resolver/README.md
Also includes a commit that fixes the package name used for `key-did-resolver`. 
Packages published as `next`:
```
- @ceramicnetwork/3id-did-resolver@0.6.2-alpha.2
- @ceramicnetwork/cli@0.18.1-alpha.2
- @ceramicnetwork/common@0.15.2-alpha.2
- @ceramicnetwork/core@0.17.2-alpha.2
- @ceramicnetwork/docid@0.4.2-alpha.2
- @ceramicnetwork/doctype-caip10-link@0.12.4-alpha.2
- @ceramicnetwork/doctype-tile@0.12.6-alpha.2
- @ceramicnetwork/http-client@0.8.10-alpha.2
- key-did-resolver@0.2.4-alpha.2
- @ceramicnetwork/pinning-aggregation@0.1.7-alpha.2
- @ceramicnetwork/pinning-ipfs-backend@0.1.7-alpha.2
- @ceramicnetwork/pinning-powergate-backend@0.1.7-alpha.2
```
=> fix(http-client): reload cached documents

packages/cli/src/ceramic-daemon.ts
Closes #705 
When a request is made to the daemon that causes an error the server should respond with an error status code and message. Right not it always responds with 200
- Moved custom error handler to be the last Express handler
- per the [express docs](https://expressjs.com/en/guide/error-handling.html): "you define error-handling middleware last, after other app.use() and routes calls;"
- Removed the `res.json` call so Express can handle the error properly
=> fix: surface express errors properly

packages/common/src/doctype.ts
The `unique` field exists in GenesisRecord.  It doesn't show up in arbitrary record headers, and this field is currently unused
=> chore(core): Remove unused 'unique' field

packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/dispatcher.ts, packages/core/src/document.ts
Our ipfs node on infra is going down periodically (reason tbd) and when it reboots we stop receiving pubsub messages.
Created an issue on js-ipfs repo here https://github.com/ipfs/js-ipfs/issues/3465 -- the error handler for pubsub is broken in Node.js
- Check if we are subscribed every 60 seconds and resubscribe if we are not
- Also updated infra https://github.com/3box/ceramic-infra/commit/164ba63a21b82d5aba6da27dee457079930eb292 to not subscribe from the IPFS API node itself because it was causing this issue https://github.com/ipfs/js-ipfs/issues/3467
- Small change to check that document context includes `anchorService` before removing listeners (which was breaking tests)
=> Hotfix pubsub subscribe

packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/document.ts
This fixes #717, namely that when loading a document from the createDocument method it's pinned state was not being respected.
=> fix(core): respect pinned status on createDocument call

packages/blockchain-utils-validation/package.json
Having trouble using the new creamic version. Looks like this dependency is missing.
=> fix(blockchain-utils-validation): add missing dep

packages/doctype-tile/src/tile-doctype.ts
This fixes the recent regression where documents can't be created from the cli.
=> fix(doctype-tile): make controllers default to current user

packages/cli/src/build-ipfs-connection.util.ts
**This PR disables the use of the DHT in the js-ipfs node used by the cli.**
Having the DHT enabled in it's current configuration is causing quite severe degradation issues when making method calls to ceramic. It doesn't only slow things down, but makes request times very variable (sometimes up to minutes). With the DHT disabled the same calls work much more consistently.
=> fix(cli): Disable DHT

package.json
Resolves #823 
- Adds missing required pkg `jest-environment-uint8array`
=> fix: add missing jest pkg

packages/blockchain-utils-linking/package.json, packages/blockchain-utils-linking/src/__tests__/__snapshots__/cosmos.test.ts.snap, packages/blockchain-utils-linking/src/__tests__/cosmos.test.ts, packages/blockchain-utils-linking/src/cosmos.ts, packages/blockchain-utils-linking/src/index.ts, packages/blockchain-utils-validation/package.json, packages/blockchain-utils-validation/src/blockchains/__tests__/cosmos.test.ts, packages/blockchain-utils-validation/src/blockchains/cosmos.ts, packages/blockchain-utils-validation/src/index.ts
This PR is a migration of [#44](https://github.com/ceramicnetwork/js-3id-blockchain-utils/pull/44)
**Summary** :
Add support for `cosmos:cosmoshub-3` chain to the library
**Dependencies added** :
Tendermint Signer
**Changes**:
=> feat: Add support for cosmos blockchain

packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/dispatcher.ts
Only tries to resubscribe if we are not currently subscribed to the pubsub topic. Will unsubscribe before trying to subscribe. 
Have tested this locally by running an external ipfs node with ceramic. Closed the ipfs node, then restarted it and confirmed that I still receive pubsub messages.
=> fix(core): Improve pubsub resubscribe logic

packages/common/src/utils/doctype-utils.ts, packages/core/src/store/__tests__/level-state-store.test.ts
This was causing multi-node integration tests to fail when comparing their state objects as one node would have `anchorScheduledFor: null` and the other would just be missing that field entirely
=> fix(common): Don't serialize null state fields

packages/common/package.json, packages/common/src/anchor-service.ts, packages/common/src/index.ts, packages/common/src/unreachable-case-error.ts, packages/core/package.json, packages/core/src/__tests__/ceramic-anchor.test.ts, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/ceramic-recover-documents.test.ts, packages/core/src/__tests__/ceramic.test.ts, packages/core/src/anchor/ethereum/ethereum-anchor-service.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/core/src/ceramic.ts, packages/core/src/document.ts, packages/core/src/subscription-set.ts
BTW, shaves 5-20 ms from `POST /documents` request as tested locally.
Replaces #860
=> Recover anchors on startup

packages/common/src/logger-provider.ts, packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/ceramic.ts, packages/core/src/dispatcher.ts, packages/core/src/document.ts, packages/logger/package.json, packages/logger/src/index.ts
Current log output:
```
timestamp=1612816371277 peer=QmdA7MsuBQoYcfnFXTfeUjNGLEFtBzC3A2yTK16Anrz4wT event=received topic=/ceramic/testnet-clay message.from=QmNTneAkkct2PMzJR73gARRPtKjVsBZEHa3wBkX6xCCo5h message.data.typ=2 message.data.
id=18,32,33,49,36,54,38,117,118,200,226,126,15,213,247,91,70,82,131,117,96,71,197,251,220,93,90,103,129,193,181,32,150,89 message.data.tips.kjzl6cwe1jw148i5dltejg923qq8ukoeco3t3y9xcasozji4f4v3e68h9xa1859=bagcqce
raqgkhhpnnfpobtsuk4aqkcoirc64bfoaarpzhejreysgja7pkdv6q message.seqno.0=12 message.seqno.1=247 message.seqno.2=30 message.seqno.3=55 message.seqno.4=66 message.seqno.5=114 message.seqno.6=166 message.seqno.7=183 
message.topicIDs.0=/ceramic/testnet-clay
```
New log output:
```
[Mon, 08 Feb 2021 22:22:20 GMT] service=pubsub …
```
=> Chore(core): Replace logger used in Document and Dispatcher

packages/cli/package.json, packages/cli/src/ceramic-daemon.ts, packages/logger/src/index.ts
As implemented, this doesn't actually replace or remove the existing logging behavior from the ceramic daemon, it simply adds the new logger in place in addition to the old.  So now we'll have two log files containing the http logs, with the following output formats.  Note in the below log samples I added a line `throw new Error("FAILED TO LOAD DOC!!")` right before [this line](https://github.com/ceramicnetwork/js-ceramic/blob/01562c92ea1b837530f751d5737ec6ade0305608/packages/cli/src/ceramic-daemon.ts#L272), to simulate a failed response.
*ceramicdaemon.log*:
```
request.timestamp=1612906056137 request.headers.content-type=application/json request.headers.accept=*/* request.headers.content-length=706 request.headers.user-agent="node-fetch/1.0 (+https://github.com/bitinn/
node-fetch)" …
```
=> chore(cli): Add new express logger to ceramic daemon

packages/common/src/index.ts, packages/common/src/utils/test-utils.ts, packages/core/src/__tests__/ceramic-anchor.test.ts
I'm curious for thoughts on this approach.  If we like this we can roll out the `waitForState` helper in more of our tests over time
=> chore(core): Stabilize ceramic-anchor.test.ts

packages/blockchain-utils-validation/src/blockchains/__tests__/eosio.test.ts, packages/blockchain-utils-validation/src/blockchains/__tests__/ethereum.test.ts, packages/blockchain-utils-validation/src/blockchains/__tests__/filecoin.test.ts, packages/blockchain-utils-validation/src/blockchains/eosio.ts, packages/blockchain-utils-validation/src/blockchains/ethereum.ts, packages/blockchain-utils-validation/src/blockchains/filecoin.ts, packages/doctype-caip10-link-handler/src/caip10-link-doctype-handler.ts
See [this comment](https://github.com/ceramicnetwork/js-ceramic/issues/829#issuecomment-777056611) for more context
=> chore(core): Allow exceptions to escape from blockchain validateLink functions

packages/common/src/pinning.ts, packages/core/src/ceramic.ts, packages/core/src/store/__tests__/state-store-integration.test.ts, packages/core/src/store/pin-store-factory.ts, packages/pinning-aggregation/src/index.ts, packages/pinning-ipfs-backend/src/__tests__/ipfs-pinning.test.ts, packages/pinning-ipfs-backend/src/index.ts
Requiring the `Context` object to already exist before the PinStore is initialized creates some circular initialization dependencies that are getting in the way of cleaning up Ceramic initialization
=> chore(core): Remove Context from PinStoreFactory and PinningBackend

packages/core/src/pubsub/pubsub-message.ts
Apparently dag-cbor can not serialize custom JS symbols
=> fix(core): Generate Query id differently

packages/core/src/pubsub/incoming-channel.ts
Sometimes `this.logger` is empty, so better init TaskQueue this way.
=> fix(core): Init TaskQueue differently in IncomingChannel

packages/cli/src/ceramic-daemon.ts, packages/common/src/anchor-service.ts, packages/core/src/__tests__/ceramic.test.ts, packages/core/src/__tests__/document.test.ts, packages/core/src/anchor/ethereum/ethereum-anchor-service.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/core/src/ceramic.ts
Now you can run `ceramic daemon --network<network>` with any of `testnet-clay`, `dev-unstable`, `local` or `inmemory` and it just works
=> chore(core): Set defaults based on ceramic network

packages/cli/src/ceramic-daemon.ts
This gives us the ip that makes a request to our load balancer so in the metrics dashboard we can track requests per origin properly
=> feat: get origin in logs

packages/cli/src/s3-state-store.ts
It was mentioned the other day that we wanted the ceramic-related stuff in S3 under a `ceramic/` prefix to parallel the `ipfs/` prefix for the ipfs data
=> chore(core): Update state store path in S3 to include ceramic prefix

packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/doctype-tile-handler/src/__tests__/__snapshots__/three-id.test.ts.snap, packages/doctype-tile-handler/src/__tests__/__snapshots__/tile-doctype.test.ts.snap, packages/doctype-tile-handler/src/__tests__/three-id.test.ts, packages/doctype-tile-handler/src/__tests__/tile-doctype.test.ts
Javascript and ms -.-
The blockTimestamp from Eth is correctly denoted in `s`.
=> fix(core): Use seconds for unix timstamp for inmemory anchors

packages/ipfs-daemon/Dockerfile
We want to use @ceramicnetwork/ipfs-daemon instead of js-ipfs-ceramic on our infra nodes so this updates the Dockerfile that will be used to run the former.
- Updates Dockerfile to pull ipfs-daemon from npm and run the binary
=> fix: use npm package for ipfs-daemon in docker

.circleci/config.yml, DEVELOPMENT.md, package.json
We can now install deps by simply running `npm i` or `npm ci`.
Feel free to merge when approved ✅
=> chore: simplify installation process

packages/3id-did-resolver/src/__tests__/index.test.ts, packages/3id-did-resolver/src/__tests__/vectors.json, packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/common/src/doctype.ts, packages/doctype-tile-handler/src/__tests__/three-id.test.ts, packages/doctype-tile-handler/src/__tests__/tile-doctype.test.ts, packages/doctype-tile/src/tile-doctype.ts
With this change now if a deterministic document is created then the `unique` field simply doesn't show up in the doc state at all (unlike today where it's there with the value `"0"`).  When a non-deterministic document is made, the unique field and its random string value are now a part of the document metadata (and thus will now show up on the cli when running `ceramic state`, which isn't currently the case)
=> chore(core): Move 'unique' field into GenesisHeader

packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-cli-utils.ts, packages/common/src/index.ts, packages/common/src/networks.ts, packages/core/src/__tests__/ceramic.test.ts, packages/core/src/ceramic.ts
We have some infra up for ELP but now need a way to run the Ceramic nodes!
- Added "elp" network
- Created enum for different networks (will punt this change if there's hesitancy because just want to get this running asap ideally)
Do we need a test for this? If so will sync with @stbrody about how because I didn't really understand if/how we are testing these networks.
=> feat: add networks enum and elp

packages/ipfs-daemon/src/healthcheck-server.ts
The readings are off on 3Box Ceramic infra--maybe it doesn't work properly when running the process in a container. CPU usage said it was over .95 but we have been around 25% consistently per cloudwatch/grafana dashboards. Also potentially caused 502 gateway errors.
*Anyone can merge!*
=> fix: remove cpu and memory from healthcheck

packages/3id-did-resolver/generateVectorDocuments.js, packages/cli/package.json, packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/cli/src/ceramic-cli-utils.ts, packages/common/src/ceramic-api.ts, packages/common/src/context.ts, packages/core/src/__tests__/ceramic-anchor.test.ts, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/__tests__/ceramic-recover-documents.test.ts, packages/core/src/__tests__/ceramic.test.ts, packages/core/src/__tests__/create-ceramic.ts, packages/core/src/ceramic.ts, packages/doctype-tile/src/tile-doctype.ts, packages/http-client/package.json, packages/http-client/src/ceramic-http-client.ts
This breaks a circular dependency between the http-client and the 3id-did-resolver
=> feat(core, http-client): Remove default DID Resolver and make apps provide via CeramicAPI.setDID()

packages/cli/package.json, packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon/error-handler.ts, packages/cli/src/daemon/log-requests.ts, packages/core/src/ceramic.ts, packages/ipfs-daemon/package.json
- LoggerProvider is exposed as a field of Ceramic core node (Context ≠ DI)
- Beautification for async request handlers. This makes all the errors fall to the generic error handler.
- Generic error handler dumps error message to DiagnosticsLogger and response back with 500 error
- Morgan now exposes caught error as `error_message` and `error_code` tokens.
- Drop health checks
=> Daemon error handling

Dockerfile.ipfs-daemon, packages/ipfs-daemon/.dockerignore, packages/ipfs-daemon/Dockerfile, packages/ipfs-daemon/src/index.ts, packages/ipfs-daemon/src/ipfs-daemon.ts
On infra the migration from 9 to 10 is failing. The very odd thing here is the the image built from `develop` branch results in v9. Images built from `master` are properly using v10. The docker image we are using for the build just pulls from npm so this PR addresses that issue. No guarantees it will fix the migration problem unfortunately but submitted an issue here: https://github.com/ipfs/js-ipfs-repo/issues/299
- Replaces Dockerfile with Dockerfile.ipfs-daemon in root
- Builds ipfs-daemon with lerna
- Uses ipfs path specified in config by default
=> Ipfs daemon docker

packages/core/src/__tests__/create-ceramic.ts, packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/__tests__/state-manager.test.ts, packages/core/src/ceramic.ts, packages/core/src/pubsub/task-queue.ts, packages/core/src/state-management/__tests__/cache-eviction.test.ts, packages/core/src/state-management/execution-queue.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/state-manager.ts
Add one more config parameter: `concurrentTasksLimit`. By default it is the same as `docCacheLimit`.
Sets the upper bound of concurrently processing documents.
=> feat(core): Limit total number of the tasks executed concurrently

packages/cli/package.json, packages/common/package.json, packages/core/package.json
=> chore: Drop dependency on "events" package

packages/3id-did-resolver/src/__tests__/vectors.json, packages/cli/src/ceramic-daemon.ts, packages/common/src/ceramic-api.ts, packages/http-client/src/ceramic-http-client.ts, packages/http-client/src/document.ts
Also updates the MultiQueries API since that also affects the http API.
Did some simple manual testing of a new daemon with an old http-client. I used an old CLI to create and update a tile document, and to pin, unpin, and list pins.  Anything beyond what's covered by that doesn't have test coverage of backwards compatibility.
=> feat(cli,http-client): Update HTTP API to use streams terminology

packages/3id-did-resolver/src/__tests__/index.test.ts, packages/3id-did-resolver/src/index.ts
Apparently we were using an incorrect url for the `@context` property for the json-ld encoded DID document.
Feel free to merge this without my oversight.
=> fix(3id-did-resolver): Use the correct url for json-ld context

Dockerfile.daemon, Dockerfile.ipfs-daemon
Image builds were failing because docid package no longer exists. This pr cleans up the docker image code and avoids such issues in the future.
=> fix: update docker images for streamid package

packages/common/package.json, packages/common/src/index.ts, packages/common/src/logger-base.ts, packages/common/src/logger-provider-browser.ts, packages/common/src/logger-provider.ts, packages/common/src/loggers-browser.ts, packages/common/src/loggers.ts
~~will revisit tmrrw, some cleanup/types, and had some trouble testing locally and getting dependencies to resolve properly~~
likely better long term solutions after, but can be revisited at same time as we work on core working in browser again, there may be other options for libraries as well, but wanted to minimize any changes there since we have a lot built on current log formats.
=> feat: seperate node and browser loggers

packages/core/src/store/level-state-store.ts
When using `js-ceramic` with webpack, nodes can't be used due to the use of `fs` in the Level store. Since `fs` is `undefined` in web browsers, a simple solution is to only use `fs` when it's defined. There seems to only be 1 occurance in `js-ceramic` of this, and I updated it accordingly.
=> fix(store): web browsers don't have access to fs

packages/3id-did-resolver/src/__tests__/vectors.json, packages/3id-did-resolver/src/index.ts
The did-core spec requires the ISO timestamps to not include milliseconds.
=> fix(3id-did-resolver): Don't include ms in timestmaps

packages/common/src/ceramic-api.ts
CeramicApi is currently incompatible with CeramicClient and Ceramic core.
=> fix(common): CeramicApi compatibility

packages/common/src/docopts.ts, packages/stream-tile/src/tile-document.ts
Also cleans up the doc comments for the `SyncOptions` enum
=> chore(stream-tile): Add doc comments for TileMetadataArgs

packages/core/src/ceramic.ts, packages/streamid/src/__tests__/commit-id.test.ts, packages/streamid/src/__tests__/stream-id.test.ts, packages/streamid/src/commit-id.ts, packages/streamid/src/stream-id.ts, packages/streamid/src/stream-ref.ts
No Symbol.hasInstance voodoo. Babel deserves its name.
Should solve #1311
=> feat: Get instance comparison by hand

packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-daemon.ts
Less friction to serve it from any address so that a proxy is not required
=> feat(cli): use 0 address for default hostname

packages/stream-tile/src/tile-document.ts
Makes the rest of the TileDocument APIs consistent with that of `TileDocument.create()`, which accepts `T | null | undefined`
=> fix(stream-tile): TileDocument content can always be null or undefined

package-lock.json, package.json
Apparently, it is a prerequisite for rxjs bump
=> chore: Bump typescript to 4.2.4

packages/cli/src/__tests__/ceramic-error.test.ts, packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon/log-requests.ts
We want to be able to show requests per endpoint in our monitoring dashboards
- Use express routers to organize request url, path, and params
- Add params to http-access logs
- Clean up http logs with string wrapping (to follow [logfmt](https://brandur.org/logfmt))
1. It's harder to read the endpoints now in the code. Generally these routes would be organized in separate files. I'm down to move towards making this cleaner and more organized if people agree it would be helpful. Quick change.
2. 404s will not have these log properties assigned properly because they don't lead to any real handler. So the logs will look like the old format.
Old format
```js
[Thu, 06 May 2021 19:35:31 GMT]
service=http-access
ip=35.203.252.113
ts=2021-05-06T19:35:31.668Z
method=GET
// notice urls and path …
```
=> Daemon http paths and params

packages/ipfs-topology/src/ipfs-topology.ts
We don't want to throw if a network is not provided to the ipfs-daemon/topology, instead we want to keep the behavior of logging a warning.
- Return `null` instead of throwing
- Renamed the type checking variable to make it more clear why it's there
=> fix(ipfs-topology): return null when no network is given for peerlist

packages/http-client/src/__tests__/document.test.ts, packages/http-client/src/document.ts
Previously, two subscriptions on a stream state resulted in two streams of HTTP update calls. Say, one HTTP call is marked `U`, and sync interval is four dashes (~seconds). With two independent `.subscribe` calls for one `TileDocument` object we would have: `UU----UU----UU----`.
This PR makes it back to `U----U----U----` regardless of how many subscriptions are active. The stream of HTTP calls starts when the first observer arrives, and stops when the last observer unsubscribes.
=> fix(http-client): Allow just one stream of sync http calls

packages/key-did-resolver/package.json, packages/key-did-resolver/src/__tests__/__snapshots__/index.test.ts.snap, packages/key-did-resolver/src/__tests__/__snapshots__/secp256r1.test.ts.snap, packages/key-did-resolver/src/__tests__/index.test.ts, packages/key-did-resolver/src/__tests__/secp256r1.test.ts, packages/key-did-resolver/src/index.ts, packages/key-did-resolver/src/secp256r1.ts, packages/key-did-resolver/tsconfig.json
I used JsonWebKey2020 which uses publicJwk to map to an object? This is the first use of publicJwk. secp256k1 and ed25519 uses publicKeyBase58 which uses a string.
=> Create a secp256r1 resolution method

packages/core/src/__tests__/state-manager.test.ts, packages/core/src/state-management/state-manager.ts
This PR bundles 3 different small cleanups to how Ceramic handles the polling for and application of anchor commits. Reviewers may find it helpful to look at the 3 commits that make up this PR independently, as they all have slightly different goals. I also plan to merge those 3 commits separately, without squashing them into a single commit as I usually do for PRs.
=> Cleanups to anchor handling

packages/key-did-resolver/package.json, packages/key-did-resolver/src/__tests__/__snapshots__/index.test.ts.snap, packages/key-did-resolver/src/__tests__/__snapshots__/secp256r1.test.ts.snap, packages/key-did-resolver/src/__tests__/index.test.ts, packages/key-did-resolver/src/__tests__/secp256r1.test.ts, packages/key-did-resolver/src/index.ts, packages/key-did-resolver/src/secp256r1.ts, packages/key-did-resolver/tsconfig.json, tsconfig.json
Add documentation within code. Get `tsc`, `npm run test`, `npm run lint`, and `npm run build` to run in the key-did-resolver directory. Get `npm run docs` to run in the js-ceramic root directory. This supersedes pull request #1261 .
=> Merge secp256r1 key-did-method with npm run docs working

packages/core/src/__tests__/state-manager.test.ts, packages/core/src/conflict-resolution.ts
https://github.com/ceramicnetwork/js-ceramic/issues/730 is the better/more complete fix, but this simpler code change optimizes for the most common cases of trying to re-apply tips already in the log
=> fix(core): Don't refetch CID from IPFS when re-applying commits already in the log

packages/common/src/utils/stream-utils.ts, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/ceramic.test.ts, packages/core/src/__tests__/state-manager.test.ts, packages/core/src/ceramic.ts, packages/core/src/conflict-resolution.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/snapshot-state.ts, packages/core/src/state-management/state-manager.ts, packages/core/src/state-management/stream-from-state.ts
This basically makes loading a stream with a CommitID function as a backdoor way to expose "handleTip" to the public API.
=> feat(core): Loading a CommitID makes the node handle the commit CID as a potential new tip

packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/core/src/__tests__/ceramic-recover-streams.test.ts, packages/core/src/__tests__/ceramic.test.ts, packages/core/src/ceramic.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/state-manager.ts
If you try to create or update a stream in a way that requests an anchor (either because of the defaults or because of explicitly requesting `anchor: true`), then the operation throws an exception. This means that when creating a stream with `anchor:true` an exception will be thrown so the application code will *not* get back a StreamID even though the stream was actually successfully created.  I decided that was okay in this case, even though I decided it *wasn't* okay in https://github.com/ceramicnetwork/js-ceramic/pull/1487, because in this case trying to anchor when no CAS is set up is a configuration error, which you'll want to notice and fix ASAP, rather than a transient runtime error due to temporary unavailability.
=> feat(core,cli): Add --disable-anchors flag to allow ceramic to start up without a working CAS

packages/common/src/anchor-service.ts, packages/core/src/anchor/ethereum/ethereum-anchor-service.ts, packages/core/src/anchor/ethereum/ethereum-anchor-validator.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/core/src/ceramic.ts, packages/core/src/conflict-resolution.ts, packages/stream-caip10-link-handler/src/caip10-link-handler.ts, packages/stream-tile-handler/src/tile-document-handler.ts
This is important so that Ceramic nodes running with --disableAnchors can still validate AnchorCommits
=> feat(core): Split AnchorService from AnchorValidator

packages/core/src/anchor/ethereum/ethereum-anchor-validator.ts
Without this change I get an error when trying to load a stream on dev-unstable that has been anchored against rinkeby.
```
Error loading transaction info for transaction 0xd05dd4d973596d766e9d1f2ae62aa7ca740480c96cd763d48d77cc19b8680518 from Ethereum: Error: No ethereum provider available for chainId eip155:4
Error: No ethereum provider available for chainId eip155:4
```
The fact that we're *not* seeing these errors in the integration tests has me pretty confused as to why not...
=> fix(core): Add information for validating transactions on rinkeby

packages/3id-did-resolver/src/__tests__/vectors.json, packages/3id-did-resolver/src/error-representation.ts, packages/3id-did-resolver/src/index.ts
"created" timestamp refers to a time of DID Create Operation. By design of 3id, create operation timestamp could be any time in the past, and there is no way to determine it via anchor commits. An anchor commit is only present after 3id update operation, which is effectively key rotation. So, "created" field has to be removed.
=> feat: Drop "created" metadata property from 3id did resolution result

packages/3id-did-resolver/src/__tests__/index.test.ts, packages/3id-did-resolver/src/__tests__/vectors.json, packages/3id-did-resolver/src/index.ts
3id-did-resolver returns now only the latest anchored state, or genesis state for vanilla DID URL like `did:3:foo`. See #1520
=> feat: Return last anchored state

packages/cli/package.json, packages/common/package.json, packages/common/src/stream.ts, packages/core/package.json, packages/core/src/__tests__/state-manager.test.ts, packages/core/src/conflict-resolution.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/state-manager.ts, packages/http-client/package.json, packages/stream-caip10-link/package.json, packages/stream-tile-handler/package.json, packages/stream-tile-handler/src/tile-document-handler.ts
There can be a case, when a stream has only genesis commit. Its signature has to be verified. On the other hand, a stream can has more commits, which can provide timestamp information important for signature verification. A Ceramic node has to verify only lone-genesis signature, while postponing verification for multi-commit streams until all the commits are available
This has to be the case, until proper full-log state reconstruction is available.
---
v2 approach after the global prettier-ification.
Replaces https://github.com/ceramicnetwork/js-ceramic/pull/1518
=> feat: Check signature of a lone genesis

packages/core/src/pubsub/pubsub.ts
To ensure no line breaks in the pubsub service logs (see for what the logs look like before this change https://github.com/ceramicnetwork/js-ceramic/issues/1538)
- convert seqno buffer to base16 string
- remove message data because it is redundant and makes the logs messy
The logs now
```
[Thu, 15 Jul 2021 13:24:33 GMT] service=pubsub peer=QmW4V8TbfaeSWYsbBdtqpydyid2bXkM8RFiEcCw8rHb7k2 event=received topic=/ceramic/testnet-clay message.topicIDs.0=/ceramic/testnet-clay message.from=QmQotCKxiMWt935TyCBFTN23jaivxwrZ3uD58wNxeg5npi message.seqno=2f188761af038ec4 message.receivedFrom=QmQotCKxiMWt935TyCBFTN23jaivxwrZ3uD58wNxeg5npi message.typ=1 message.id=EiBED73bwoCtayzj-RP9XauIbtBV7l-R2zwXRmeS-r5Tyw message.stream=k2t6wyfsu4pfzdupeqsehss3t6zu6in8a5kt64uvs0wfl7dbx5mn5yscxld19q …
```
=> fix(core): convert pubsub seqno to string

packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/dispatcher.ts
This is a regression that was causing my CAS consensus test to fail
=> fix(core): Properly cache IPFS lookups with paths

.github/workflows/docker-image.yml
Replaces keys in `client_payload` to include `env_tag` and `sha_tag`. This gets sent to our webhook.
=> Clean up CD workflow

packages/cli/package.json, packages/cli/src/ceramic-daemon.ts
This PR adds support for `did:ethr` in the CLI daemon.
To create ceramic documents using `did:ethr` one can use [Veramo](https://github.com/uport-project/veramo/pull/627)
Current implementation assumes that ceramic node is being run with `--ethereum-rpc` parameter. E.x.:
```
./bin/ceramic.js daemon --network inmemory --debug --ethereum-rpc https://mainnet.infura.io/v3/5ffc47f65c4042ce847ef66a3fa70d4c
```
=> feat(cli): ethr-did-resolver support for mainnet

packages/cli/src/ceramic-daemon.ts, packages/common/src/docopts.ts, packages/core/src/__tests__/ceramic-anchor.test.ts, packages/core/src/__tests__/state-manager.test.ts, packages/core/src/conflict-resolution.ts, packages/core/src/state-management/state-manager.ts, packages/stream-caip10-link/src/caip10-link.ts, packages/stream-tile/src/tile-document.ts
If an error is encountered while applying commits as part of loading a stream, the application process stops and the stream is returned with as much of the state as could be validly constructed
=> feat(core): Invalid commits don't prevent loading a stream

packages/blockchain-utils-linking/package.json, packages/blockchain-utils-validation/package.json
Resolves the warning we've been seeing anytime Ceramic is run:
```
@polkadot/util has multiple versions, ensure that there is only one installed.
Either remove and explicitly install matching versions or dedupe using your package manager.
The following conflicting packages were found:
7.1.1   /home/spencer/js-ceramic3/node_modules/@polkadot/util-crypto/node_modules/@polkadot/util
6.11.1  /home/spencer/js-ceramic3/node_modules/@polkadot/util
```
=> chore(blockchain-utils-linking,blockchain-utils-validation): Upgrade '@polkadot/util' package

packages/ipfs-daemon/README.md
The original URL points to the private dashboard so I swapped it for the public url that anyone can view.
=> docs(ipfs-daemon): change dockerhub url to public

packages/core/src/__tests__/tile-controller.test.ts, packages/stream-tile-handler/src/tile-document-handler.ts
Right now, controller change comes into effect only after a tile is anchored. Here we allow a new controller to edit a tile without waiting for an anchor.
Prompted by HackFS discord message.
=> feat: Allow updating tile immediately after controller change

packages/cli/package.json, packages/cli/src/ceramic-daemon.ts
and use latest nft-did-resolver
=> feat: Rely on default nft-did-resolver subgraphs

package-lock.json, packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts
In order to introduce a config file for the daemon with automatic parsing, I need all the config options to have a single type - 'corsAllowedOrigins' is the one field causing issues given it can be either a single string or an array of RegExps.  I don't totally follow how express uses this field, but as far as I can tell converting the input to a RegExp shouldn't be necessary?  Could also try to go in the direction of moving to always being an array of RegExp, but when I tried to represent the default case as `new RegExp('*')` I get an Eslint error: `Invalid regular expression: /*/: Nothing to repeat.(no-invalid-regexp)`.
=> chore(cli): Use consistent type for 'corsAllowedOrigins'

packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon-config.ts
Pass `resolvers.nft-did-resolver` to nft-did-resolver.
In an ideal universe, one could iterate over keys of `resolvers`, and initialize (and dynamically include!) the appropriate resolvers, but this IMO is for the next time, when dynamic non-http modules are a thing.
=> feat: configure nft-did-resolver via config file

packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-cli-utils.ts
Also fully removes the `--validate-streams`, `--max-healthy-cpu`, and `--max-healthy-memory` flags, which already don't do anything.
=> chore(cli): Deprecate advanced CLI flags

packages/3id-did-resolver/src/index.ts, packages/core/src/ceramic.ts, packages/key-did-resolver/src/index.ts
Following on https://github.com/ceramicnetwork/js-ceramic/pull/1661 this adds named exports for the DID resolvers and the core package.
=> feat: named exports

packages/blockchain-utils-linking/package.json, packages/blockchain-utils-linking/src/__tests__/ethereum.test.ts, packages/blockchain-utils-validation/package.json, packages/blockchain-utils-validation/src/blockchains/__tests__/ethereum.test.ts, packages/core/package.json
Required for 1559 support.
Ceramic uses old ethers packages. CAS uses some Ceramic packages. Due to hoisting, CAS can not really use new ethers packages in presence of the old ethers required by Ceramic packages. So, here we are, updating ethers in Ceramic.
=> chore: Bump ethers to the latest version

packages/core/src/ceramic.ts
Until we have the trusted set of anchor services project complete, we don't want anyone using any anchor service other than our official one
=> chore(core): Prevent using custom CAS on mainnet

.circleci/config.yml, packages/blockchain-utils-validation/src/blockchains/__tests__/eosio.test.ts
- Increase timeout for EOS test in blockchain-utils-validation
- Set max Node memory to 4G
- Change CircleCI executor from `docker` to `machine`: increases available memory from 4G to 7.5G
Note: we are still on "medium" machine, please disregard "medium+" commit.
=> chore: Made test suite run again

packages/core/src/ceramic.ts
Latest mainnet release from last week was not deployed to 3Box infra successfully due to prohibiting passing an anchor service url when on mainnet.
One way to fix this is to use the default mainnet cas url `http://cas.3boxlabs.com` and add static IPs for our nodes to the firewall. This is unfortunately non-trivial as we are using load balancers pointing to ECS targets so we don't have static IPs and setting up a configuration to generate static IPs is likely a week of work to do it right.
The other way to fix it is this PR.
- Do not throw an error if the url passed is `https://cas-internal.3boxlabs.com`
All of our mainnet nodes are still on https://github.com/ceramicnetwork/js-ceramic/commit/3aad2e20d08815c00695f528c18b6b37372552dc with the exception of the gateway …
=> fix(core): allow cas internal url

packages/core/src/ceramic.ts
The 'in' syntax did not work 😥
Tested with the following...
Fails
```
node packages/cli/bin/ceramic.js daemon --anchor-service-api "https://hello.example" --network=elp
...
Ceramic daemon failed to start up:
Error: Cannot use custom anchor service on Ceramic mainnet
```
Succeeds
```
node packages/cli/bin/ceramic.js daemon --anchor-service-api "https://cas.3boxlabs.com" --network=elp
```
```
node packages/cli/bin/ceramic.js daemon --anchor-service-api "https://cas-internal.3boxlabs.com" --network=elp
```
=> fix(core): check for cas url equality

packages/blockchain-utils-linking/src/__tests__/__snapshots__/tezos.test.ts.snap, packages/blockchain-utils-linking/src/tezos.ts, packages/blockchain-utils-validation/src/blockchains/__tests__/__snapshots__/tezos.test.ts.snap, packages/blockchain-utils-validation/src/blockchains/tezos.ts
Taking into consideration Tezos community input, a signing message string should be transferred to a signer as its Micheline representation for security reasons.
Unit tests have been updated.
- https://github.com/Cryptonomic/ConseilJS/blob/fb718632d6ce47718dad5aa77c67fc514afaa0b9/src/chain/tezos/lexer/Micheline.ts#L62L71
- https://tezos.gitlab.io/shell/micheline.html
=> feat: update Tezos message encoding based on community input

packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/__tests__/local-pin-api.test.ts, packages/core/src/__tests__/state-manager.test.ts, packages/core/src/state-management/__tests__/running-state.test.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/running-state.ts
(https://github.com/ceramicnetwork/ceramic/issues/114)
(https://github.com/ceramicnetwork/ceramic/issues/115)
Update RunningState constructor to always take a StateSource argument so you know whether the state came from the state store or from the network. 
Store the pinned CIDs so we won't pin them again
Added a test to the running state tests 
None
=> feat(core): Add stateSource to runningState

packages/core/src/__tests__/local-pin-api.test.ts, packages/core/src/ceramic.ts, packages/core/src/local-pin-api.ts, packages/core/src/state-management/__tests__/running-state.test.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/running-state.ts, packages/core/src/store/__tests__/pin-store.test.ts, packages/core/src/store/__tests__/state-store-integration.test.ts, packages/core/src/store/pin-store.ts
https://github.com/ceramicnetwork/ceramic/issues/118
https://github.com/ceramicnetwork/ceramic/issues/119
https://github.com/ceramicnetwork/ceramic/issues/127
* `PinStore.add` finishes by calling a `setPinnedState` on `RunningState`, which sets the `pinnedState` field to the given state, and updates the `StateSource` for the `RunningState` to `StateStore`. This will prevent repinning of commits on subsequent `Pinstore.add` calls
* `PinStore.add` is given a second, optional argument `force` which if set to true causes it to pin everything in the entire stream history.  This is useful in case the state store and ipfs pin store get out of sync and there are CIDs that aren't pinned in IPFS even though they're included in the state object stored in the state store.
Unit Tests
Before submitting …
=> feat(core): Update running state's pinned commits when adding pins to pin store

packages/stream-tile/src/tile-document.ts
Deterministic tile documents are based on the initial metadata so it should be required 
Tests still work
=> chore(stream-tile): Require metadata when creating a deterministic tile document

packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/http-client/src/ceramic-http-client.ts
https://github.com/ceramicnetwork/js-ceramic/issues/1797 described the case where loading a deterministic stream with provided genesis did not resolve while using multiqueries. However, it should have been. The issue arose due to the HTTP client not passing forth the `genesis` parameter to the ceramic daemon, which this PR fixes.
=> Pass through all parameters for multiquery through the HTTP Client

packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/cli/src/ceramic-daemon.ts, packages/common/src/ceramic-api.ts, packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/__tests__/local-pin-api.test.ts, packages/core/src/local-pin-api.ts, packages/core/src/state-management/repository.ts, packages/http-client/src/remote-pin-api.ts
builds on https://github.com/ceramicnetwork/js-ceramic/pull/1819
=> feat(core,http-client): Add 'force' option to pin API

packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/__tests__/local-pin-api.test.ts, packages/core/src/__tests__/state-manager.test.ts, packages/core/src/state-management/__tests__/running-state.test.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/running-state.ts, packages/core/src/store/__tests__/pin-store.test.ts, packages/core/src/store/__tests__/state-store-integration.test.ts
builds on https://github.com/ceramicnetwork/js-ceramic/pull/1821
=> chore(core): Remove StateSource enum in favor of pinned bool

packages/core/src/utils.ts
Fix a bug.
1. Use `@ceramicnetwork/streamid` instead of `streamid` for import.
2. Import just `StreamID` type.
=> chore: Use proper module name

packages/streamid/src/commit-id.ts, packages/streamid/src/reading-bytes.ts, packages/streamid/src/stream-id.ts, packages/streamid/src/stream-ref.ts
This allows WebStorm's "Any exception" breakpoint to be useful again without hitting tons of false positives from `StreamRef::from`.
An alternative approach would have been to add `StreamID.isValid` and `CommitID.isValid` static methods that never throw but return true or false based on if their input is a valid representation of a StreamID/CommitID.  That approach though would have resulted in `StreamRef::from` parsing the same input twice - once to determine if it was valid, and a second time to actually parse the input into the appropriate data type.
=> chore(streamid): Don't use exceptions as control flow in StreamRef::from

packages/common/src/anchor-service.ts, packages/common/src/pinning.ts, packages/common/src/stream.ts, packages/common/src/utils/test-utils.ts
Some imports are only used to provide type information. Here we replace vanilla import with `import type`.
=> feat(common): Import types, when only types are imported

packages/stream-tile-handler/src/tile-document-handler.ts
It is not clear right now what is `did` and why it is here. Came across this while tinkering with CACAO spec.
=> chore: Rename did parameter to controller on TileDocumentHandler::_verifySignature

packages/canary-integration/package.json, packages/canary-integration/src/__tests__/tile-update.test.ts, packages/common/src/streamopts.ts, packages/stream-tile/src/tile-document.ts
Introduces the ability to make an update with a different DID `asDID` than the one invoking the call. Necessary for OCAP work that is in-progress where updates will be made by the permission holder rather than the permission giver.
Since OCAPs are not fully implemented yet, there are two basic tests. 
The first passes the Ceramic Api's authenticated DID as `asDID` - which works as expected (even though we do switch to using `asDid` instead of `ceramic` for the signatures) 
The second passes a random DID `asDID` and it fails when attempting to sign a Dag JWS. 
More tests will be added as the CACAO library progresses and real use cases become available to test. The changes made should not affect any existing code flows.
- [-] I have updated the …
=> add `asDID` option to TileDocumentHandler

packages/blockchain-utils-linking/package.json, packages/blockchain-utils-linking/src/__tests__/__snapshots__/solana.test.ts.snap, packages/blockchain-utils-linking/src/__tests__/solana.test.ts, packages/blockchain-utils-linking/src/index.ts, packages/blockchain-utils-linking/src/solana.ts, packages/blockchain-utils-validation/package.json, packages/blockchain-utils-validation/src/blockchains/__tests__/solana.test.ts, packages/blockchain-utils-validation/src/blockchains/solana.ts
Support Solana wallet using the most popular Solana wallet adapter (https://github.com/solana-labs/wallet-adapter).
Only support these wallets that provide a signMessage method for signing arbitrary bytes
Phantom
Solflare
Slope
TokenPocket 
(https://github.com/solana-labs/wallet-adapter/blob/master/FAQ.md#how-can-i-sign-and-verify-messages).
- Local unit test
run local unit test
- Wallet integration test
1. install these wallets (Phantom/Solflare/Slope/TokenPocket)  in my browser.
2. using Solana wallet adapter as provider to SolanaAuthProvider.
3. invoke authenticate() can properly pop up related wallets to sign the message and produce deterministic result.
4. verify the signature in created …
=> support solana wallet

packages/core/src/__tests__/ceramic.test.ts, packages/core/src/ceramic.ts, packages/core/src/utils.ts
also includes a small code cleanup regarding how we ensure the genesis commit already exists when querying with genesis content (FYI @haardikk21)
=> chore(core): log multiquery errors

packages/canary-integration/babel.config.json, packages/canary-integration/jest.config.json, packages/canary-integration/package.json, packages/core/package.json, packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/ceramic.ts, packages/core/src/state-management/repository.ts, packages/stream-tile-handler/package.json
Replaces https://github.com/ceramicnetwork/js-ceramic/pull/1872
Please, disregard changes to ancillary stuff like Jest configs: this is to make the test suite run. Jest and such have to be upgraded.
=> feat: Disable double unpinning by moving handlePinOpts out of Repository::load

.circleci/config.yml, packages/canary-integration/package.json, packages/canary-integration/src/create-ipfs.ts, packages/cli/babel.config.js, packages/core/src/__tests__/ipfs-util.ts
Make CircleCI test using go-ipfs and js-ipfs based on `IPFS_FLAVOR` env variable. Uses go-ipfs by default, but if `IPFS_FLAVOR` env is set to `js` or `JS`, then `js-ipfs` is used.
=> feat: Test with both go-ipfs and js-ipfs

packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/ceramic.ts, packages/core/src/dispatcher.ts, packages/core/src/pubsub/__tests__/pubsub-ratelimit.test.ts, packages/core/src/pubsub/pubsub-ratelimit.ts
Tested manually
I thought about adding this fully to the ceramic config and daemon config file, but given that query rate limiting is likely going away soon with tipsync, I figured it might be better just to use an env var as a quick fix that we can easily remove later.
=> feat(core): Add env var to configure pubsub qps limit

packages/common/src/utils/stream-utils.ts, packages/core/src/__tests__/ceramic.test.ts, packages/core/src/__tests__/state-manager.test.ts, packages/core/src/state-management/execution-queue.ts, packages/core/src/state-management/running-state.ts, packages/core/src/state-management/state-manager.ts
This is a re-apply of 3290a66db7f4063aac1df3781bef2962442740e2 after it was
reverted in 8c73805991e1f3d960f5451af8fa795fb260fef2.
=> fix(core): Allow loading multiple CommitIDs for the same stream in parallel

packages/cli/package.json
Fixes our current build failure
=> fix(cli): Pin version of '@types/abstract-leveldown' package

packages/ipfs-topology/src/ipfs-topology.ts
The host domain for the CAS ipfs has changed. This will stop producing false positive warnings about not being able to connect to 3boxlabs nodes
E.g. https://github.com/ceramicnetwork/js-ceramic/issues/1975
=> feat(ipfs-topology): update multiaddresses

packages/common/package-lock.json, packages/common/package.json
As reported by Ceramic community member [here](https://github.com/ceramicnetwork/js-ceramic/issues/1980) and in Discord, the maintainer of [colors](https://github.com/Marak/colors.js) pushed an [infinite loop](https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6) into the code base. The module is used by one of our logging dependencies called [overnight](https://github.com/seanpmaxwell/overnight).
This PR adds a package-lock file to `js-ceramic/packages/common` in order to fix the colors version to an earlier version that is compatible with overnight but does not include this... weirdness.
Tested this locally by doing
```
npm install
npm run build
node packages/cli/bin/ceramic.js daemon
```
=> hotfix(common): lock colors dependency to stop infinite loop

packages/cli/src/ceramic-daemon.ts
Update the Ceramic daemon health-check to return unhealthy if its associated IPFS node in offline.
This ensures that ECS does not mark Ceramic as ready-to-use until IPFS is fully operational.
=> fix: return 503 during health-check if connected ipfs is not online

.github/workflows/npm-publish.yml, packages/cli/package.json, packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-cli-utils.ts
We are now providing an alert after most functions that looks like the following: 
 
The updated help looks like the following: 
The deprecation notice has been run multiple times to ensure that it behaves properly & ANSI escapes were used to ensure no issues with colors/different Operating Systems.
=> Add Deprecation notice to all functions that have been moved to the Glaze CLI

packages/blockchain-utils-linking/package.json, packages/blockchain-utils-linking/src/__tests__/__snapshots__/ethereum.test.ts.snap, packages/blockchain-utils-linking/src/__tests__/ethereum.test.ts, packages/blockchain-utils-linking/src/ethereum.ts, packages/canary-integration/src/__tests__/caip10/ethereum.test.ts
From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap):
> A WeakMap is a collection of key/value pairs whose keys must be objects, with values of any arbitrary JavaScript type, and which does not create strong references to its keys. That is, an object’s presence as a key in a WeakMap does not prevent the object from being garbage collected. Once an object used as a key has been collected, its corresponding values in any WeakMap become candidates for garbage collection as well — as long as they aren't strongly referred to elsewhere.
Here we utilise WeakMap to effectively attach chainId property to an ethereum provider, as long as the provider is available somewhere in JS memory.
A chainId value is set in the weak map the first time chainId is …
=> feat: Cache chainId requests to providers

packages/cli/package.json, packages/core/package.json, packages/ipfs-daemon/package.json
=> chore: Fix libp2p-mplex version

packages/ipfs-daemon/src/ipfs-daemon.ts
Set gossipsub cache TTL to 2 minutes since the current 30 second TTL has been ineffective in preventing pubsub floods.
- [js-libp2p issue](https://github.com/libp2p/js-libp2p/issues/1043) describing the pubsub flood
- [js-libp2p-gossipsub v0.9.2](https://github.com/ChainSafe/js-libp2p-gossipsub/tree/v0.9.2) (version used in Ceramic 1.x)
- [Gossipsub `seenCache`](https://github.com/ChainSafe/js-libp2p-gossipsub/blob/v0.9.2/ts/index.ts#L170)
- [TimeCache](https://github.com/daviddias/time-cache)
=> hotfix: set gossipsub seen cache ttl to 2 minutes

packages/common/src/context.ts, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/__tests__/dispatcher-mock-ipfs.test.ts, packages/core/src/__tests__/dispatcher-real-ipfs.test.ts, packages/core/src/ceramic.ts, packages/core/src/dispatcher.ts
If we have outstanding requests to ipfs during shutdown, especially ones that will take along time, like loading a CID that doesn't exist, then shutdown blocks until those outstanding requests terminate.  We should be able to use an AbortController to proactively abort outstanding networking i/o when we begin shutdown.
=> chore(core): Interrupt blocked ipfs network i/o at shutdown

packages/common/src/utils/stream-utils.ts
Resolves NET-901
Adds serialization/deserialization of CACAO blocks over HTTP
=> NET-901 serde for cacao blocks

.circleci/config.yml, packages/3id-did-resolver/package.json, packages/blockchain-utils-linking/package.json, packages/blockchain-utils-validation/package.json, packages/canary-integration/package.json, packages/cli/package.json, packages/common/package.json, packages/core/package.json, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/dispatcher-real-ipfs.test.ts, packages/http-client/package.json, packages/key-did-resolver/package.json, packages/logger/package.json, packages/pinning-aggregation/package.json, packages/pinning-crust-backend/package.json, packages/pinning-ipfs-backend/package.json, packages/pinning-powergate-backend/package.json, packages/pkh-did-resolver/package.json, packages/stream-caip10-link-handler/package.json, packages/stream-tile-handler/package.json, packages/streamid/package.json
It works. One caveat: had to add `--forceExit` to every jest invocation. Guess, it is because js-ipfs does not clean all the resources after stopped.
=> chore: Revive tests with js-ipfs

packages/blockchain-utils-linking/src/__tests__/__snapshots__/cosmos.test.ts.snap, packages/blockchain-utils-linking/src/__tests__/__snapshots__/eosio.test.ts.snap, packages/blockchain-utils-linking/src/__tests__/__snapshots__/ethereum.test.ts.snap, packages/blockchain-utils-linking/src/__tests__/__snapshots__/filecoin.test.ts.snap, packages/blockchain-utils-linking/src/__tests__/__snapshots__/near.test.ts.snap, packages/blockchain-utils-linking/src/__tests__/__snapshots__/polkadot.test.ts.snap, packages/blockchain-utils-linking/src/__tests__/__snapshots__/solana.test.ts.snap, packages/blockchain-utils-linking/src/__tests__/__snapshots__/tezos.test.ts.snap, packages/blockchain-utils-linking/src/cosmos.ts, packages/blockchain-utils-linking/src/eosio.ts, packages/blockchain-utils-linking/src/ethereum.ts, packages/blockchain-utils-linking/src/filecoin.ts, packages/blockchain-utils-linking/src/near.ts, packages/blockchain-utils-linking/src/polkadot.ts, packages/blockchain-utils-linking/src/solana.ts, packages/blockchain-utils-linking/src/tezos.ts, packages/blockchain-utils-linking/src/util.ts, packages/blockchain-utils-validation/src/blockchains/__tests__/__snapshots__/ethereum.test.ts.snap, packages/blockchain-utils-validation/src/blockchains/__tests__/ethereum.test.ts, packages/blockchain-utils-validation/src/blockchains/__tests__/tezos.test.ts, packages/blockchain-utils-validation/src/blockchains/ethereum.ts, packages/blockchain-utils-validation/src/blockchains/solana.ts
Apparently, found a bug in v2 client communicating with v1 daemon. v2 client should use old CAIP format string in proofs.
=> feat: Use old caip format for proofs

packages/key-did-resolver/package.json, packages/key-did-resolver/src/bigint-mod-arith.ts, packages/key-did-resolver/src/secp256r1.ts, packages/key-did-resolver/src/secp384r1.ts, packages/key-did-resolver/src/secp521r1.ts
Unless it can be really used as ES module.
Copied the relevant code inside.
Relevant issue: https://github.com/juanelas/bigint-mod-arith/pull/6
=> feat: Do not depend on bigint-mod-arith

packages/blockchain-utils-validation/src/blockchains/__tests__/eosio.test.ts
Our tests fail after EOS Jungle endpoint in `@smontero/eosio-signing-tools` became unavailable. See https://github.com/sebastianmontero/eosio-signing-tools/issues/1 for details.
This PR removes the tests that use the failed network.
=> chore: Disable tests using EOS Jungle network

packages/cli/package.json, packages/ipfs-daemon/package.json
- Update to go-ipfs v0.12
- It works on Apple Silicon out of the box, no env variables needed.
=> chore: Use newer go-ipfs

packages/canary-integration/package.json, packages/cli/package.json, packages/common/package.json, packages/core/package.json, packages/http-client/package.json, packages/stream-caip10-link/package.json, packages/stream-tile-handler/package.json, packages/stream-tile-handler/src/tile-document-handler.ts
Related to NET-1253
Bumps `dids` and uses `Date` instead of `number` for `atTime` when calling `verifyJWS`
NOTE: Unable to test it locally yet due to some ESM import issues. Believe @stephhuynh18 is looking more into it.
=> bump dids and use `Date` for `atTime`

packages/blockchain-utils-linking/src/ethereum.ts
Small patch to update the default CACAO expiration time to be 1 day, instead of 1 week.
=> [NET-1240] Update default CACAO expiration time to be 1 day later

packages/blockchain-utils-linking/jest.config.json, packages/stream-tile-handler/src/tile-document-handler.ts
Root cause: Jest resolver is buggy. It tries to import CJS by default; some packages do not properly specify conditional exports, which leads to a failure.
The misbehavior is solved in upcoming Jest v28. We can not use it though right now: it changed the way mocks work, which breaks other tests.
Changes: use `jest-resolver-enhanced` for `blockchain-utils-linking` package to overcome Jest resolver limitations.
Also, to make tests fully green again, fixed an issue in TileHandler. Pass `atTime` option to `did` signature verification only if commit has a timestamp. CC @haardikk21
=> chore: fix polkadot tests

packages/common/src/utils/test-utils.ts, packages/core/src/__tests__/conflict-resolution.test.ts, packages/core/src/store/__tests__/level-state-store.test.ts, packages/core/src/store/level-state-store.ts
More realistic test coverage, plus easier to extend the test in the future.  Will build on this in next PR
=> Switch level-state-store.test.ts to use a real LevelDB instance instead of a mock

packages/core/src/ceramic.ts
The gateway doesn't actually have the real IPFS data for the streams it has in its state store (which is all copied from other node's state stores), so it always fails the ipfs data startup check
=> feat(core): Add env var to skip ipfs data persistence check at startup

packages/canary-integration/src/__tests__/capability.test.ts, packages/stream-tile-handler/src/tile-document-handler.ts
Adds cacao wildcard resource support
Reference [SIWE+ spec](https://www.notion.so/threebox/CACAO-DID-PKH-SIWE-Client-Libraries-5ce1f1f6e8c7417683c2b63e07f91cef#741885cca9d94532afee11a46621ab7d) for motivation. 
Tests for create/update using wildcard resource capability. 
Does change validation a bit, but adds not removes, dont have any version/upgrade concerns at moment
=> feat(stream-tile-handler): add cacao wildcard resource support

packages/canary-integration/src/__tests__/capability.test.ts
I don't really understand why @zachferland's recent commit would have made this teardown take longer.
I suspect that wasn't actually the root cause, and the issue was some upstream package getting updated and slowing down, although it is suspicious that the test that keeps failing is exactly the test file that zach's recent commit touched.  Something fishy is definitely going on here, but hopefully increasing the timeout on the teardown here will help
=> fix(canary-integration): Increase test fixture cleanup timeout

packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/daemon-config.ts
Introduces a custom serializer to properly parse & validate port property passed to daemon-config either via CLI switch option `--port`, `daemon.config.json` or `ENV` variables.
This will solve the daemon being unable to start with a custom port that might be passed as a wrong type due to tool/system limitations (e.g. Docker passes strings vs the expected number type).
`node ceramic.js daemon` -> OK (defaults to 7007)
`node ceramic.js daemon --port 7009` -> OK
`node ceramic.js daemon --port "7009"` -> OK
`node ceramic.js daemon --port 70000` -> NG (_Expected_: exceeds valid port length)
`node ceramic.js daemon --port "S09"` -> NG (_Expected_: non-number/valid port)
```
{
"anchor": {},
"http-api": {
"cors-allowed-origins": [
".*"
],
"port": "7008"
},
"ipfs": {
"mode": "bundled"
}, …
```
=> fix(cli): added daemon-config port number coercion and validation

packages/core/src/ceramic.ts
Now that we have the qa environment up and running, dev-unstable network should anchor to it by default
=> feat(core): replace cas-dev for dev-unstable with cas-qa

packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/daemon-config.ts
- Pass `--config` option from CLI to actual code
- Read connection string for a database
- Specify models to index in the config file
Also: replace `path.resolve` with `URL`-based resolution.
=> Indexing configuration

packages/cli/src/daemon/log-requests.ts
In order to determine what metrics we are able to gather about partners and dapps using Ceramic, we need to examine the full headers produced by dapps in the wild.  The only way to reliably gather this is by temporarily logging full headers in the wild, ie at least on clay.
This is only modifying a well exercised log pathway, the smoke tests should be sufficient.
- [x ] I have tagged the relevant reviewers and interested parties
See https://www.notion.so/threebox/js-ceramic-instrumentation-8e1baf720b764b7ab0cf1e25d8a50da1
=> temporarily log the full headers from dapps in the wild - PLAT-535

.gitignore, packages/stream-model-handler/src/__tests__/__snapshots__/model-handler.test.ts.snap, packages/stream-model-handler/src/__tests__/model-handler.test.ts, packages/stream-model-handler/src/__tests__/schema-utils.test.ts, packages/stream-model-handler/src/model-handler.ts, packages/stream-model-handler/src/schema-utils.ts, packages/stream-model/src/model.ts
Add ajv strict validation of json-schemas to Model
Use draft 2020-12 for validation: https://ajv.js.org/json-schema.html#draft-2020-12
=> Add model stream schema validation.

packages/core/src/ceramic.ts, packages/core/src/indexing/build-indexing.ts
If using an old ceramic daemon config with no `indexing` section, display a warning.
=> feat: warn if indexing is not configured

packages/core/src/indexing/sqlite/__tests__/sqlite-index-api.test.ts, packages/core/src/indexing/sqlite/chronological-order.ts
SQLite, chronological order. I forgot to filter by account. This fixes the mistake.
=> fix: Filter by account

packages/core/src/ceramic.ts, packages/core/src/indexing/__tests__/index-api.test.ts, packages/core/src/indexing/database-index-api.ts, packages/core/src/indexing/local-index-api.ts
Potential controversies:
- We might have indexing database backend not configured. It makes the `queryIndex` method return an empty page. We also log a warning for every query.
- Use `Repository::streamState` to load StreamState for StreamID. We assume that a state store always contains StreamState for an indexed stream.
Base branch is not `development` to reduce mental overhead for reviewing.
=> feat: Make IndexAPI call the database

packages/3id-did-resolver/src/index.ts
Disco team reported the following error: 
```
Uncaught (in promise) Error: Failed to resolve did:3:kjzl6cwe1jw145cszwj09gmsiolltkxvr75uxm40c6zpi3i58ltg78gg1o3c4xo?version-id=0#i31x2JpQ5fbVLsy: invalidDid, TypeError: Cannot read properties of undefined (reading 'state')
```
I suspect this might be because of a multiquery that is not properly resolving. However, it's been difficult to replicate the issue. In this PR an error is thrown if this happens, so that we can validate the hypothesis the next time this error happens.
=> feat(3id-did-resolver): throw error on failed multiquery

packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon/__tests__/collection-query.test.ts, packages/cli/src/daemon/collection-query.ts, packages/cli/src/error-handling-router.ts, packages/core/src/indexing/local-index-api.ts
Add HTTP endpoint `/collection`.
No ordering options.
Few minor improvements à la housekeeping.
=> feat: HTTP endpoint - it works

packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon/__tests__/collection-query.test.ts, packages/cli/src/daemon/collection-query.ts, packages/common/src/utils/http-utils.ts, packages/http-client/src/__tests__/document.test.ts, packages/http-client/src/__tests__/remote-index-api.test.ts, packages/http-client/src/ceramic-http-client.ts, packages/http-client/src/document.ts, packages/http-client/src/remote-index-api.ts, packages/http-client/src/remote-pin-api.ts, packages/http-client/src/utils.ts
Core part:
- Make RemoteIndexApi call HTTP endpoint
Housekeeping:
- Use native JS URL extensively. We do not need `query-string` package anymore.
=> feat: Implement IndexAPI on http client side

packages/cli/src/__tests__/ceramic-daemon.test.ts
Fixes flaky test for /api/v0/collection endpoint by using `did:key:{random}` as account field.
=> fix: user more real request to the collection endpoint

packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/dispatcher-mock-ipfs.test.ts, packages/core/src/__tests__/dispatcher-real-ipfs.test.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/core/src/ceramic.ts, packages/core/src/conflict-resolution.ts, packages/core/src/dispatcher.ts, packages/core/src/state-management/repository.ts, packages/core/src/utils.ts
Makes the `streamId` argument to `Dispatcher.retrieveCommit` mandatory, which means that anytime there is an error loading a commit from IPFS we will have the StreamID it belongs to in the log message
=> chore(core): Always log streamId on errors loading commits from IPFS

packages/core/src/__tests__/ceramic.test.ts, packages/core/src/ceramic.ts
I don't really *love* this approach.  I think it's weird to use a query as a backdoor way to create a stream.  But that's what we did when we introduced https://github.com/ceramicnetwork/js-ceramic/issues/1647 so this seems like the only way to make the behavior actually correct.
=> fix(core): Creating a stream via a multiquery should pin it

packages/common/src/stream.ts, packages/core/src/anchor/anchor-service-response.ts
People in the community are getting confused by it (https://github.com/gitcoinco/dPopp/issues/247).
Now that the anchor service does not anchor on a reliable interval `anchorScheduledFor` is not accurate and keeping it around is just misleading and confusing.  We should get rid of it entirely soon, but for now let's at least mark it as deprecated
=> chore(common,core): Deprecate anchorScheduledFor

packages/blockchain-utils-linking/src/cosmos.ts, packages/blockchain-utils-linking/src/eosio.ts, packages/blockchain-utils-linking/src/filecoin.ts, packages/blockchain-utils-linking/src/near.ts, packages/blockchain-utils-linking/src/polkadot.ts, packages/blockchain-utils-linking/src/solana.ts, packages/blockchain-utils-linking/src/tezos.ts
Auth providers other than Ethereum don't have full support, and often result in bugs for end developers when attempting to use them. This PR adds a warning to all auth providers other than Ethereum letting developers know about this.
No tests.
=> chore: add warnings to auth providers other than ethereum [NET-1578]

packages/blockchain-utils-linking/src/__tests__/polkadot.test.ts, packages/blockchain-utils-validation/src/blockchains/__tests__/polkadot.test.ts, packages/canary-integration/src/__tests__/caip10/polkadot.test.ts
The tests are flaky and fail often.  Polkadot support was added by a community member and we (3BoxLabs) never committed to maintaining support for it.  We're not going to go out of our way to break polkadot support, but we're also not going to spend any resources making sure it keeps working either.  Until such a time as the 3BoxLabs team is ready to commit to maintaining support for linking/validating wallet signatures from non-ethereum chains, lets disable the tests so they don't cause our build pipelines to randomly fail.  Of course other community members are welcome and encouraged to build and maintain support for other chains on their own.
=> fix(blockchain-utils-linking,blockchain-utils-validation,canary-integration): Disable flaky polkadot tests

README.md, packages/core/src/anchor/ethereum/ethereum-anchor-validator.ts, packages/core/src/ceramic.ts
Rinkeby and Ropsten testnets are on their way to being deprecated. This PR lays the foundation to add support for Gnosis Chain and Goerli Testnet to Ceramic. The plan is to use Gnosis Chain mainnet for Clay testnet, and Goerli for Dev.
No tests.
=> feat: add gnosis chain and goerli to supported networks [NET-1556]

packages/cli/package.json, packages/cli/src/s3-state-store.ts, packages/core/package.json
Using Semaphore, nothing fancy. Semaphore limit is set based on the S3 minimum 5500 limit for GET/HEAD requests.
Although reality is a bit more complex, this might be a good first approach. According to the [docs](https://aws.amazon.com/premiumsupport/knowledge-center/s3-503-within-request-rate-prefix/) S3 is really flexible, but it requires the exponential backoff in the ideal case. IMO, it is a responsibility of s3leveldown ([issue](https://github.com/loune/s3leveldown/issues/13) created) to handle that.
I am not certain that the semaphore approach here makes sense, so feel free to say no to it.
=> feat: Attempt to limit concurrent S3 reads

packages/stream-model/src/model.ts
Following our call yesterday, we need to add support for the `documentVersion` view to expose the version to set in mutations.
=> Add `documentVersion` view to model type definitions

packages/core/src/__tests__/ceramic-anchor.test.ts, packages/core/src/__tests__/dispatcher-mock-ipfs.test.ts, packages/core/src/__tests__/local-pin-api.test.ts, packages/core/src/dispatcher.ts, packages/core/src/local-pin-api.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/state-manager.ts
When testing https://github.com/ceramicnetwork/js-ceramic/pull/2258, I noticed the log message was getting printed very often, even with without me sending any requests to my local node.  I investigated further and found that we were filling up the execution and loading queues entirely with messages from pubsub, for streams that aren't even pinned where we won't even wind up actually loading or applying any commits.
This change puts the check for seeing if the stream exists in the state store or in memory cache outside of the loading and execution queue concurrency bottlenecks, and only uses those queues when actually loading a stream over pubsub or applying an actual commit to current state.
I don't know if this issue can really fully explain all the issues that gitcoin is seeing, but it …
=> fix(core): Only use the execution and loading queues when applying commits or loading over pubsub

packages/stream-model-handler/src/schema-utils.ts, packages/stream-model-instance-handler/src/schema-utils.ts, packages/stream-tile-handler/src/schema-utils.ts
@ukstv could you double-check that this fixes the memory growth when associated with validating schemas (both for streams that share a schema and for streams with different schemas)?
=> fix(stream-tile-handler,stream-model-handler,stream-model-instance-handler): Don't cache schemas

packages/stream-model-handler/src/__tests__/views-utils.test.ts, packages/stream-model-handler/src/views-utils.ts
Follow-up on adding the `documentVersion` type for model views, adds the matching logic to the model handler.
=> Accept `documentVersion` as model view type in handler validation

packages/cli/src/__tests__/daemon-config.test.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/daemon-config.ts
Handle:
- `~/` is replaced with `os.homedir()`,
- `./`, `../` are resolved against the config file path,
for:
- `config.logger.logDirectory`,
- `config.stateStore.localDirectory`.
=> feat: Add path expansion to config file handling

packages/common/src/ceramic-api.ts, packages/core/src/__tests__/ceramic.test.ts, packages/core/src/ceramic.ts, packages/http-client/src/__tests__/ceramic-http-client.test.ts, packages/http-client/src/ceramic-http-client.ts
`ceramic.buildStreamFromState(streamState)` builds an instance of a corresponding Streamtype based on the StreamState.
Works on Core and Client.
@pawartur @PaulLeCam
=> feat: Add a method to CeramicAPI that transforms raw StreamState to an instance of Streamtype

packages/blockchain-utils-linking/package.json
Now it is yet another prod dependency.
=> chore(blockchain-utils-linking): Depend on streamid just once

packages/canary-integration/src/__tests__/capability.test.ts, packages/canary-integration/src/__tests__/model-instance-document.test.ts, packages/canary-integration/src/__tests__/model.test.ts, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/ceramic.ts, packages/core/src/indexing/local-index-api.ts, packages/core/src/initialization/make-index-api.ts, packages/stream-model-handler/src/__tests__/model-handler.test.ts, packages/stream-model-handler/src/model-handler.ts, packages/stream-model-instance-handler/src/__tests__/model-instance-document-handler.test.ts, packages/stream-model-instance-handler/src/model-instance-document-handler.ts
This PR puts all indexing and query functionality behind an environment variable flag guard temporarily.  If users discover the new functionality and start creating models or MIDs on mainnet, then any breaking changes we make to those streamtypes as part of testing and finalizing the release would break any existing streams of those streamtypes on the network.  Worse, even if we don't make breaking changes, any MID or Model streams created on mainnet before the necessary changes are in place on the CAS to enable indexing from anchors would never get picked up by indexers performing a historical sync.  We shouldn't have any Model or MID streams created on mainnet until the anchors being performed on mainnet are indexable.
As soon as we're ready to release indexing for real, we should …
=> feat(core,model-handler,model-instance-handler): Disable indexing and query features by default until they are ready

packages/core/src/ceramic.ts, packages/core/src/indexing/database-index-api.ts, packages/core/src/indexing/sqlite/__tests__/read-csv-fixture.util.ts, packages/core/src/indexing/sqlite/__tests__/sqlite-index-api.test.ts, packages/core/src/indexing/sqlite/migrations/1-create-model-table.ts, packages/core/src/indexing/sqlite/sqlite-index-api.ts
It is a breaking change, but we are free _now_ to do this.
=> feat: Store first anchored time in the indexing database

packages/cli/package.json, packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/cli/src/__tests__/ceramic-error.test.ts, packages/cli/src/__tests__/index-api.test.ts, packages/cli/src/__tests__/make-ceramic-core.ts, packages/cli/src/__tests__/make-ceramic-daemon.ts, packages/stream-tests/package.json
- Use Ceramic Client instead of fetchJSON
- Cover http-to-indexAPI flow.
=> chore: Beautify index api test

packages/common/src/stream.ts, packages/stream-caip10-link/src/caip10-link.ts, packages/stream-tile/src/tile-document.ts
I did not add a `controller` accessor to `Model` or `ModelInstanceDocument`, as this can be easily accessed by `metadata.controller`.  I'm happy to add a `controller` accessor though if people think it's useful
=> feat(common): Remove 'controllers' accessor from Stream base class

packages/cli/src/__tests__/make-ceramic-daemon.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon-config.ts, packages/core/src/indexing/build-indexing.ts, packages/core/src/indexing/index-query-not-available.error.ts, packages/core/src/indexing/postgres/__tests__/postgres-index-api.test.ts, packages/core/src/indexing/postgres/postgres-index-api.ts, packages/core/src/indexing/sqlite/__tests__/sqlite-index-api.test.ts, packages/core/src/indexing/sqlite/sqlite-index-api.ts
Add allowQueriesBeforeHistoricalSync to index config.
If set to `false`, calls to `/api/v0/collection` return 503 error "Index for historical data is not available".
CLI creates a new daemon config with the flag set to `true`.
For existing config files, if the flag is absent, default is `false`.
=> feat: Add allowQueriesBeforeHistoricalSync flag to config

packages/cli/src/ceramic-cli-utils.ts
- Uses environment variables to override config file defaults (note: the hierarchy here is cli flags > env vars > config file > defaults)
- Adds env var for indexing db uri
=> feat(cli): use env vars to override config file

packages/core/src/ceramic.ts, packages/core/src/store/__tests__/pin-store.test.ts, packages/core/src/store/__tests__/state-store-integration.test.ts, packages/core/src/store/pin-store-factory.ts, packages/core/src/store/pin-store.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts
I had really been hoping on using this to make stream pinning behavior streamtype-specific so each StreamHandler could specify its own behavior for when streams of that type get pinned. That way the model-specific pinning logic wouldn't have to live in a generic codepath that applies to all streamtypes. But doing that would have been a much bigger refactor and so in the interest of time and simplicity this seemed like the more straightforward change that gets us what we need.
=> feat(core): Pinning a ModelInstanceDocument should also pin its Model

packages/core/src/anchor/ethereum/ethereum-anchor-service.ts
tested manually as there are no tests for this file (a known tech dept). 
I have chosen to represent READY requests as AnchorStatus.PENDING because READY is a CAS specific status for batching.
=> feat(core): Anchor Status for ceramic anchoring READY request status  

packages/core/src/anchor/ethereum/ethereum-anchor-validator.ts
ethers js does not have a default provider for gnosis so we are providing a default endpoint
=> fix(core): Add default endpoint for gnosis

packages/core/src/initialization/make-index-api.ts
Setting this var to false on our infra enabled indexing.
I wrongly assumed that the value would be checked, but I think we should always check the value of an env var, rather than just the presence of it.
=> fix(core): check value of indexing env var

packages/core/src/pubsub/pubsub-message.ts
Apparently, we forgot to replace one of the relative imports with `@ceramicnetwork/metrics` import. The PR fixes that.
I hope it is the last occurrence of the relative imports.
CC @gvelez17
=> fix(core): Use package, not relative path to metrics

packages/cli/src/ceramic-cli-utils.ts, packages/core/src/ceramic.ts, packages/stream-model-handler/src/model-handler.ts, packages/stream-model-instance-handler/src/model-instance-document-handler.ts
Instead of just checking the presence of an environment variable for a conditional, we should check its value so that node operators can set environment variables to false when needed.
This is motivated by an issue we had where we accidentally enabled indexing on our nodes in an attempt to gate the release of the feature by setting the environment variable `CERAMIC_ENABLE_EXPERIMENTAL_INDEXING = 'false'`.
**I think using variables from process.env directly should be avoided.**  Instead, let's evaluate the variable in one place and use that result elsewhere in the code.
E.g.
```js
const indexingEnabled = envVarToBoolean(process.env.CERAMIC_ENABLE_EXPERIMENTAL_INDEXING)
```
However this PR is a quick fix before deciding where to put this utility function and refactoring existing uses of …
=> fix: evaluate string value of env vars as booleans

packages/core/src/pubsub/pubsub-ratelimit.ts
To declutter production log messages, moving the pubsub rate limiting warning message from `warning` to `verbose` since rate limiting doesn't have any negative impact on actual data retention or message socialization.
=> feat(core): moving rate limiting message from warning to verbose

packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon/handle-sigint-signal.ts, packages/core/src/__tests__/dispatcher-mock-ipfs.test.ts, packages/core/src/__tests__/dispatcher-real-ipfs.test.ts, packages/core/src/__tests__/shutdown-signal.test.ts, packages/core/src/ceramic.ts, packages/core/src/dispatcher.ts, packages/core/src/shutdown-signal.ts
AbortController.signal uses native Node.js `events`. It emits a warning to console, when number of listeners gets bigger than some predefined number. You can easily increase the number if you use vanilla EventEmitter. Unfortunately, an instance of EventEmitter is unavailable if you use AbortController and AbortSignal. So, the only option is to set the limit globally.
But, you can not reliably do that, as basically every IPFS call creates a listener. You just can not determine reliably the upper bound for that number. And even if you do that, you would interfere with all the EventEmitters.
So, instead, the PR uses rxjs-based entity to pass the shutdown signal inside Ceramic.
=> feat: Bypass maxEventListeners warning by using homegrown signalling

packages/core/src/anchor/ethereum/ethereum-anchor-validator.ts
This allows us to test version 1 and version 2 anchors in CAS by using different starting block numbers
=> chore(core): increase blocknumber that turns on smart contract anchor validation for ganache networks 

packages/cli/src/ceramic-daemon.ts, packages/common/src/index-api.ts, packages/core/src/indexing/__tests__/local-index-api.test.ts, packages/core/src/indexing/local-index-api.ts
It may happen that a stream is indexed, but it's not possible to retrieve it from the repository (e.g. because it wasn't pinned, was unpinned or perhaps other reasons). In such case, we don't want to (for now at least) an index query to throw an error, but we want to return nulls instead.
=> Allow empty states for indexed streams

packages/cli/src/daemon-config.ts, packages/core/src/indexing/__tests__/local-index-api.test.ts, packages/core/src/indexing/build-indexing.ts, packages/core/src/indexing/local-index-api.ts
This PR doesn't remove the `models` config key yet, just deprecates, adds TODOs to remove them it and a logger warning when they're present. It will be removed in a future PR.
1. Set `indexing.models` to `["kh4q0ozorrgaq2mezktnrmdwleo1d"]` in my local daemon config file
2. Started the daemon and got the new warning log:
```
☁  js-ceramic [CDB-1784-remove-models-from-config-file] CERAMIC_ENABLE_EXPERIMENTAL_COMPOSE_DB=true  node packages/cli/bin/ceramic.js daemon --network=inmemory
[2022-09-19T13:12:35.475Z] IMPORTANT: Starting Ceramic Daemon at version 2.7.0-rc.2 with config: 
{
"anchor": {},
"http-api": {
"cors-allowed-origins": [
".*"
]
},
"ipfs": {
"mode": "bundled"
},
"logger": { …
```
=> Cdb 1784 remove models from config file

packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon/instrument-requests.ts
This PR restores the instrument-requests.ts handler which enables counting of API requests in the ceramic node, 
and adds the handler into the chain
=> instrument request metrics

packages/core/src/indexing/database-index-api.ts, packages/core/src/indexing/postgres/__tests__/postgres-index-api.test.ts, packages/core/src/indexing/postgres/init-tables.ts, packages/core/src/indexing/postgres/migrations/1-create-model-table.ts, packages/core/src/indexing/postgres/migrations/cdb-schema-verification.ts, packages/core/src/indexing/postgres/postgres-index-api.ts, packages/core/src/indexing/sqlite/__tests__/sqlite-index-api.test.ts, packages/core/src/indexing/sqlite/init-tables.ts, packages/core/src/indexing/sqlite/migrations/1-create-model-table.ts, packages/core/src/indexing/sqlite/sqlite-index-api.ts
* made the `model` column unique in `ceramic_models` table
* started adding entries to `ceramic_models` table in `indexModels(...)`
* added `stopIndexingModels(...)` to `DatabaseIndexApi` and implemented it in postres and sqlite db apis
* **did not(!!!!)** implement deletion of model index tables on `stopIndexingModels(...)`
* update entries in `ceramic_models` table in `stopIndexingModels(...)`
* load the list of models to index in `init()` in `DatabaseIndexApi`
=> Start populating the `ceramic_models` table and add stopIndexingModels(...) to `DatabaseIndexApi`

packages/core/src/pubsub/__tests__/pubsub-ratelimit.test.ts
The source of the flakiness is not-really precise timer it seems. Our expectation is that `setTimeout(fn, N)` would trigger a function at `currentTime+N+ɛ`, `ɛ ≥ 0`. In the test, we expect functions to be called every second. Apparently, and obviously in retrospect, `ɛ` varies second to second. For second `N` `ɛ = 10`, while for the next second `N+1` `ɛ = 5`.  This means two invocations are `<1 second` apart, which triggers an error.
Here is how it looks for real. Every timestamp below is when a function is called. Notice the difference between start of the 3rd and the 2nd second is 999ms.
```
times [
2022-09-29T13:52:44.702Z,
2022-09-29T13:52:44.703Z,
2022-09-29T13:52:44.703Z,
2022-09-29T13:52:44.703Z,
2022-09-29T13:52:44.703Z,
2022-09-29T13:52:45.702Z, // <= start of the 2nd second …
```
=> test: Make pubsub-ratelimit test less flaky

packages/ipfs-daemon/package.json
Going to leave this PR unmerged until we have clearance to take `kubo v0.15.0` to Clay/Prod.
=> chore: use newer version of kubo in npm dependencies

packages/core/src/anchor/ethereum/__tests__/ethereum-anchor-validator.test.ts, packages/core/src/anchor/ethereum/ethereum-anchor-validator.ts
We use INFURA in EthereumAnchorValidator.
There we have three calls to a provider:
`provider.getNetwork` - in `init` function, definitely a one-time operation
`provider.getTransaction` - per anchor proof
`provider.getBlock` - per anchor proof, same as `getTransaction`.
Let's start with `getTransaction`. We use JsonRPCPRovider. `getTransaction` is inherited from `BaseProvider`. https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/base-provider.ts#L1849
The first thing it does is `getNetwork`. Then inside it calls `detectNetwork`, which is defined in JSONRPCProvider: https://github.com/ethers-io/ethers.js/blob/44cbc7fa4e199c1d6113ceec3c5162f53def5bb8/packages/providers/src.ts/base-provider.ts#L1148
https://github.com/ethers-io/ethers.js/blob/44cbc7fa4e199c1d6113ceec3c …
=> feat: Use StaticJsonRpcProvider in EthereumAnchorValidator

packages/common/src/ceramic-api.ts, packages/core/src/ceramic.ts, packages/http-client/src/ceramic-http-client.ts
for now I left the AdminApi interface around, but it might make sense to delete the interface entirely and just let LocalAdminApi and RemoteAdminApi exist as totally independent types.  Would love input here.
=> fix(core, http-client, common): Remove AdminApi from CeramicAPI since the implementations are different

packages/cli/package.json, packages/cli/src/__tests__/admin-api.test.ts, packages/cli/src/__tests__/make-ceramic-core.ts, packages/cli/src/__tests__/make-ceramic-daemon.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon-config.ts, packages/common/src/ceramic-api.ts, packages/core/src/ceramic.ts, packages/core/src/indexing/local-index-api.ts, packages/core/src/local-admin-api.ts, packages/http-client/src/__tests__/remote-admin-api.test.ts, packages/http-client/src/ceramic-http-client.ts, packages/http-client/src/remote-admin-api.ts, packages/stream-tests/src/__tests__/admin-api.test.ts
puts the `admin: AdminAPI` back into the common `CeramicApi` interface (effectively reverting https://github.com/ceramicnetwork/js-ceramic/commit/d83c739ef6e5679da485363db8bc477ec1d39540) and unifies the `LocalAdminApi` and `RemoteAdminApi` to have the same signatures by removing the DID arguments from both and taking the DID from the `CeramicClient` handle in the http-client implementation
=> feat(core,common,http-client): Standardize AdminAPI implementations to not take DID argument.

packages/core/src/state-management/__tests__/repository.test.ts, packages/stream-model-instance-handler/package.json, packages/stream-model-instance-handler/src/__tests__/model-instance-document-handler.test.ts, packages/stream-model-instance-handler/src/__tests__/schema-utils.test.ts, packages/stream-model-instance-handler/src/model-instance-document-handler.ts, packages/stream-model-instance-handler/src/schema-utils.ts, packages/stream-tile-handler/package.json, packages/stream-tile-handler/src/schema-utils.ts
Apparently, AJV instance is just a huge source of memory leaks when applied to on-demand schema validation. Better put AJV instances in LRU cache to isolate garbage.
=> fix: Wrap AJV instances in LRU cache

packages/cli/src/ceramic-daemon.ts
Don't return UNAUTHORIZED from admin api's getIndexedModels, if it's not authorization that fails. Return a higher-level error in that case instead.
=> fix(cli): Don't return UNAUTHORIZED for non-auth failure of AdminAPI getIndexedModels()

packages/cli/src/ceramic-daemon.ts, packages/cli/src/s3-state-store.ts, packages/core/src/ceramic.ts, packages/core/src/state-management/repository.ts, packages/core/src/store/__tests__/level-state-store.test.ts, packages/core/src/store/__tests__/pin-store.test.ts, packages/core/src/store/__tests__/state-store-integration.test.ts, packages/core/src/store/level-state-store.ts, packages/core/src/store/pin-store-factory.ts, packages/core/src/store/pin-store.ts, packages/core/src/store/state-store.ts
A small cleanup to prepare for https://linear.app/3boxlabs/issue/CDB-1837/allow-network=mainnet, which will require querying the state store during initialization to detect if there is existing data under an `elp` directory or not
=> chore(core): Make pinStore initialization async

.changeset/orange-files-listen.md, packages/streamid/src/__tests__/__snapshots__/stream-id.test.ts.snap, packages/streamid/src/__tests__/stream-id.test.ts, packages/streamid/src/commit-id.ts, packages/streamid/src/reading-bytes.ts, packages/streamid/src/stream-id.ts, packages/streamid/src/stream-ref-parsing.ts, packages/streamid/src/stream-ref.ts, packages/streamid/src/try-catch.util.ts, packages/streamid/tsconfig.json
- Throw/no-throw functions: throw by default, `NoThrow` function wraps a throwing one in a try-catch.
- `StreamRef.fromBytes` and `StreamRef.fromString` along with respective `StreamID` and `CommitID` parsing functions reuse same parsing logic. Control flow does not rely on errors. @stbrody Your precious debugging should be all right.
It is now slightly faster: https://github.com/ceramicnetwork/js-ceramic/blob/feature/cdb-1945-streamid-bench/packages/streamid/src/old-new.bench.ts
One caveat. For some reason we allowed parsing StreamID from `/ceramic/<stream-id>?commit=<commit-id>` string. This is a drastic inconsistency with other formats, where presence of CommitID information leads to an error. I changed parsing here, so that we throw an error if commit is present in a string formatted …
=> chore(streamid): Strict TS config

packages/core/src/__tests__/__snapshots__/caip10-link.test.ts.snap, packages/stream-caip10-link-handler/package.json, packages/stream-caip10-link-handler/src/__tests__/__snapshots__/caip10-link-handler.test.ts.snap, packages/stream-caip10-link-handler/src/__tests__/caip10-link-handler.test.ts, packages/stream-caip10-link-handler/src/caip10-link-handler.ts, packages/stream-handler-common/.eslintrc.json, packages/stream-handler-common/.gitignore, packages/stream-handler-common/LICENSE-APACHE, packages/stream-handler-common/LICENSE-MIT, packages/stream-handler-common/README.md, packages/stream-handler-common/babel.config.json, packages/stream-handler-common/jest.config.json, packages/stream-handler-common/package.json, packages/stream-handler-common/src/anchor-commit-utils.ts, packages/stream-handler-common/src/index.ts, packages/stream-handler-common/tsconfig.json, packages/stream-model-handler/package.json, packages/stream-model-handler/src/model-handler.ts, packages/stream-model-instance-handler/package.json, packages/stream-model-instance-handler/src/model-instance-document-handler.ts, packages/stream-tile-handler/package.json, packages/stream-tile-handler/src/tile-document-handler.ts
Also introduce @ceramicnetwork/stream-handler-common package to house code shared between the various streamtype handlers.
=> chore: Consolidate anchor commit application logic

.changeset/tidy-eagles-try.md, packages/common/src/context.ts, packages/common/src/index.ts, packages/common/src/non-empty-array.ts, packages/common/src/stream.ts, packages/stream-caip10-link-handler/src/caip10-link-handler.ts, packages/stream-model-handler/src/model-handler.ts, packages/stream-tile-handler/package.json, packages/stream-tile-handler/src/__tests__/tile-document-handler.test.ts, packages/stream-tile-handler/src/schema-utils.ts, packages/stream-tile-handler/src/tile-document-handler.ts, packages/stream-tile-handler/tsconfig.json, packages/stream-tile/package.json, packages/stream-tile/src/tile-document.ts, packages/stream-tile/tsconfig.json
Note: `context.api` is mandatory now.
One more change: `StreamState#log` is `NonEmptyArray` now, which on type level gives assurance that `log[0]` is present. No run-time guarantees though, but it seems fine for now.
=> chore(stream-tile): Make TS compiler strict

packages/core/src/indexing/postgres/__tests__/postgres-index-api.test.ts, packages/core/src/indexing/postgres/init-tables.ts, packages/core/src/indexing/sqlite/__tests__/sqlite-index-api.test.ts, packages/core/src/indexing/sqlite/init-tables.ts, packages/core/src/indexing/sqlite/sqlite-index-api.ts
Paralellised the table operations using `await Promise.all(...)`, because I didn't find methods in `Knex` to e.g. create several tables at once (which I'd expect to be done in parallel, if possible).
- MID table creation on current `develop` branch: 17.462 seconds
- table verification on current `develop` branch: 8 milliseconds
- MID table creation on this PR's branch: 16.533 seconds
- table verification on this PR's branch: 8 milliseconds
- MID table creation on current `develop` branch: 390 milliseconds
- table verification on current `develop` branch: 259 milliseconds
- MID table creation on this PR's branch: 170 milliseconds
- table verification on this PR's branch: 49 milliseconds
I ran all …
=> feat: Parallelise table operations in database apis

packages/core/src/__tests__/local-pin-api.test.ts, packages/core/src/local-pin-api.ts
Call `this.repository.pin` only if `force` is true. Otherwise it is a fancy no-op.
=> feat: Provisionary dedupe of pinning

packages/common/src/utils/stream-utils.ts, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/state-manager.test.ts, packages/core/src/conflict-resolution.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/state-manager.ts, packages/stream-model-handler/src/__tests__/__snapshots__/model-handler.test.ts.snap, packages/stream-model-handler/src/__tests__/model-handler.test.ts, packages/stream-model-instance-handler/src/__tests__/__snapshots__/model-instance-document-handler.test.ts.snap, packages/stream-model-instance-handler/src/__tests__/model-instance-document-handler.test.ts, packages/stream-tests/src/__tests__/capability.test.ts, packages/stream-tile-handler/src/__tests__/__snapshots__/tile-document-handler.test.ts.snap, packages/stream-tile-handler/src/__tests__/tile-document-handler.test.ts
This has the nice bonus of removing the need for the "lone genesis" check since we now check for expired CACAOs every time we load or update a stream anyway, which lets us simplify the code a bit
=> feat(core): Throw when loading or updating a stream with expired CACAOs in the log

packages/common/src/utils/http-utils.ts
Cookies are remembered by browser.
Cookies do not work if a request is originated from Node.js
It would require a wrapper around one of the "native" fetch implementations. Due to sheer complexity of handling that in a cross-platform way, I better slightly postpone handling of cookies in Node.js. Expectation anyway is absolute most of the requests come from a browser.
So, treat this PR as a starter before moving to better more future-proof fetch based on undici.
=> chore: Handle cookies in browser

packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/stream-tests/src/__tests__/model.test.ts
Seems that the reason that the tests interfered with each other had to do with the fact that the InMemoryAnchorService was getting multiple anchor requests for the same commit (the genesis commit for the Model).  When it picked which request to anchor, it would randomly choose one of the two identical requests to anchor, but mark the other as failed due to conflict resolution, which would send an event on the Observable polling the anchor service saying the request was failed.
I still don't totally understand then why the test would *hang* rather than erroring that the anchoring had failed, but I think at this point that's enough time spent digging on this.
=> Fix interference between tests

packages/core/src/document.ts
In response to Sergey's recent email proposing that we've made it *too* easy with all the recent comments.  I feel pretty fine about removing the comments from the highlighted block related to picking which log to keep.  I have no reservations about removing the comments there as proposed in this PR.  If there's a belief that that's still not enough and we should remove more comments from the earlier part of the function, we might want to have a call to discuss that in more detail, as that seems to me like a change that would come with more tradeoffs.
=> code reading interview: rm comments from highlighted block

packages/cli/src/ceramic-daemon.ts
Fix a forgotten flag that resulted in an annoying issue.
To use sticky sessions in future, we have enabled `credentials: include` previously. 
From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials):
> The Access-Control-Allow-Credentials response header tells browsers whether to expose the response to the frontend JavaScript code when the request's credentials mode ([Request.credentials](https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials)) is include.
I forgot (and did not know, to be honest) to add a server counterpart `credentials: true`.
=> fix: Provide Access-Control-Allow-Credentials header

packages/common/src/stream.ts, packages/core/src/__tests__/conflict-resolution.test.ts, packages/core/src/ceramic.ts, packages/core/src/conflict-resolution.ts, packages/core/src/utils.ts, packages/stream-handler-common/src/anchor-commit-utils.ts, packages/stream-tests/src/__tests__/capability.test.ts
I went with this approach, where we validate the anchor commits right after fetching the log, but before applying them, and remember any validation errors so they can be thrown later during commit application.
This was the shortest path to making the changes needed for Graceful Block Reorgs while preserving existing functionality and not making major changes to how signatures are verified or how CACAO timeouts are handled.
That means this is a temporary fix.  We will hit against this problem again when we move log syncing to happen in a single pass where we go from oldest commit to newest commit, without the preliminary pass that first loads commits from newer to older.  We will need to make sure the scope for StreamSync includes time to think about how CACAO timeouts get validated and …
=> feat(core): Validate anchors and extract timestamp information before commit application

packages/cli/src/s3-store.ts, types/s3leveldown/index.d.ts
Removed the @ts-ignore and instead included empty interface to make S3LevelDOWN conform to AbstractLevelDown
=> Explicitly hide S3LevelDOWN incompatibility with abstract level down

packages/core/src/state-management/__tests__/anchor-resuming-service.test.ts
This test had been failing on CircleCi occasionally. I wasn't able to reproduce the failure locally, so I increased the timeout a bit and made the test wait for all anchor status updates before checking them. Let's see, if this make CircleCI stop failing.
=> Wait for all relevant anchor status updates in the anchor resume test

packages/stream-model-handler/src/__tests__/model-handler.test.ts, packages/stream-model-instance-handler/src/__tests__/model-instance-document-handler.test.ts, packages/stream-model-instance/src/model-instance-document.ts, packages/stream-model/src/model.ts, packages/stream-tests/src/__tests__/basic-indexing.test.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts, packages/stream-tests/src/__tests__/model.test.ts
This PR adds the `sep` key to the genesis header as specified in CIP-120. While not used yet it will allow the future upgrade to support CIP-120 much less painful.
Note: This is a breaking change to deterministic MID documents.
=> feat: Add sep key to model stream types

packages/cli/src/s3-store.ts
There was a typo in the implementation of `S3Store.exists(...)` which caused crashes when checking, if a running state should be resumed for a `StreamID`.
=> Fixed the implementation of S3Store.exists(...)

packages/http-client/src/__tests__/remote-admin-api.test.ts, packages/http-client/src/remote-admin-api.ts
See #CDB-2133 - several developers have run into this confusing message if they do not set DID_PRIVATE_KEY.  In order to allow composedb to return a helpful message, have the admin api return a specific error class.
```right now running composedb composite:deploy errors with Cannot read properties of undefined (reading 'createJWS') if DID_PRIVATE_KEY is undefined.  We should have a more useful error message instead.```
- [ x] added unit tests to cover the new code
- [x ] made local changes and verified with composedb that the desired behavior occurs
Please list relevant documentation …
=> Throw specific error on missing DID so composedb can be helpful - #CDB-2133

packages/core/src/indexing/postgres/postgres-index-api.ts, packages/core/src/indexing/sqlite/sqlite-index-api.ts
Indexing streams to DB works well for new streams but not for the updates.
It only updates `last_anchored_at` and `updated_at` fields for existing streams.
This commit simply adds `stream_content` field for both SQLite and PostgreSQL indexers.
=> Update stream content in DB on stream updates

packages/common/package.json, packages/common/src/utils/signature_utils.ts
Adds tezos verifier from - https://github.com/ceramicnetwork/js-did/tree/main/packages/pkh-tezos
Allows support for tezos cacao/did-session
=> feat(common): add tezos cacao (did-session) support

packages/cli/src/index.ts
This is critical to fix the integration tests, as they cannot run the newest version of Ceramic currently, as they cannot build Ceramic with the S3 state store as the S3 store implementation moved and stopped being exported in https://github.com/ceramicnetwork/js-ceramic/commit/2754643e7503a9f5103cc5af14d1614a3ee07245#diff-2fb448d11702324cc59d657d5945d59cd325540eb87b71f2e66a5bc01ada834c
=> fix(cli): Export S3Store type

packages/common/src/streamopts.ts, packages/core/src/ceramic.ts, packages/core/src/state-management/repository.ts, packages/stream-tests/src/__tests__/capability.test.ts
This may be useful for apps that are encountering CACAO errors and want those CACAO errors to be handled by resetting the stream state back to the last valid commit (even at the cost of throwing away writes), but don't want to have to manually catch CACAO errors and trigger a reload with the SYNC_ALWAYS flag.  If they use this new flag for all their stream loads instead, then for healthy streams there will be no extra overhead, but when there's an error loading the stream we will get the behavior of resyncing the full stream log to try to repair it.
This would also be useful to use on our CAS, as our CAS Ceramic node now has streams in its state store that have expired CACAOs and so those streams will never be able to be successfully anchored again until the state in the CAS Ceramic node …
=> feat(core): Add SyncOption to resync stream on error

packages/core/src/dispatcher.ts, packages/core/src/pubsub/__tests__/incoming-channel.test.ts, packages/core/src/pubsub/__tests__/pubsub-keepalive.test.ts, packages/core/src/pubsub/__tests__/pubsub-ratelimit.test.ts, packages/core/src/pubsub/__tests__/pubsub.test.ts, packages/core/src/pubsub/incoming-channel.ts, packages/core/src/pubsub/pubsub.ts
Emit a log warning if we receive no messages from IPFS within 5 minutes, or if we receive no internal messages (messages intended for the node). 4 additional tests added to verify behavior
=> feat(core) CDB-1952: Warn if no pubsub messages

packages/cli/src/__tests__/make-ceramic-daemon.ts, packages/cli/src/ceramic-cli-utils.ts, packages/core/src/indexing/database-index-api.ts, packages/core/src/indexing/migrations/1-create-model-table.ts, packages/core/src/indexing/migrations/cdb-schema-verification.ts, packages/core/src/indexing/tables-manager.ts
Add Historical Data Sync config table & populate with default values depending on network chosen.
**ATTENTION**: This is a breaking change to previous versions as it changes the table structure of `ceramic_config` & `ceramic_models`.
- updated `ceramic_config` table structure & populate with default values during startup;
- extended `ceramic_models` with historical sync flag;
- remove 'allow-queries-before-historical-sync' from config file creation;
- change default value for updated_by to '0' before final feature implemented;
- changed config table and updated schema verification;
=> feat (core): extend config table with addt. indexing options

packages/3id-did-resolver/README.md
README previously included some text that referred to the did-ethr resolver
Found this because the Veramo team added a resolver for did:3 to our DID Driver, so we can add did:3 support to the Universal Resolver. If anyone from Ceramic wants to review our work, that'd be great
https://github.com/uport-project/uport-did-driver/pull/103
=> chore: remove errata in 3id-did-resolver README

packages/core/src/initialization/make-index-api.ts
We must not release this on prod until after the hard fork
=> feat(core): Enable running ComposeDB on mainnet

packages/core/src/anchor/ethereum/__tests__/ethereum-anchor-validator.test.ts, packages/core/src/anchor/ethereum/ethereum-anchor-validator.ts
The code will enforce that anchors go to the proper smart contract address for all anchors after the BLOCK_THRESHOLD.  We will set the blockThreshold to whatever is the first block after we update the CAS to use the actual correct smart contract address
=> fix(core): Update expected smart contract address

packages/anchor-listener/src/__tests__/listener.test.ts, packages/anchor-listener/src/__tests__/loader.test.ts, packages/anchor-listener/src/__tests__/test-utils.ts, packages/anchor-listener/src/__tests__/utils.test.ts, packages/anchor-listener/src/listener.ts, packages/anchor-listener/src/loader.ts, packages/core/src/sync/__tests__/ceramic-sync.test.ts, packages/core/src/sync/workers/__tests__/sync.test.ts, packages/core/src/sync/workers/sync.ts
Get logs in the anchor-listener get logs for a range now (set to 100 blocks as default)
=> fix(anchor-listener, core): batch get logs

packages/cli/src/__tests__/admin-api.test.ts, packages/cli/src/ceramic-daemon.ts, packages/common/src/ceramic-api.ts, packages/core/src/local-admin-api.ts, packages/http-client/src/__tests__/remote-admin-api.test.ts, packages/http-client/src/remote-admin-api.ts, packages/stream-tests/src/__tests__/admin-api.test.ts
No real functionality yet (beyond the admin api authorization), just returns an empty response body.
=> feat(cli,http-client): Add node status admin API endpoint skeleton

packages/core/src/indexing/__tests__/database-index-api.test.ts, packages/core/src/indexing/migrations/1-create-model-table.ts, packages/core/src/indexing/tables-manager.ts
Add checks when a node starts up to verify that indices are present.
Additionally fix code that was using too long of a name, switching from tableName to indexName.
=> feat(core) CDB-1655: Verify Indices

packages/ipfs-daemon/package.json
18 fails to start in bundled mode
=> fix: downgrade go-ipfs to 15

packages/core/src/indexing/migrations/1-create-model-table.ts
Allow `elp` as option for network config to comply with internal infrastructure settings.
recommended for internal use only. No need for docs update
=> fix: allow elp as composedb network config

packages/core/src/initialization/make-index-api.ts
Historical data sync is not supported with SQLite. Added addt. check to inform dev to switch.
=> fix: added disallow HDS with SQLite check

packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-cli-utils.ts, packages/core/src/indexing/database-index-api.ts, packages/core/src/indexing/migrations/1-create-model-table.ts, packages/core/src/indexing/tables-manager.ts, packages/core/src/initialization/make-index-api.ts
Also update all places where we say "Compose DB" to say "ComposeDB" to match our branding and marketing material.
=> chore: Update error message when starting on mainet without postgres to mention disabling ComposeDB

packages/ipfs-daemon/src/create-ipfs.ts
Ran IPFS in bundled mode and checked config output:
```
{
.
.
.
"Peering": {
"Peers": [
{
"Addrs": [
"/dns4/go-ipfs-ceramic-private-mainnet-external.3boxlabs.com/tcp/4011/ws/p2p/QmXALVsXZwPWTUbsT8G6VVzzgTJaAWRUD7FWL5f7d5ubAL"
],
"ID": "QmXALVsXZwPWTUbsT8G6VVzzgTJaAWRUD7FWL5f7d5ubAL"
},
{
"Addrs": [
"/dns4/go-ipfs-ceramic-private-cas-mainnet-external.3boxlabs.com/tcp/4011/ws/p2p/QmUvEKXuorR7YksrVgA7yKGbfjWHuCRisw2cH9iqRVM9P8"
],
"ID": "QmUvEKXuorR7YksrVgA7yKGbfjWHuCRisw2cH9iqRVM9P8"
},
{
"Addrs": [
"/dns4/go-ipfs-ceramic-elp-1-1-external.3boxlabs.com/tcp/4011/ws/p2p/QmUiF8Au7wjhAF9BYYMNQRW5KhY7o8fq4RUozzkWvHXQrZ"
],
"ID": "QmUiF8Au7wjhAF9BYYMNQRW5KhY7o8fq4RUozzkWvHXQrZ"
},
{
"Addrs": [
"/dns4/go-ipfs-ceramic-elp-1-2-external.3boxlabs.com/tcp/4011/ws/p2p/QmRNw9ZimjSwujzS3euqSYxDW9EHDU5LB3NbL …
```
=> feat: add pubsub cache ttl and bootstrap peers to bundled kubo config

packages/cli/src/__tests__/make-ceramic-core.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/daemon-config.ts, packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/__tests__/create-ceramic.ts, packages/core/src/ceramic.ts, packages/core/src/indexing/__tests__/build-indexing.test.ts, packages/core/src/indexing/build-indexing.ts, packages/core/src/indexing/migrations/1-create-model-table.ts, packages/core/src/initialization/make-index-api.ts, packages/core/src/sync/__tests__/ceramic-sync.test.ts, packages/stream-tests/src/__tests__/admin-api.test.ts, packages/stream-tests/src/__tests__/basic-indexing.test.ts, packages/stream-tests/src/__tests__/cross-node-indexing.test.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts, packages/stream-tests/src/create-ceramic.ts
Moves HDS configuration flag from experimental env variable (`CERAMIC_ENABLE_EXPERIMENTAL_SYNC`) to be set in the config file. This populates both `allow-queries-before-historical-sync` & `run-historical-sync-worker` by network specific default values.
This PR has default options `3` implemented as outlined in the product discussion: https://www.notion.so/threebox/HDS-Default-Behavior-f5314ebbaba54e1d86ad3af613056f2c
=> feat(cli, core): add sync worker flag to config file with default values

packages/core/src/indexing/local-index-api.ts
=> chore: Slightly more relaxed check for absence (#2763)Co-authored-by: Spencer T Brody <spencer+github@3box.io>

packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/state-management/repository.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts
Similar reasoning to https://github.com/ceramicnetwork/js-ceramic/pull/2762 
Currently causes error in composedb cli /etc, those could be easily fixed, but may also cause glaze/selfid and all related dependencies to also throw errors which used these options (would have to double check these, it looks like they may only be used on create, but this would still likely be the safest short term option) 
Changes the thrown error to console.warn(if we use that all) 
~~Just commented out lines in tests, but can remove or cleanup in another way.~~
=> fix(core): warn instead of throw on pin opts for stream crud (#2764

packages/cli/src/__tests__/admin-api.test.ts, packages/cli/src/ceramic-daemon.ts
Needs to be valid json response, since http clients uses fethJSON and json parse response - https://github.com/ceramicnetwork/js-ceramic/blob/develop/packages/common/src/utils/http-utils.ts#LL49C6-L49C6
otherwise json parse error will be returned 
will try to add a test now, should have the first time, pushing up now for visibility
=> fix(cli): legacy pin, must return json for 200 (#2769

packages/stream-model/babel.config.json, packages/stream-model/jest.config.json, packages/stream-model/package.json, packages/stream-model/src/__tests__/__snapshots__/model.test.ts.snap, packages/stream-model/src/__tests__/model.test.ts, packages/stream-model/src/model.ts
It is deprecated long time ago. Adds extra code and extra warnings.
=> chore: Remove multihashes from js-ceramic

packages/cli/package.json, packages/core/package.json
The js-ceramic metrics other than the request instrumentation had stopped working, including the metric on ipfs timeouts
The reason was that I had let the versions of the observability package imported get out of sync, which meant that it did not act as a singleton, so the copy imported in the `core` package was not the same one that had been initialized in the daemon.  This updates the observability package to the same latest version in both packages.
- [x ] Tested locally in debugger, to ensure that the core metrics work correctly now
- [ x] Unit tests
Please list relevant …
=> the versions of the observability package must match

packages/core/src/indexing/build-indexing.ts
Community alerted us that with Knex's default value of 2 a stale Postgres connection can lead to connection issues before its re-established. Both in a Knex Github issues (https://github.com/knex/knex/issues/3523) & on the Knex docs (https://knexjs.org/guide/#pool) it is recommended to set the min pool size to 0 to avoid this exact issue and allow stale connections to be terminated.
=> fix (core): set min connection pool size to 0

packages/core/src/anchor/ethereum/__tests__/ethereum-anchor-validator.test.ts, packages/core/src/anchor/ethereum/ethereum-anchor-validator.ts
Methodology for selecting block numbers:
- go to etherscan for the appropriate chain (eth mainnet, goerli, and gnosis).
- search for our anchor smart contract address: [0x231055A0852D67C7107Ad0d0DFeab60278fE6AdC](https://github.com/ceramicnetwork/js-ceramic/blob/94b51b6e11279a9e9daf007bcc3c9f00a283e6f1/packages/core/src/anchor/ethereum/ethereum-anchor-validator.ts#L63)
- Take the block number of the very first `anchorDagCbor` transaction (which is always the third overall transaction on the address - after contract creation and ownership transfer)
=> feat(core): finalize block threshold for switch to smart contract anchoring

packages/streamid/package.json, packages/streamid/src/__tests__/event-id.test.ts, packages/streamid/src/event-id.ts
EventIDs for recon, ref corresponding rust pr - https://github.com/3box/rust-ceramic/pull/53/files#diff-2924eb293981196ffa6cd00553cc52fe96f0718b46b967ea3f2e436504ff0401
Placed in streamids packages, but could make sense to move elsewhere, needed to communicate later with rust ceramic/recon
=> feat: add eventIDs

packages/common/src/index-api.ts
Needed by ComposeDB to create the new inputs and add them to APIs calls.
=> feat(common): Update query type to support new filters and order parameters

.github/workflows/npm-publish.yml, .github/workflows/reusable-release.yml, package.json
Lets say the current version of the ceramic core package is `2.35.0`.  When we do an RC, we want to bump the minor version (leaving the patch version available for potential hotfix releases) and go to `2.36.0-rc.0`.  That is what our current `rc` workflow does.  Then when we do the main release it goes to `2.36.0`.  All good so far.  The problem comes if we want to do a second RC before doing a main release.  With the current workflow, the second RC will get version `2.37.0-rc.0`.  This wastes a minor version and loses information about the fact that the two RCs are linked and the second is effectively replacing the first as the candidate to become the next full release.  Instead, it would be better for the second RC to get the version `2.36.0-rc.1`.  This PR gives us a workflow to do …
=> add workflow for publishing follow-up RCs that bump the RC version

packages/cli/src/__tests__/admin-api.test.ts, packages/cli/src/ceramic-daemon.ts, packages/common/src/ceramic-api.ts, packages/core/src/local-admin-api.ts, packages/http-client/src/__tests__/remote-admin-api.test.ts, packages/http-client/src/remote-admin-api.ts, packages/stream-tests/src/__tests__/admin-api.test.ts
Adjusts AdminAPI to support new functionality around adding indices to models. New structure ModelData is added, and new methods are start, stop, and get indices related to ModelData are added.
This splits out part of the changes in https://github.com/ceramicnetwork/js-ceramic/pull/2829
=> feat: CDB-2493 Adjust API to support model index changes

package.json
Fixes PLAT-1537
Develop branch build failures due to unpinned dependencies.
Ran `npm test` locally
=> Override opentelemetry pacakge versions to 1.8.0

packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon-config.ts
Adds support for Prometheus /metrics export. This is beneficial as it allows pull based metrics collection in addition to the existing OTLP pushed based collection.
Depends on https://github.com/ceramicnetwork/observability/pull/7 to merge and be published first.
Manually verified that the `/metrics` endpoint is exposed on the specified port.
https://github.com/ceramicnetwork/observability/pull/7
=> feat: add config for prometheus exporter

packages/blockchain-utils-linking/package.json, packages/blockchain-utils-validation/src/blockchains/__tests__/eosio.test.ts, packages/common/package.json, packages/core/package.json, packages/stream-model-handler/package.json, packages/stream-model-instance-handler/package.json, packages/stream-tests/package.json, packages/stream-tests/src/__tests__/caip10/eos.test.ts, packages/stream-tile-handler/package.json
It fails due to 3rd party endpoint having an expired SSL certificate.
=> test(blockchain-utils-validation): Disable eos test

packages/core/src/indexing/__tests__/database-index-api.test.ts, packages/core/src/indexing/database-index-api.ts, packages/core/src/indexing/local-index-api.ts, packages/core/src/indexing/migrations/1-create-model-table.ts, packages/core/src/indexing/tables-manager.ts
No real functionality changes, but cleans up and simplifies some of the logic, reduces the number of reads/writes to the database, and expands test coverage a bit.
=> Cleanups to indexing initialization and fieldIndex tracking

packages/core/src/anchor/ethereum/__tests__/ethereum-anchor-service.retry-failure.test.ts, packages/core/src/anchor/ethereum/ethereum-anchor-service.ts
Handle fetch errors by retrying when polling for an anchor.
There is a programmatic test. Also, tested manually:
1. create a stream, wait till the initial request to CAS passes.
2. Turn off Wi-Fi. This results in errors on the log (as expected).
3. Turn on Wi-Fi back. Polling continues.
=> fix: Do not stop polling for anchor result on a network error

packages/core/src/indexing/__tests__/query-filter-converter.test.ts, packages/core/src/indexing/query-filter-converter.ts, packages/core/src/indexing/query-filter-parser.ts, packages/stream-tests/src/__tests__/basic-indexing.test.ts
Fix issues with float casting and truncation in filters by using numeric types. Clean up and reuse logic for type determinations.
=> bug: CDB-2632 Better handle number query types

packages/core/src/anchor/ethereum/ethereum-anchor-service.ts, packages/core/src/ceramic.ts
Adds an env var `CERAMIC_DISABLE_POLLING_RETRIES` which if set to true reverts the node's behavior to be what it was before https://github.com/ceramicnetwork/js-ceramic/commit/07ff4e5b0558fd3ae6069c2fe2bdff5c6de69306#diff-7920408ff457031025a51c6c64241f297dc91febb1a810e724475548c154c781.
This is not a good fix and should be reverted before we do the next release, but if we can have gitcoin run with this flag enabled it could help us confirm whether or not the polling fix is what caused the recent node lockup
=> Temporarily allow disabling anchor polling retry logic

packages/http-client/src/ceramic-http-client.ts, packages/http-client/src/dummy-pin-api.ts
Do `console.warn` with a message `You use a deprecated ceramic.pin.${operation} API. Please, reconsider your choices`
Suggestions for a better message are welcome.
=> fix(http-client): Add a dummy pin api to not break old callers

packages/common/src/anchor-service.ts, packages/common/src/ceramic-api.ts, packages/common/src/streamopts.ts, packages/core/src/__tests__/state-manager.test.ts, packages/core/src/anchor/ethereum/__tests__/authenticated-anchor-service.test.ts, packages/core/src/anchor/ethereum/__tests__/ethereum-anchor-service.retry-failure.test.ts, packages/core/src/anchor/ethereum/__tests__/ethereum-did-auth-anchor-service.retry-failure.test.ts, packages/core/src/anchor/ethereum/ethereum-anchor-service.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/core/src/ceramic.ts, packages/core/src/state-management/state-manager.ts, packages/http-client/src/ceramic-http-client.ts
For now the flag is still false by default until we've tested it further, but the plan is to make it true by default in a later release.
This is also still missing the behavior where if the anchor fails the stream state is left unmodified as if the write never happened.  That requires some refactoring of the state manager and repository and will come in a future PR (test coverage will also come at that time as that will change behavior quite a bit).  But I wanted to get this in place first so we can test the latency implications.
=> feat: Add option to wait until anchor requests are durably created on the CAS

packages/core/src/indexing/__tests__/query-filter-converter.test.ts, packages/core/src/indexing/__tests__/query-filter-parser.test.ts, packages/core/src/indexing/query-filter-converter.ts, packages/core/src/indexing/query-filter-parser.ts, packages/stream-tests/src/__tests__/basic-indexing.test.ts
Added a bunch of tests
not(a & b)  and not a || b) fixed 
multiple keys/values with where filters
changed the approach if you looked at this branch before
=> feat(core, stream-tests): negated ors/ands and multiple keys/values with where filters

packages/core/src/__tests__/caip10-link.test.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts
We do not use it anywhere, and it does not conform to what real CAS does.
=> chore: drop signature verification for in-memory-anchor-service

packages/core/src/ceramic.ts, packages/core/src/state-management/repository.ts, packages/core/src/stream-loading/apply-tip-helper.ts, packages/core/src/stream-loading/stream-loader.ts, packages/core/src/stream-loading/stream-updater.ts
Only the `StreamLoader` and `StreamUpdater` should be used by the `Repository`, all the components that make them up should be considered private implementation details (this will be enforced in CDB-2749).  The public methods of `StreamLoader` and `StreamUpdater` are the API presented to the `Repository` for handling all Stream operations.  In turn, nothing outside of the Repository should access the `StreamLoader` or `StreamUpdater` - the `Repository` should be the interface to all Stream operations performed by any other part of the codebase.  The Repository will be responsible for handling concurrency control (the loading and execution queues) as well as pinning, indexing, publishing tips to pubsub, etc.
=> feat: Add StreamUpdater to handle applying incoming commits

README.md
Updating the info based on the [ADOPT-1327](https://linear.app/3boxlabs/issue/ADOPT-1327/the-docs-pointed-to-from-the-repo-still-refer-to-glaze) and a few additional observations of extremely outdated info displayed here, e.g.:
- outdated links for the documentation
- latest project update being pre-June 2022
- announcing the Clay launch when we already are giving access to the mainnet
=> [ADOPT-1327] update the info on README

packages/core/src/__tests__/ceramic-query-response.test.ts, packages/core/src/__tests__/state-manager.test.ts
The implementation of how streams get synced during loadStream is about to change a lot, so these tests as-written in `state-manager.test.ts` won't work anymore.  They're testing functionality we want to preserve though, so I want to make sure we don't lose that test coverage, so I re-wrote them to happen at a higher level.
=> chore: Rewrite tests of how sync waits for responses

packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/core/src/anchor/memory/in-memory-anchor-validator.ts, packages/core/src/stream-loading/__tests__/stream-loader.test.ts
...due to a difference for what `init` expects on the inmemory anchor service and the inmemory validator.
Previously `InMemoryAnchorService` implemented `AnchorValidator` interface. The PR extracts `InMemoryAnchorValidator` class to free `InMemoryAnchorService` from validator responsibility, and make unconvoluted `init`.
Positive side-effect: InMemoryAnchorService is more inline with EthereumAnchorService.
That's part of off-memory anchoring PR unbundling.
=> chore: Extract inmemory validator

packages/core/src/anchor/anchor-request-car-builder.ts, packages/core/src/ceramic.ts, packages/core/src/state-management/__tests__/state-manager.test.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/state-manager.ts
Part of off-memory anchoring.
Move `StateManager. _buildAnchorRequestCARFile` to a class. This thing is needed in more than one place, and it is quite inconvenient to go through the hoops to call StateManager. Also, this functionality is not really a part of StateManager.
=> chore: AnchorRequestCarBuilder

packages/core/src/__tests__/create-dispatcher.ts, packages/core/src/ceramic.ts, packages/core/src/store/__tests__/level-anchor-request-store.test.ts, packages/core/src/store/__tests__/level-state-store.test.ts, packages/core/src/store/__tests__/level-store.test.ts, packages/core/src/store/__tests__/state-store-integration.test.ts, packages/core/src/store/level-db-store.ts
Trying to get more information about what's happening in this flaky test failure: https://app.circleci.com/pipelines/github/ceramicnetwork/js-ceramic/11815/workflows/bb4e8a7d-0df8-42b7-a88a-9c1500ed8570/jobs/15545
=> chore: Add more context to errors from leveldb

packages/core/src/ceramic.ts, packages/core/src/local-admin-api.ts, packages/stream-tests/src/__tests__/history-sync.test.ts
A minor follow-up to https://github.com/ceramicnetwork/js-ceramic/pull/2881
Also adds a few log messages
=> fix: Fix calculation on number of eth blocks in 24 hours

packages/ipfs-topology/src/ipfs-topology.ts
Switch the dev-unstable peerlist to the new TCP multiaddrs of the QA IPFS nodes (including the new rust-ceramic node).
=> fix(ipfs-topology): update dev-unstable peerlist

packages/common/src/networks.ts, packages/core/src/initialization/__tests__/anchoring.test.ts, packages/core/src/initialization/anchoring.ts, packages/core/src/initialization/network-options.ts, packages/core/src/store/__tests__/level-anchor-request-store.test.ts, packages/core/src/store/__tests__/level-state-store.test.ts, packages/core/src/store/level-db-store.ts, packages/core/src/store/stream-state-store.ts, packages/indexing/src/migrations/1-create-model-table.ts, packages/ipfs-topology/src/ipfs-topology.ts
Note that mainnet used "elp" as the default location for the stores. I'm keeping that for mainnet as we have never used "mainnet" as the default location.
=> feat(common, core, indexing, ipfs-toplogy): Remove ELP network

packages/core/src/store/level-db-store.ts
This logging was added recently in https://github.com/ceramicnetwork/js-ceramic/commit/bc46534a162af4c8ce1fac6b812ecb8bca3e0ba2, but it's too verbose for key not found errors, which happen often
=> chore: don't log key not found errors

packages/cli/src/ceramic-daemon.ts
Note this is technically a breaking change for any deployments currently relying on bundled mode on mainnet.  If they upgrade to the new version their node will fail to start up unless they switch to a dedicated IPFS node. Do we need to make a major version bump then?  Or can we just communicate it on discord and to the partners we know are using 'bundled' mode?
FYI @jpham2023
=> feat(cli): Don't allow running IPFS in bundled mode on mainnet

packages/ipfs-topology/src/ipfs-topology.ts
Only logs at debug log level, but that's what we use on our nodes in our tests and infra so should help us debug failures.
=> chore: Log connected peers at startup

packages/core/src/state-management/repository.ts, packages/core/src/store/anchor-request-store.ts, packages/core/src/store/level-db-store.ts
* Noticed that the anchor request store wasn't being closed, its a no op for this store, but can be for other types of stores.
* This is not a solution but can provide better insight into whats happening with little impact. I have a solution on deck, but I'm not too fond of it as the packages it needs are "deprecated". 
* Should we be upgrading our level packages (level-ts uses deprecated level packages) 
Unit tests are running
=> chore(core): Add logging when creating new leveldb store

packages/cli/src/ceramic-daemon.ts
The S3 state store was being initialized before the Ceramic DID was set up. Normally, this worked fine but if the state store path was changed and indexed model streams previously accessible were no longer available in the store, the node would attempt to load them from the network. Without the DID set up correctly, this would cause the startup process to fail.
=> fix: initialize s3 state store after setting up did

packages/stream-model-handler/src/model-handler.ts, packages/stream-model-instance-handler/src/model-instance-document-handler.ts, packages/stream-tile-handler/src/tile-document-handler.ts
This mostly manifests as logging the wrong StreamID.
In theory, the StreamID we pass to `SignatureUtils.verifyCommitSignature` can matter, because it's possible to issue a CACAO that is authorized only to write to a specific StreamID.  This definitely matters for updates.  But this PR only changes code for applying genesisCommits.  It's pretty hard to create a CACAO that will let you only create a specific stream with a specific StreamID, because you usually don't know the StreamID until after the Stream is created.  So practically speaking its very hard for this to ever be an actual issue.  In theory if you were using a deterministic stream you could predict the StreamID before creating it and then issue a CACAO that allows someone to create it.  But that's a pretty niche and unlikely …
=> fix: Use envelope not payload when building StreamID for applying genesis commits

.github/workflows/reusable-release.yml
I tried building without the flag and the installation worked correctly in a GitHub runner 🤷🏼  The flag is only supposed to apply during the install step anyway.
I can leave this PR open and perhaps the next RC/release you make, @stbrody, can be run from this branch so we can test the workflow before it goes in.
=> fix: remove deprecated unsafe-perm npm flag

packages/streamid/package.json, packages/streamid/src/commit-id.ts, packages/streamid/src/event-id.ts, packages/streamid/src/stream-id.ts
This should be a fix for https://forum.ceramic.network/t/from-discord-user-elcharitas-please-help-i-am-running-a-local-ceramic-node-and-i-keep-getting-this-error/1374/15
If I understand the issue correctly, [`uint8arrays` v4.0.9 released 3 days ago](https://github.com/achingbrain/uint8arrays/releases/tag/v4.0.9) is more strict in the input values it accepts for `concat()`, it only accepts `Uint8Array` and no longer plain `Array` that can be generated by using `varint.encode()`, so this PR ensures these are explicitly cast.
=> Fix Uint8Array inputs for concatenation calls

packages/cli/src/ceramic-daemon.ts, packages/cli/src/s3-store.ts, packages/core/src/state-management/repository.ts, packages/core/src/store/ikv-store.ts, packages/core/src/store/level-db-store.ts
From my understanding of the ticket this is the kind of logic required, though I'm wondering about the following:
- Is the `storeRoot` path logic correct?
- If the `s3Bucket` option is not provided, is there a default value?  
- Is `elp` the right name for the network?
- Is the `storeRoot` value the right one to provide for the S3 `Bucket` check? 
- Is the `S3Store` internal logic OK if I replace the network name by `elp` or are there other changes needed there?
- Is there any way to test the behavior in unit tests or manually locally?
Thanks!
=> Check if ELP bucket exists for S3 state store

packages/core/src/state-management/repository.ts
This is the bug that causes anchored updates to be lost after a node restart.  It was introduced in https://github.com/ceramicnetwork/js-ceramic/commit/62bc7cbdef356e32768282d09c1c96409142b16a, almost 2 months ago.
=> fix: Update state store after applying update

packages/indexing/.eslintrc.json, packages/indexing/src/history-sync/sync-api.ts, packages/indexing/src/insertion-order.ts, packages/indexing/src/query-filter-converter.ts, packages/indexing/tsconfig.linter.json, packages/ipfs-daemon/.eslintrc.json, packages/ipfs-daemon/src/rust-ipfs.ts, packages/ipfs-daemon/tsconfig.linter.json, packages/stream-model-handler/.eslintrc.json, packages/stream-model-handler/src/__tests__/schema-utils.test.ts, packages/stream-model-handler/tsconfig.linter.json, packages/stream-tests/.eslintrc.json, packages/stream-tests/src/__tests__/caip10/near.test.ts, packages/stream-tests/src/__tests__/invalid_tip.test.ts, packages/stream-tests/tsconfig.linter.json
This PR introduces an ESLint rule in the js-ceramic codebase to prevent floating promises in the core package. Floating promises occur when the outcome of a promise is not explicitly managed. Packages touched are indexing, ipfs-daemon, stream-model-handler and stream-tests
To address this, we apply one of three strategies:
Handling Positive and Negative Outcomes: This involves adding a .catch() to manage errors when promises fail.
Using void Keyword: This is used when the result of the promise is intentionally ignored.
Silencing the Linter: This is a last resort and should be used sparingly. This is used when the linter is highlighting code that we do not think should be highlighted
This PR is an extension of : https://github.com/ceramicnetwork/js-ceramic/pull/3049
To ensure the …
=> chore(indexing, ipfs-daemon, stream-model-handler, stream-tests) : cat added no-floating promise linter to pkgs and fixed errors related

packages/core/.eslintrc.json, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/__tests__/ceramic-query-response.test.ts, packages/core/src/__tests__/shutdown-signal.test.ts, packages/core/src/state-management/__tests__/anchor-resuming-service.test.ts, packages/core/src/state-management/repository.ts, packages/core/src/stream-loading/__tests__/tip-fetcher.test.ts, packages/core/tsconfig.json, packages/core/tsconfig.linter.json, packages/ipfs-topology/src/ipfs-topology.ts
This PR introduces an ESLint rule in the js-ceramic codebase to prevent floating promises in the core package. Floating promises occur when the outcome of a promise is not explicitly managed. To address this, we apply one of three strategies:
1) Handling Positive and Negative Outcomes: This involves adding a .catch() to manage errors when promises fail.
2) Using void Keyword: This is used when the result of the promise is intentionally ignored.
3) Silencing the Linter: This is a last resort and should be used sparingly.
To ensure the effectiveness of this rule, the following test was conducted:
Test 1: Executed npm lint to confirm no errors related to @typescript-eslint/no-floating-promises.
- Test 1 : ran npm lint, ensured no errors regarding to the rule …
=> chore(core): cat 2855 add lint rule to detect promises that never get awaited on core

docs-src/guides/create-doctype.md
Fix one typo in the document: "/docs-src/guides/create-doctype.md"
No test required
=> Fix: Fix one typo in the docs

packages/core/src/anchor/__tests__/anchor-processing-loop.test.ts, packages/core/src/anchor/anchor-processing-loop.ts, packages/core/src/anchor/ethereum/ethereum-anchor-service.ts, packages/core/src/anchor/processing-loop.ts, packages/core/src/store/__tests__/level-anchor-request-store.test.ts, packages/core/src/store/anchor-request-store.ts
Adds logs and exception handling.  Also increases restart delay from 100ms to 1 second to avoid hammering S3 too often.
=> fix: Make AnchorRequestStore processing loop more robust

packages/cli/src/ceramic-daemon.ts
Now even if SSE feed is connected, the daemon could be closed.
=> chore: Close connections on Ctrl+C

packages/core/src/state-management/repository.ts
If we hit the case here where the state isn't found in the cache or state store, but then we wind up creating a new RunningState object here, we don't ever call _registerRunningState on it.
=> fix: register new running state

packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/core/src/state-management/repository.ts
This ensures that two different tasks can't clobber each other's writes to the state store
=> fix: Always update the StateStore from within the ExecutionQueue

packages/core/src/anchor/processing-loop.ts, packages/core/src/store/__tests__/level-anchor-request-store.test.ts, packages/core/src/store/anchor-request-store.ts
This is kind of me taking a stab in the dark because I still don't have any really good hypothesis for why the anchor polling keeps stopping.  But since the processing loop is serial, I had the thought that if the query from S3 hung for any reason, it would lock up the whole loop.  So this patch addresses that, as well as adding some increased logging to ProcessingLoop.
=> feat: Timeout fetching batches from the AnchorRequestStore

packages/core/src/anchor/ethereum/ethereum-anchor-validator.ts
Previously: In readOnly mode cannot load streams fully. Logs show the following error
```
[2024-01-17T22:22:25.350Z] WARNING: 'Error when validating anchor commit: Error: Any anchor proofs created after block undefined must include the txType field. Anchor txn blockNumber: 15325737'
[2024-01-17T22:22:25.352Z] WARNING: 'Error when validating anchor commit: Error: Any anchor proofs created after block undefined must include the txType field. Anchor txn blockNumber: 15325737'
[2024-01-17T22:22:25.354Z] WARNING: 'Error when validating anchor commit: Error: Any anchor proofs created after block undefined must include the txType field. Anchor txn blockNumber: 15325737'
```
Now: In readOnly mode can load streams fully. No errors in logs 
Run in readOnly mode. Successfully load streams fully …
=> fix(core): Use the anchor proofs chain id to verify the anchor proof

packages/stream-model-instance-handler/src/__tests__/model-instance-document-handler.test.ts, packages/stream-model-instance/src/model-instance-document.ts
This will be useful to users of the Firehose who won't have access to the StreamState object but might still want to be able to issue updates to documents that they are maintaining via the Firehose.
=> feat: Add static method for updating a MID without access to the StreamState

packages/indexing/src/tables-manager.ts, packages/stream-model-instance/src/model-instance-document.ts, packages/stream-tests/src/__tests__/model.test.ts, packages/stream-tests/src/__tests__/pg-model-indexing.test.ts
Postgres was not preserving casing on field names, so index validation was
failing on MID table creation. Added additional test file to verify PG
behavior.
Addresses WS2-2960 and WS2-2937
=> fix: load model should work under postgres

packages/core/src/ceramic.ts
Otherwise we can get a different error while trying to close half-initialized state, and wind up masking whatever the actual real error was that caused initialization to fail in the first place.
=> fix: Don't attempt to close Ceramic if it never finished initializing

packages/codecs/package.json, packages/common/src/stream.ts, packages/core/src/state-management/repository.ts, packages/indexing/src/__tests__/database-index-api.test.ts, packages/indexing/src/database-index-api.ts, packages/indexing/src/local-index-api.ts, packages/stream-model-instance-handler/src/__tests__/model-instance-document-handler.test.ts, packages/stream-model-instance-handler/src/model-instance-document-handler.ts, packages/stream-model-instance-handler/src/schema-utils.ts, packages/stream-model-instance/src/model-instance-document.ts, packages/stream-tests/package.json, packages/stream-tests/src/__tests__/caip10/tezos.test.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts, packages/stream-tests/src/create-ceramic.ts
Replaces #3109 due to merge conflicts.
- `shouldIndex` still remains as it was previously agreed on.
- `shouldIndex` is part of opts still: this makes the most sense from DX and release management perspective.
=> feat: Add shouldIndex metadata flag

packages/codecs/src/feed.ts, packages/codecs/src/stream.ts
The current codec would misbehave for `metadata.model` field, as it is Uint8Array encoded. Also, if we do decode on the current codec, only commitId field is available. This PR introduces a StreamMetadata codec and a more complete AggregationDocument codec.
This change doesn't require a different usage to the current implementation.
=> feat: make the feed codecs more robust

.github/workflows/reusable-release.yml, package.json
`--canary` mode appears to have a bug where it won't update internal dependencies on publish. e.g. If package A (`v1`) and B (`v1`) are published and A refers internally to B, then canary mode will publish A => `v1.1-nightly.0` and B => `v1.1-nightly.0` but A will continue to refer to B => `v1` internally.
=> fix: use lerna conventional-prerelease for nightlies

packages/streamid/package.json, packages/streamid/src/__tests__/event-id.test.ts, packages/streamid/src/event-id.ts
We can possible receive hex strings from the recon api. We made assumptions about the even height byte length that we should not have.
=> fix: event id can parse hex string

packages/stream-model-handler/src/views-utils.ts, packages/stream-model/src/codecs.ts
Enables defining a relation to a single document in a set, for example accessing a "like" on a post for a given input DID.
=> feat(stream-model,stream-model-handler): Add support for `relationSetFrom` view in model definition

packages/stream-model-handler/package.json, packages/stream-model/package.json
No sure how Lerna and/or the nightly releases script works but it seems the last 2 commits for these packages didn't get released to the nightly channel, maybe it's because they didn't use the conventional commit format?
If so, hopefully this commit will help having the changes detected and released.
=> chore(stream-model,stream-model-handler): bump version

packages/cli/package.json, packages/core/package.json, packages/core/src/anchor/anchor-processing-loop.ts, packages/core/src/store/anchor-request-store.ts
We need to track the latency of the anchor requests in the polling loop
however we need to make sure not to add excessive overhead
this pr adds reporting with interval-based publishing if prometheus metrics are turned on
Under the Hood:
calls to the TimeableMetric.count() are added to an internal counter only 
there is a setInterval call that runs at the requested interval that then calls the observe code which creates a scrapable observation on prometheus for the average and max over the interval
This mechanism is all hidden from js-ceramic.  The reason for it underneath is that we want to avoid creating load and the actual OTLP observe has a non-negligible overhead.  So we use this lighter weight calculation for every stream, and the heavier observe only once per interval.  
Before …
=> use interval publishing metrics for anchor polling loop delay

.github/workflows/reusable-release.yml, package.json
I was unnecessarily complicating the nightly releases. This PR simplifies the flow and eliminates the package versioning conflicts the workflow was running into previously.
Not having the `--preid` in the `package.json` command means that, if left unspecified when called manually, it will use the default of `beta`.
I've been able to create multiple releases using the workflow, e.g. for [stream-model](https://www.npmjs.com/package/@ceramicnetwork/stream-model?activeTab=versions), even without any changes to the package.
I was able to update the e2e tests to use the new versions and they compiled. I'm also going to run them and see if they pass after auto-updating.
=> fix: create unique package versions for nightly releases

packages/core/src/anchor/__tests__/anchor-processing-loop.test.ts, packages/core/src/anchor/anchor-processing-loop.ts, packages/core/src/anchor/processing-loop.ts, packages/core/src/store/anchor-request-store.ts
An alternative approach to https://github.com/ceramicnetwork/js-ceramic/pull/3152 that addresses the concerns raised in my comment there.
This changes the ProcessingLoop to swallow errors instead of returning an encountered error when the loop shuts down as it did before.  This is because now that multiple tasks are running concurrently, it's possible to get multiple errors at once, and it isn't clear what error should be returned by the loop.  Given that nothing outside of tests was actually doing anything with the returned error other than logging it anyway, just logging it and otherwise swallowing errors seems fine.
=> feat: Add concurrency to ProcessingLoop

docs-dev/ADVANCED_CONFIG.md, docs-dev/QUICKSTART.md, packages/cli/src/ceramic-cli-utils.ts
This will allow node operators to enable prometheus metrics as well as collector metrics from the node environment
=> Allow consistent management of metrics related config settings from environment

packages/core/src/state-management/repository.ts, packages/stream-tests/src/__tests__/deterministic-model-instance-document.test.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts, packages/stream-tests/src/__tests__/model.test.ts, packages/stream-tests/src/__tests__/pg-model-indexing.test.ts
This does reduce our test coverage of basic composedb features a good amount though.  I did this without modifying the body of any tests, just disabling any test that fails, but many of them fail just because the tests happens to check that the anchor status is PENDING in some place, without really relying on anchoring as a core part of the test.  I could, instead, use the env var inside of test bodies to selectively skip just the parts of the tests that are breaking, but leaving the bulk of many of the tests in tact.  It would just muddy up some of the tests a bit and to put them back later we'd have to grep for uses of the `CERAMIC_RECON_MODE` flag instead of just being able to search for `testIfV3ShouldPassWithAnchoring` and `describeIfV3ShouldPassWithAnchoring`.
I kind of think that …
=> feat: Disable anchoring when CERAMIC_RECON_MODE env var is set

packages/cli/src/ceramic-cli-utils.ts, packages/core/src/dispatcher.ts, packages/stream-model-handler/src/__tests__/interfaces-utils.test.ts, packages/stream-model-handler/src/interfaces-utils.ts
Currently js-composedb enforces that if an interface being implemented has an immutable fields this constraint should be kept by the implementer. This PR adds the enforcement on the server side.
=> feat: enforce immutability constraints when working with interfaces

packages/common-test-utils/src/index.ts, packages/core/src/state-management/repository.ts, packages/ipfs-daemon/src/rust-ipfs.ts, packages/stream-tests/src/__tests__/cross-node-indexing.test.ts
I moved `testIfV3` to common test utils and used it in this test suite because one of the tests in this test suite ACTUALLY cannot work in V'. 
We cannot skip publishing in V'
=> feat: turn on cross-node sync test

packages/core/src/anchor/__tests__/anchor-processing-loop.test.ts, packages/core/src/anchor/processing-loop.ts, packages/core/src/ancillary/task-queue.ts
https://github.com/ceramicnetwork/js-ceramic/pull/3163 was a really nice code cleanup, and addressed the issue of the multiple tasks being generated and run concurrently for the same logical unit of work.  It however brought back a slight performance regression by returning us to the behavior of processing work in batches, waiting for every task in the batch to finish before starting on the next task.  This PR returns us to the behavior of always keeping ourselves busy with up to the concurrency limit number of tasks running at once, and as soon as one task finishes letting the next one in immediately.
=> feat: Keep ProcessingLoop full up to the concurrency limit

packages/indexing/src/__tests__/database-index-api.test.ts, packages/indexing/src/database-index-api.ts, packages/stream-tests/src/__tests__/deterministic-indexing.test.ts
Simply looking up a deterministic stream causes it to be indexed, which causes the indexer queries to return results with empty contents that don't match the expected behavior.
This PR updates the logic to ignore streams with no content when indexing.
=> fix(indexing): don't index empty deterministic streams

packages/cli/package.json, packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/cli/src/ceramic-daemon.ts, packages/http-client/src/ceramic-http-client.ts, packages/stream-model-instance-handler/src/__tests__/model-instance-document-handler.test.ts, packages/stream-model-instance/src/model-instance-document.ts
Encodes the genesis commit in the HTTP client if present in the multiquery request and decodes it in the HTTP handler.
As we discussed before @stbrody I also made the `ModelInstanceDocument.makeGenesis()` public as I needed it for the test, and I'll also be able to use it in the ComposeDB loader.
=> fix(cli,http-client,stream-model-instance): encode genesis commit in multiquery

.github/workflows/pr-semantic-message.yml
The PR title or single commit message will be linted against conventional commit message standard. If you have multiple commits in a PR only the PR title will be linted.
=> chore: enable linting of commit messages

packages/core/package.json, packages/core/src/ceramic.ts, packages/core/src/stream-loading/__tests__/state-manipulator.test.ts, packages/core/src/stream-loading/__tests__/stream-loader.test.ts, packages/stream-model-instance-handler/package.json, packages/stream-model-instance-handler/src/__tests__/model-instance-document-handler.test.ts
This will make js-ceramic actually use multiple worker threads for schema validation.  When this merges is when we should be able to observe real improvements to js-ceramic throughput.
=> feat: Update ajv-threads package to version with worker pool

packages/common/src/utils/stream-utils.ts
The code paths needed for creating a new composedb model called the convertCommitToSignedCommitContainer function. However the function would always use online mode and fails in Recon mode. We should not need online mode as the commits will have just been stored locally. This changes the code to use offline mode when in recon mode.
Created a model using the composedb CLI, prior to this change it errors. With this change it no longer errors.
=> fix: make convertCommitToSignedCommitContainer use offline mode

packages/anchor-utils/src/constants.ts, packages/core/src/anchor/ethereum/ethereum-anchor-validator.ts, packages/core/src/initialization/anchoring.ts, packages/core/src/providers-cache.ts, packages/indexing/src/history-sync/sync-api.ts, packages/indexing/src/history-sync/workers/__tests__/rebuild-anchor.test.ts
Add Sepolia chain id to the allowed list for dev-unstable.
=> feat: add sepolia to allow chain for dev-unstable

packages/stream-model-instance-handler/src/__tests__/__snapshots__/model-instance-document-handler.test.ts.snap, packages/stream-model-instance-handler/src/__tests__/model-instance-document-handler.test.ts, packages/stream-model-instance-handler/src/model-instance-document-handler.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts
We used the payload data to determine if an immutable field was being altered, but this caused 2 problems:
- Not optimal developer experience when running a mutation including an immutable field but not mutating it.
- Databases built on top of js-ceramic using an `upsert` command will always throw if creating a new record for a model with an immutable field. e.g. ComposeDB
=> feat: update how we check immutability

.circleci/config.yml
This PR pins the version of Node.js used for running unit tests in CircleCI to the last version that worked (`20.11.1`). A newer version of Node.js (`20.12.0`) is causing (currently) unexplained errors such as the following:
```
> @ceramicnetwork/stream-model-instance@4.5.0-rc.0 test
> exit 0
PASS  src/__tests__/tezos.test.ts
FAIL  src/__tests__/near.test.ts
● Test suite failed to run
TypeError: Cannot assign to read only property 'fetch' of object '[object global]'
at Object.<anonymous> (../../node_modules/near-api-js/lib/connect.js:35:14)
at Object.<anonymous> (../../node_modules/near-api-js/lib/index.js:28:14)
ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From src/__tests__/near.test.ts.
```
=> chore: pin node.js version in circleci config

packages/core/src/anchor/ethereum/remote-cas.ts
We need metrics for keeping track of how many streams have been anchored/errored or are in pending state. This is done in order to track performance of anchoring. 
Tested locally by creating a ceramic node with config where prometheus exporter was turned on.
js_ceramic_cas_request_success_total 7513
- [Yes ] I have tagged the relevant reviewers and interested parties
- [ Not needed] I have updated the READMEs of affected packages
- [Not needed ] I have made corresponding changes to the documentation
=> feat: metrics for counting state of cas requests

packages/base-test-utils/src/__tests__/index.test.ts, packages/base-test-utils/src/index.ts, packages/common-test-utils/src/index.ts, packages/stream-tests/src/__tests__/history-sync.test.ts
Currently it returns false if it fails, which is error prone as it means the test author needs to remember to check the return value or re-check the condition after calling it.  Making it throw on error makes the behavior more obvious and harder to mis-use, at the cost of possibly getting less useful error messages in some cases.
=> chore: make TestUtils.waitForConditionOrTimeout throw on failure

packages/core/src/__tests__/ceramic-api.test.ts
The flaky behavior was caused by the node receiving the updates created by itself via recon and applying them. This caused the mock calls to include calls outside of functions we were testing for. I disabled recon in these tests as it does not test updates between nodes anyways.
=> fix: disable recon feed in test where it is causing flaky behavior

DEVELOPMENT.md
The test currently runs with recon mode off by default, but there is no documentation regarding the necessary steps to run them in recon mode, this PR includes documentation to run the test in recon mode.
In the future, when explicit documentation is available about recon, it would be useful to modify that section by including links to the recon/ceramic-one docs.
=> chore: Update DEVELOPMENT.md

packages/core/src/state-management/repository.ts, packages/core/src/store/__tests__/feed-aggregation-store.test.ts, packages/core/src/store/feed-aggregation-store.ts
In order to verify if events are not being emitted by the data feed we'll add logging for the events being dispatched from js-ceramic. The way we'll do it is by showing the timestamps of when events were written and read from Level.
=> chore: add logging for leveldb

packages/core/src/__tests__/ceramic-feed.test.ts
```
Summary of all failing tests
FAIL  src/__tests__/ceramic-feed.test.ts (13.479 s)
● Ceramic feed › add entry after anchoring stream
RangeError: Maximum call stack size exceeded
128 |     expect(emissions[1].commitId).toEqual(document.allCommitIds[0])
129 |     // model.anchor
> 130 |     expect(emissions[2].commitId.baseID).toEqual(model.id)
|                                          ^
131 |     expect(emissions[2].eventType).toEqual(EventType.TIME)
132 |     // document.anchor
133 |     expect(emissions[3].commitId).toEqual(document.allCommitIds[1])
at Object.toEqual (src/__tests__/ceramic-feed.test.ts:130:42)
```
=> chore: skip flaky test for time being

packages/cli/src/__tests__/ceramic-error.test.ts, packages/cli/src/__tests__/ceramic-multi-daemon.test.ts, packages/cli/src/__tests__/make-ceramic-core.ts, packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/__tests__/create-ceramic.ts, packages/core/src/__tests__/initialization.test.ts, packages/core/src/anchor/anchor-processing-loop.ts, packages/core/src/anchor/processing-loop.ts, packages/core/src/ceramic.ts, packages/core/src/store/__tests__/level-anchor-request-store.test.ts, packages/core/src/store/anchor-request-store.ts, packages/core/src/utils.ts, packages/stream-tests/src/__tests__/ceramic_sync_disabled.test.ts, packages/stream-tests/src/create-ceramic.ts
With this change, when the number of pending requests is small, we will poll each of them once per minute, which is aligned with how things used to work before we switched to the new polling system.  But when the number of pending requests is large, we'll poll them as fast as possible to make sure we don't fall behind.
=> fix: rate limit how fast anchor polling loops on small data sets

docs-dev/ADVANCED_CONFIG.md, docs-dev/NODE_METRICS.md, packages/cli/src/__tests__/daemon-config.test.ts, packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon-config.ts
As we move towards more decentralization, publishing metrics on the ceramic network becomes more important - so defaulting it to on.  Will notify folks in an announcement and post.
- [ x] I have updated the READMEs of affected packages
=> feat: default node metrics publishing to on and add docs

packages/cli/src/__tests__/ceramic-error.test.ts, packages/cli/src/__tests__/ceramic-multi-daemon.test.ts, packages/cli/src/__tests__/make-ceramic-core.ts, packages/cli/src/ceramic-daemon.ts, packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/__tests__/create-ceramic.ts, packages/core/src/__tests__/initialization.test.ts, packages/core/src/anchor/ethereum/__tests__/authenticated-anchor-service.test.ts, packages/core/src/anchor/ethereum/__tests__/remote-cas.test.ts, packages/core/src/anchor/ethereum/ethereum-anchor-service.ts, packages/core/src/anchor/ethereum/remote-cas.ts, packages/core/src/ceramic.ts, packages/core/src/initialization/__tests__/anchoring.test.ts, packages/core/src/initialization/anchoring.ts, packages/stream-tests/src/__tests__/ceramic_sync_disabled.test.ts, packages/stream-tests/src/create-ceramic.ts
js-ceramic half corresponding to https://github.com/ceramicnetwork/ceramic-anchor-service/pull/1232
Builds on https://github.com/ceramicnetwork/js-ceramic/pull/3245
=> feat: send js-ceramic and ceramic-one versions to CAS when creating requests

packages/cli/src/ceramic-daemon.ts
When running with simple deploy, we receive the error
```
Error: DID is not authenticated
at get id [as id]
```
handle this case and report the error, but do not fail to start
- [x ] Unit tests
=> fix(ceramic-node): handle case where the admin DID is not authenticated

packages/cli/src/ceramic-daemon.ts, packages/cli/src/ipfs-connection-factory.ts, packages/common/src/utils/environment-utils.ts, packages/core/src/__tests__/ceramic-feed.test.ts, packages/core/src/ceramic.ts, packages/ipfs-daemon/src/index.ts, packages/ipfs-daemon/src/rust-ipfs.ts
We now detect the remote IPFS node type and adjust the daemon config (really the environment variables) accordingly. This also now respects the --network CLI flag passed in when starting a ceramic one binary automatically.
[Linear ticket](https://linear.app/3boxlabs/issue/AES-159/js-ceramic-should-error-if-not-connected-to-c1-node).
=> chore: detect remote ipfs type and adjust accordingly

packages/core/src/__tests__/create-dispatcher.ts, packages/core/src/__tests__/recon.test.ts, packages/core/src/recon.ts, packages/core/src/state-management/repository.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts
current: does not resubscribe
desired: resubscribed 
added unit test and stream-test (for restarting node)
=> feat: recon resubscribes to interests on startup

Dockerfile.daemon, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/cli/src/ipfs-connection-factory.ts, packages/ipfs-daemon/src/index.ts
The default IPFS mode is now remote with localhost:5101 (ceramic-one). We no longer support starting the ceramic-one binary automatically in bundled mode outside of tests. It didn't provide a super elegant startup as we don't have a good cross platform install method for node so couldn't guarantee the defaults and it isn't how we want people to run things anyway. It also had some issues stopping, especially when errors occur during start up and rather than rework that handling, we're moving away from the option.
This changes the default config options to remote ceramic one, so it doesn't "just work" if you run `node ceramic.js daemon` like it would before. If you previously had bundled mode in your config, you will get an error saying it's not supported and you should pass a url.
The …
=> chore: change ipfs default to remote mode and remove bundled ceramic-one

packages/core/src/anchor/ethereum/remote-cas.ts, packages/core/src/dispatcher.ts, packages/core/src/state-management/repository.ts
Created in order to observe gitcoin errors better. This adds more observability regarding calls to IPFS and CAS.
NOTE : Currently we are not using spans anywhere in the code-base to record time function calls usually take. Thus, this PR uses Gauge's to track that. Once we have support for observing spans better we can use those.
Added a TODO in the PR to tackle this, as well as commented out code on how we should use spans.
We can use 'avg_over_time[5m(or any other time duration)]' in grafana to get observability over the gauges we have added.
=> feat: more observability for import CAR and CAS polling

packages/core/src/__tests__/ceramic-feed.test.ts
=> test: Unskip a flaky feed API test

packages/core/src/__tests__/initialization.test.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/core/src/recon.ts
Related to the new network startup check for ceramic one. That error happens earlier than the cas error was, so we get a different error. On kubo, we get the old error. We also check a few fields are not null when cleaning up in case we somehow didn't manage to call init() due to an error in `ceramic._init()` but we still try to stop everything.
=> fix: adjust tests for failure to start due to network mismatch

packages/base-test-utils/src/index.ts, packages/common/src/utils/abort-signal-utils.ts, packages/core/src/ceramic.ts, packages/core/src/dispatcher.ts, packages/core/src/shutdown-signal.ts
New approach instead of https://github.com/ceramicnetwork/js-ceramic/pull/3265.
Now we start a background job that waits forever for the NodeMetrics model to be synced (using exponential backoff, maxing out at checking once per minute).  If the model never becomes available, that job will keep checking for the Model once per minute, and will log an error once every 5 minutes.  If the model ever becomes available, however, it will start up the NodeMetrics publishing subsystem at that point and the background task stops.
=> feat: Start up Node Metrics publishing after the Model becomes available locally

packages/core/src/__tests__/recon.test.ts, packages/core/src/ceramic.ts, packages/core/src/recon.ts
In testing the node metrics publish I found two bugs:
1. Metrics interest was for all peers not just itself.
2. The node id was empty causing the published data to fail validation.
This fixes both issues.
The controller needs to be a query parameter not a POST body object.
The `ipfsId.publicKey` was empty I do not know why, however the `ipfsId.id` field was set correctly and works as expected.
Manually tested, starting a node. Previously the node saw errors everytime it tried to publish metrics. Additionally I directly inspected the interest and was able to see it was for all controllers not just itself. I have manually verified the interest is now for the specific controller.
Please list relevant documentation (e.g. tech specs, articles, …
=> fix: correctly use controller when registering interest and correctly use node's ID when publishing metrics.

packages/core/src/state-management/__tests__/repository.test.ts, packages/core/src/state-management/repository.ts
~Needs testing~ steph: Tested manually using both ipfs + c1, and added a unit test
This has the downside that if the reason applying the anchor failed is *not* transient, like if the TimeEvent is malformed or otherwise invalid, we will still leave the event in the store and keep retrying it.  I think that is probably fine for now since we don't expect to be getting any fundamentally invalid TimeEvents from the CAS.  Self-anchoring in C1 should be able to be more intelligent in understanding what types of failure modes are transient vs irrecoverable.
=> fix: Don't remove entries from AnchorRequestStore if applying the anchor commit fails

DEVELOPMENT.md, packages/cli/src/s3-store.ts, packages/core/src/ancillary/task-queue.ts, packages/core/src/state-management/named-task-queue.ts, packages/indexing/src/history-sync/workers/rebuild-anchor.ts
From the datadog analysis, it looks like the gitcoin out of memory errors are related to queue growth specifically with the p-queue library.
This adds metrics to all instances of PQueue to track the size and add operations.
=> feat: add metrics to track queue sizes and add operations - #AES-361

packages/core/src/state-management/named-task-queue.ts
=> fix: do not log names of all queues, cardinality is too high

packages/cli/src/ceramic-daemon.ts, packages/core/src/dispatcher.ts, packages/core/src/initialization/stream-loading.ts, packages/stream-tests/src/__tests__/ceramic_sync_disabled.test.ts
Flag can be enabled by setting `ipfs.disablePeerDataSync` in the config file, or with the new `CERAMIC_DISABLE_PEER_DATA_SYNC` env var.
turning on this flag does 3 things:
1. Fully disable pubsub.  The node will not subscribe to the ceramic pubsub topic, and will not publish or receive any pubsub messages
2. Turns down the timeout when getting blocks from ipfs from 30 seconds to 1 second
3. Uses the "offline" flag whenever loading blocks form ipfs so that the request will fail immediately if the block is not found in the ipfs node's local blockstore.  IPFS will never try to load the block via bitswap.
Blocks published to ipfs with this flag enabled should still be fetchable by other ipfs nodes over bitswap.
=> feat: Flag to fully disable pubsub and all cross-node syncing

packages/ipfs-daemon/src/rust-ipfs.ts
=> fix: Disable event-validation in C1 in unit tests
