ceramicnetwork/js-ceramic

.dockerignore, Dockerfile.daemon, package-lock.json, packages/ceramic-cli/package-lock.json, packages/ceramic-cli/src/index.ts, packages/ceramic-core/package-lock.json, packages/ceramic-http-client/package-lock.json
Added a dockerfile for the ceramic daemon, and implemented the the CLI option to set the IPFS API URL
=> add cli dockerfile, add ipfs-api daemon option

package.json, packages/ceramic-cli/package.json, packages/ceramic-core/package.json
Also update the bootstrap script.
=> fix(package): explicitly set identity-wallet version for now

.gitignore, package-lock.json, packages/ceramic-cli/package-lock.json, packages/ceramic-cli/src/__tests__/ceramic-daemon.test.ts, packages/ceramic-cli/src/ceramic-daemon.ts, packages/ceramic-cli/src/index.ts, packages/ceramic-cli/src/utils.ts, packages/ceramic-core/package-lock.json, packages/ceramic-core/package.json, packages/ceramic-core/src/__tests__/ceramic.test.ts, packages/ceramic-core/src/__tests__/document.test.ts, packages/ceramic-core/src/anchor/anchor-service-factory.ts, packages/ceramic-core/src/anchor/anchor-service-response.ts, packages/ceramic-core/src/anchor/anchor-service.ts, packages/ceramic-core/src/anchor/ethereum/ethereum-anchor-service.ts, packages/ceramic-core/src/anchor/mock/mock-anchor-service.ts, packages/ceramic-core/src/ceramic.ts, packages/ceramic-core/src/doctypes/__tests__/__snapshots__/accountLinkHandler.test.ts.snap, packages/ceramic-core/src/doctypes/__tests__/__snapshots__/threeIdHandler.test.ts.snap, packages/ceramic-core/src/doctypes/__tests__/__snapshots__/tileHandler.test.ts.snap, packages/ceramic-core/src/doctypes/accountLinkHandler.ts, packages/ceramic-core/src/doctypes/threeIdHandler.ts, packages/ceramic-core/src/doctypes/tileHandler.ts, packages/ceramic-core/src/document.ts, packages/ceramic-http-client/src/document.ts
- implement Ethereum anchor service
- implement support for future anchor services (other block[chains])
- update tests
=> Ceramic anchor service integration

packages/ceramic-core/src/anchor/ethereum/ethereum-anchor-service.ts
- emit `PROCESSING` event for anchor status
=> bug(core): emit processing state

packages/ceramic-cli/package.json, packages/ceramic-core/package-lock.json, packages/ceramic-core/package.json, packages/ceramic-core/src/__tests__/document.test.ts, packages/ceramic-core/src/anchor/mock/mock-anchor-service.ts, packages/ceramic-core/src/dispatcher.ts, packages/ceramic-core/src/document.ts
- add `prev` verification for anchor record
=> fix(core): add prev verification for anchor record

packages/ceramic-cli/src/ceramic-daemon.ts
- feat(core): make `ethereumRpcUrl` optional
=> feat(core): make ethereumRpcUrl optional

packages/ceramic-cli/src/ceramic-daemon.ts
- add default anchor service URL
=> feat(core): add default anchor service URL

packages/ceramic-http-client/src/ceramic-http-client.ts
=> fix(cli): fix pin call

packages/ceramic-core/src/__tests__/document.test.ts, packages/ceramic-core/src/document.ts
=> fix(core): fix state management

packages/ceramic-core/src/__tests__/ceramic-api.test.ts, packages/ceramic-core/src/document.ts
- validate "update" content with "update" schema
- add test
=> Simultaneous content and schema update

packages/ceramic-cli/src/ceramic-cli-utils.ts, packages/ceramic-common/src/utils/doctype-utils.ts
- validate schema
- print error messages in CLI
=> Validate schema

packages/ceramic-core/src/dispatcher.ts
The record cache should not be needed anymore.
=> chore(core): remove record cache in dispatcher

packages/ceramic-core/src/ceramic.ts, packages/ceramic-core/src/document.ts, packages/ceramic-core/src/store/__tests__/state-store-integration.test.ts
- fix document creation
- adapt tests
=> fix(core): fix document creation

packages/ceramic-core/src/ceramic.ts, packages/ceramic-http-client/src/ceramic-http-client.ts
=> Add user getter to CeramicApi implementations

packages/ceramic-http-client/src/ceramic-http-client.ts
Fixes https://github.com/3box/identity-wallet-js/issues/71
=> fix(http-client): return correct doc instance from createDocument

packages/ceramic-common/package.json
=> chore(common): remove deps

package-lock.json, package.json, packages/ceramic-cli/package-lock.json, packages/ceramic-cli/package.json, packages/ceramic-cli/src/__tests__/ceramic-daemon.test.ts, packages/ceramic-cli/src/bin/ceramic.ts, packages/ceramic-cli/src/ceramic-cli-utils.ts, packages/ceramic-common/package.json
- add config option to the CLI
- fix seed generation
=> feat(cli): add config option to CLI

packages/ceramic-cli/package.json, packages/ceramic-cli/src/__tests__/ceramic-daemon.test.ts, packages/ceramic-cli/src/ceramic-cli-utils.ts, packages/ceramic-common/package.json, packages/ceramic-core/package.json, packages/ceramic-core/src/__tests__/ceramic-api.test.ts, packages/ceramic-core/src/__tests__/ceramic.test.ts, packages/ceramic-doctype-account-link/package.json, packages/ceramic-doctype-three-id/package.json, packages/ceramic-doctype-tile/package.json
=> feat: bump IW deps

packages/ceramic-cli/src/ceramic-daemon.ts, packages/ceramic-common/src/logger-factory.ts, packages/ceramic-core/src/ceramic.ts
=> feat(cli): disable CLI logs

packages/ceramic-cli/package-lock.json, packages/ceramic-cli/package.json, packages/ceramic-cli/src/ceramic-daemon.ts
replaces with cors middleware library, handles complex req, post with content application/json not supported by only allow origin, this supports those headers and preflight reqs
=> feat: cors middleware, preflight/content type

packages/ceramic-common/package.json, packages/ceramic-core/package.json, packages/ceramic-doctype-tile/package.json, packages/ceramic-http-client/package.json
=> chore: bump dids dep

package-lock.json, packages/ceramic-cli/package.json, packages/ceramic-cli/src/ceramic-cli-utils.ts, packages/ceramic-cli/src/ceramic-daemon.ts, packages/ceramic-core/package.json, packages/ceramic-doctype-account-link/package.json, packages/ceramic-doctype-tile/package.json
* fix `ipfs` and `ipfs-http-client` components and add repos to my personal github account:
* `ipfs`: github:simonovic86/ipfs
* `ipfs-http-client`: github:simonovic86/ipfs-http-client
* add support for `dag-jose` while creating `ipfsClient`
=> feat: add dag-jose format to ipfs-http-client

packages/ceramic-cli/package.json, packages/ceramic-common/package.json, packages/ceramic-core/package.json, packages/ceramic-doctype-account-link/package.json, packages/ceramic-doctype-tile/package.json
- revert the `identity-wallet` to `2.0.0-alpha.11`
=> Change identity-wallet version

packages/ceramic-core/src/dispatcher.ts, packages/ceramic-core/src/document.ts
- replace `ipfs.dag.get(cid, path)` with `ipfs.dag.get(cid | path)`
=> Fix anchor record verification

packages/ceramic-cli/package.json, packages/ceramic-cli/src/__tests__/ceramic-daemon.test.ts, packages/ceramic-cli/src/ceramic-cli-utils.ts, packages/ceramic-common/package.json, packages/ceramic-core/package.json, packages/ceramic-core/src/__tests__/ceramic-api.test.ts, packages/ceramic-core/src/__tests__/ceramic.test.ts, packages/ceramic-doctype-account-link/package.json, packages/ceramic-doctype-tile/package.json
- update IDW to `^2.0.0-alpha.13` and adapt tests
=> Update IDW and adapt tests

packages/ceramic-core/src/ceramic.ts
=> Fix pinning list

packages/ceramic-cli/package.json, packages/ceramic-cli/src/ceramic-cli-utils.ts, packages/ceramic-cli/src/declarations.d.ts, packages/ceramic-core/package.json, packages/ceramic-core/src/__tests__/ceramic.test.ts, packages/ceramic-core/src/__tests__/document.test.ts, packages/ceramic-core/src/anchor/memory/in-memory-anchor-service.ts, packages/ceramic-core/src/store/__tests__/state-store-integration.test.ts, packages/ceramic-doctype-tile/src/tile-doctype-handler.ts
- sync CAS logic with in-memory implementation
- fix CLI `seed` generation
- adapt tests
=> Sync CAS logic with in-memory implementation

packages/ceramic-common/src/pinning.ts, packages/pinning-aggregation/src/__tests__/pinning-aggregation.test.ts, packages/pinning-aggregation/src/index.ts, packages/pinning-ipfs-backend/package-lock.json, packages/pinning-ipfs-backend/src/__tests__/async-iterable-from-array.util.ts, packages/pinning-ipfs-backend/src/__tests__/ipfs-pinning.test.ts, packages/pinning-powergate-backend/src/index.ts, tsconfig.json
- fix pinning dependency
- minor refactor (spaces, etc)
- add `references` to root config
=> Fix pinning dependency

packages/ceramic-core/src/ceramic.ts, packages/ceramic-core/src/document.ts
- apply standard flow for `applyRecord`
=> Apply standard flow for applyRecord

packages/ceramic-common/package.json, packages/ceramic-core/package.json, packages/ceramic-doctype-account-link/package.json, packages/ceramic-doctype-tile/package.json, packages/ceramic-http-client/package.json, packages/docid/package.json
=> bump cids version

packages/ceramic-cli/src/ceramic-daemon.ts
- serialize Doc ID on `create`
=> Serialize Doc ID

Dockerfile.daemon, packages/ceramic-cli/package.json, packages/ceramic-common/package.json, packages/ceramic-core/package-lock.json, packages/ceramic-core/package.json, packages/ceramic-doctype-account-link/package-lock.json, packages/ceramic-doctype-account-link/package.json, packages/ceramic-doctype-tile/package-lock.json, packages/ceramic-doctype-tile/package.json, packages/ceramic-http-client/package-lock.json
- IDW dependency bump
- fix `Dockerfile`
=> IDW dependency bump

packages/key-did-resolver/package-lock.json, packages/key-did-resolver/package.json, packages/key-did-resolver/src/__tests__/__snapshots__/ed25519.test.ts.snap, packages/key-did-resolver/src/__tests__/ed25519.test.ts, packages/key-did-resolver/src/__tests__/index.test.ts, packages/key-did-resolver/src/ed25519.ts, packages/key-did-resolver/src/index.ts, packages/key-did-resolver/src/secp256k1.ts
Adds support for `ed25519` keys to the key-did-resovler. This keytype also supports keyExchange by converting the public ed25519 key to a public x25519 key.
=> feat(key-did-resolver): add support for ed25519

packages/ceramic-cli/src/ceramic-cli-utils.ts
- enable IPFS DHT functionality
=> Enable IPFS DHT functionality

packages/ceramic-cli/src/ceramic-cli-utils.ts
=> Disable random walk for DHT

packages/cli/src/ceramic-daemon.ts, packages/http-client/src/ceramic-http-client.ts, packages/http-client/src/document.ts, packages/http-client/src/utils.ts
Now there are four main names of endpoints:
* records - get all records of a document
* document - interact with a document
* pins - interact with the pinset
* node - get information about the node
=> ref: update daemon api and http-client

Dockerfile.daemon
Also used glob to copy package and package-lock files
=> fix: copy pinning packages to dockerfile

packages/cli/package.json, packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/cli/src/declarations.d.ts, packages/common/package-lock.json, packages/common/package.json, packages/common/src/context.ts, packages/common/src/declarations.d.ts, packages/common/src/index.ts, packages/common/src/utils/doctype-utils.ts, packages/core/package.json, packages/core/src/__tests__/ceramic-anchor.test.ts, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/ceramic.test.ts, packages/core/src/ceramic.ts, packages/core/src/declarations.d.ts, packages/core/src/dispatcher.ts, packages/pinning-ipfs-backend/src/declarations.d.ts, packages/pinning-ipfs-backend/src/index.ts
- fix imports for IPFS API types
- replace `ipfs` dependency with `ipfs-core`
=> IPFS API type import fixes

packages/common/src/index.ts
- fix IPFS API type import/export
=> IPFS API type import

packages/common/src/doctype.ts, packages/common/src/utils/doctype-utils.ts, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/document.test.ts, packages/core/src/ceramic.ts, packages/core/src/dispatcher.ts, packages/core/src/store/__tests__/state-store-integration.test.ts
- rename `SignedRecordDTO` to `SignedRecordContainer`
=> Rename SignedRecordDTO to SignedRecordContainer

packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/dispatcher.ts
- add restrictions for record size: the default limit is **256KB**
- add tests
=> Record size restriction

packages/core/src/anchor/ethereum/ethereum-anchor-service.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts
- set soft limit for number of listeners
- handle **404** statuses
- minor refactor
=> Anchor service client fixes

packages/core/src/__tests__/ceramic-anchor.test.ts, packages/core/src/__tests__/document.test.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/core/src/document.ts
This PR should not be considered a blocker to releasing tomorrow
=> chore(core): Update conflict resolution in InMemoryAnchorService

packages/common/src/doctype.ts
=> Remove refs property

packages/cli/src/ceramic-daemon.ts
Status code in the logs were always 200 when the actual response sent back a 5xx.
- Send response first then produce the http log so that `res.statusCode` and `res.statusMessage` are accurate
- Also only log usage stats when healthcheck fails to reduce noise of healthcheck logs
=> fix: log api errors with status and message

packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/dispatcher.ts
Causes this error https://github.com/ceramicnetwork/js-ceramic/issues/737
=> hotfix: remove timeout option from pubsub subscribe

packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/cli/src/ceramic-cli-utils.ts, packages/common/src/doc-cache.ts, packages/http-client/src/ceramic-http-client.ts
Not sure if the commit name works for our semantic versioning system.  How are we supposed to handle a fix to multiple packages?  @oed
=> fix(cli,http-client): Fix pin API in CLI and http client

packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/common/src/anchor-service.ts, packages/common/src/ceramic-api.ts, packages/common/src/doctype.ts, packages/common/src/utils/doctype-utils.ts, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/__tests__/document.test.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/core/src/ceramic.ts, packages/core/src/dispatcher.ts, packages/core/src/document.ts, packages/core/src/store/__tests__/level-state-store.test.ts, packages/core/src/store/__tests__/state-store-integration.test.ts, packages/doctype-caip10-link-handler/src/__tests__/caip10-link-doctype-handler.test.ts, packages/doctype-caip10-link-handler/src/caip10-link-doctype-handler.ts, packages/doctype-caip10-link/src/caip10-link-doctype.ts, packages/doctype-tile-handler/src/__tests__/three-id.test.ts, packages/doctype-tile-handler/src/__tests__/tile-doctype.test.ts, packages/doctype-tile-handler/src/tile-doctype-handler.ts, packages/doctype-tile/src/tile-doctype.ts, packages/http-client/src/ceramic-http-client.ts, packages/http-client/src/document.ts, packages/http-client/src/utils.ts
Somehow failed to force push the branch in #764. So, here it is @oed @stbrody.
=> Record is now named Commit

packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/core/src/ceramic.ts
And exposes configuring the pubsub topic to the daemon CLI
=> feat(cli): Allow specifying pub/sub topic for 'local' ceramic network

packages/cli/src/ceramic-daemon.ts
=> fix: send http error response as json

packages/doctype-caip10-link-handler/src/__tests__/caip10-link-doctype-handler.test.ts, packages/doctype-caip10-link-handler/src/caip10-link-doctype-handler.ts, packages/doctype-caip10-link/src/caip10-link-doctype.ts, packages/doctype-tile-handler/src/__tests__/tile-doctype.test.ts, packages/doctype-tile-handler/src/tile-doctype-handler.ts, packages/doctype-tile/src/tile-doctype.ts
=> Enforce just one controller per document

docs-src/guides/add-new-blockchain.md, typedoc.json
Add a guide on how to add a new blockchain for linking/authentication purposes
=> Guide on how to add a new blockchain

packages/cli/src/build-ipfs-connection.util.ts, packages/cli/src/ceramic-cli-utils.ts
Why manual connection? Apparently, it takes a lot of time for IPFS to connect to bootstrap nodes.
Related: #778
=> Establish IPFS connectivity for PubSub

packages/cli/src/build-ipfs-connection.util.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts
This PR contains two changes:
* Properly make connections to the bootstrap nodes
=> fix(cli): Properly connect to bootstrap nodes

packages/3id-did-resolver/package-lock.json, packages/3id-did-resolver/package.json, packages/3id-did-resolver/src/__tests__/index.test.ts, packages/3id-did-resolver/src/legacyResolver.ts
=> fix: add cache to 3idv0 resolver

package-lock.json, package.json
Seems like there was an issue with eos tests due to some package mismatch. Updated the package-lock.
=> fix: update package-lock

packages/core/src/document.ts
We set the `tip` to a constant which was problematic if there is another update on the old listener. This PR changes this to use `doc.tip` which is dynamic.
=> fix(core): Properly ignore old FAILED anchor responses

.circleci/config.yml, Dockerfile.daemon
Switch from node 12 to 14 in:
* Dockerfile
* CircleCI
=> fix: Use node 14

packages/core/src/document.ts
=> fix(core): Fully process incoming tips on first document load

Dockerfile.daemon
Or at least supposed to do so.
=> chore: Docker image builds again

Dockerfile.daemon
Now with IPFS batteries included
=> chore: make Docker build again

Dockerfile.daemon
Logger package is to blame this time.
=> fix: make Docker build again

packages/common/src/utils/doctype-utils.ts
=> fix(common): Show timezone with anchorScheduledFor property

packages/core/src/anchor/memory/in-memory-anchor-service.ts
One part of https://github.com/ceramicnetwork/js-ceramic/issues/829
=> chore(core): Use the logger in InMemoryAnchorService

packages/core/src/__tests__/local-pin-api.test.ts, packages/core/src/ceramic.ts, packages/core/src/local-pin-api.ts
=> feat: extract local pin api

packages/cli/package.json, packages/cli/src/build-ipfs-connection.util.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/common/src/logger-provider.ts, packages/core/src/ceramic.ts, packages/ipfs-daemon/package.json, packages/ipfs-daemon/src/ipfs-daemon.ts, packages/ipfs-topology/package.json, packages/ipfs-topology/src/ipfs-topology.ts, packages/logger/src/index.ts
builds on https://github.com/ceramicnetwork/js-ceramic/pull/1021
=> chore(ipfs-daemon,ipfs-topology): Use logger in IpfsDaemon and IpfsTopology

packages/core/src/__tests__/ceramic.test.ts, packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/__tests__/document.test.ts, packages/core/src/__tests__/local-pin-api.test.ts, packages/core/src/ceramic.ts, packages/core/src/dispatcher.ts, packages/core/src/document.ts, packages/core/src/local-pin-api.ts, packages/core/src/repository.ts
Dummy one. No cache eviction, no persistence, even Dispatcher is the same.
=> feat: Introduce Repository

packages/logger/package.json
Since I can't repro the issue I can't actually verify that this fixes it
=> chore(logger): Add tslib dependency

packages/common/src/utils/doctype-utils.ts
Follow-on to https://github.com/ceramicnetwork/js-ceramic/pull/1100
=> fix(core): Don't display anchorScheduledFor at all when anchored

packages/core/src/__tests__/dispatcher.test.ts, packages/core/src/document.ts, packages/core/src/state-management/document-factory.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/running-state.ts
Actually, does not do much. Just a minuscule necessary step for turning Document inside out.
=> feat: Introduce Running State

packages/core/src/__tests__/ceramic-api.test.ts
This test was causing issues with circleci.
=> fix(core): stablize the test for the atTime feature

.github/workflows/docs.yaml
Is there any way to test this?
=> fix(js-ceramic): Fix deploy-docs github workflow

packages/common/src/logger-provider.ts
Doesn't actually remove the dependency from the package, so bundlers will still get mad, but now at least if you can get the code into the browser (by providing polyfills, suppressing bundler errors, or not using a bundler at all), then things should work
=> fix(common): Don't use node packages at runtime in the logger if we might be running in-browser

packages/3id-did-resolver/generateVectorDocuments.js, packages/blockchain-utils-validation/src/blockchains/__tests__/eosio.test.ts, packages/cli/package.json, packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/cli/src/ceramic-cli-utils.ts, packages/common/src/ceramic-api.ts, packages/common/src/context.ts, packages/core/src/__tests__/ceramic-anchor.test.ts, packages/core/src/__tests__/ceramic-api.test.ts, packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/__tests__/ceramic-recover-documents.test.ts, packages/core/src/__tests__/ceramic.test.ts, packages/core/src/__tests__/create-ceramic.ts, packages/core/src/ceramic.ts, packages/doctype-tile/src/tile-doctype.ts, packages/http-client/package.json, packages/http-client/src/ceramic-http-client.ts
Looks like this might be enough to stabilize the test
=> chore(blockchain-utils-validation): Increase test timeout for eosio.test.ts

packages/cli/src/ceramic-daemon.ts
When running the cli daemon no did resolvers where provided.
=> fix(cli): set a DID with resolvers in daemon

packages/core/src/state-management/state-manager.ts
=> fix(core): Fix error handling for failed anchors

packages/cli/src/ceramic-cli-utils.ts
We really gotta get some test coverage of the CLI
=> fix(cli): Fix cli update function

packages/core/src/anchor/ethereum/ethereum-anchor-service.ts
=> fix(core): Cache providers per network

packages/cli/src/__tests__/ceramic-error.test.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/common/src/ceramic-api.ts, packages/common/src/stream.ts, packages/core/src/__tests__/state-manager.test.ts, packages/core/src/ceramic.ts, packages/core/src/state-management/stream-from-state.ts, packages/doctype-caip10-link-handler/src/caip10-link-handler.ts, packages/doctype-caip10-link/src/caip10-link.ts, packages/doctype-tile-handler/src/tile-document-handler.ts, packages/doctype-tile/src/tile-document.ts, packages/http-client/src/ceramic-http-client.ts
Also includes some additional doctype renames
=> feat(common): Rename createDocumentFromGenesis to createStreamFromGenesis

packages/3id-did-resolver/src/__tests__/vectors.json, packages/cli/src/ceramic-daemon.ts, packages/common/src/ceramic-api.ts, packages/core/src/ceramic.ts, packages/doctype-caip10-link/src/caip10-link.ts, packages/doctype-tile/src/tile-document.ts, packages/http-client/src/ceramic-http-client.ts, packages/http-client/src/document.ts
Builds on https://github.com/ceramicnetwork/js-ceramic/pull/1285
=> feat(common): Update createStreamFromGenesis to take 'type' number instead of 'doctype' string

packages/core/src/anchor/ethereum/ethereum-anchor-service.ts, packages/core/src/state-management/state-manager.ts
Also includes a couple of small updates to error messages in the ethereum anchor service
=> chore(core): Log when anchors fail

packages/core/src/pubsub/pubsub.ts
=> feat: use serialized message in pubsub logs

packages/core/src/anchor/ethereum/ethereum-anchor-service.ts, packages/core/src/ceramic.ts, packages/core/src/dispatcher.ts, packages/core/src/state-management/state-manager.ts
Also adds additional context to some other places that errors get thrown
=> chore(core): Log errors while handling pubsub messages

packages/common/src/logger-provider.ts
=> feat: Make optional custom file name for service log

packages/cli/src/ceramic-daemon.ts
=> fix(cli): Handle undefined docOpts in legacy http endpoints

packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/cli/src/__tests__/ceramic-error.test.ts, packages/cli/src/__tests__/ceramic-multi-daemon.test.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/cli/src/index.ts
I would like to use CeramicDaemon in 3id-connect for testing purposes.
=> feat: Expose CeramicDaemon from cli package

packages/cli/package.json, packages/ipfs-daemon/package.json
No complaints on different hoisted versions
=> chore: Bump aws-sdk

packages/ipfs-topology/src/ipfs-topology.ts
Support for `elp` network. Using switch statements to avoid code duplication (aka human error)
=> feat(ipfs-topology): map elp network to mainnet peerlists

packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/core/src/dispatcher.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/state-manager.ts
=> logging improvements

package-lock.json, packages/cli/package.json, packages/common/package.json, packages/core/package.json, packages/ipfs-daemon/package.json, packages/pinning-aggregation/package.json, packages/pinning-ipfs-backend/package.json
=> chore: bump ipfs

packages/core/src/__tests__/ceramic.test.ts
To make sure that the PREFER_CACHE sync behavior won't prefer an old version in the cache over getting the current version from pubsub
=> chore(core): Add tests of interplay between stream cache and the various SyncOptions

packages/stream-caip10-link-handler/src/__tests__/caip10-link-handler.test.ts, packages/stream-tile-handler/src/__tests__/tile-document.test.ts
Functionality being tested was removed under https://github.com/ceramicnetwork/js-ceramic/pull/1505
=> fix(core): Remove obsolete tests

packages/ipfs-topology/src/ipfs-topology.ts
This is helpful for testing/debugging swarm connections
=> Direct swarm connect with topology

packages/core/src/__tests__/ceramic.test.ts, packages/core/src/__tests__/ipfs-util.ts
By using exactly required number of ipfs nodes.
=> chore: Further reduce resource consumption on tests

packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/core/src/ceramic.ts
Replacement for https://github.com/ceramicnetwork/js-ceramic/pull/1516, rebased on current prettified `develop` branch.
=> feat(cli): add global sync override option

packages/core/src/state-management/__tests__/cache-eviction.test.ts
=> test: Increase timeout for some cache-eviction tests

.github/workflows/docker-image.yml
Makes a curl request to our lambda whenever a new image is built and published on docker hub. This is part of the flow to achieve automated deployments.
=> Publish build events to webhook

packages/core/src/__tests__/tile-controller.test.ts, packages/stream-tile-handler/src/tile-document-handler.ts, packages/stream-tile/src/tile-document.ts
Necessary for did:nft and did:safe
=> feat: Allow stream controller to differ from signer

packages/cli/package.json, packages/cli/src/ceramic-daemon.ts
=> feat: Include nft-did-resolver

packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts
Small cleanups before the main change
=> chore(cli): Internal function renames

packages/cli/src/bin/ceramic.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts
builds on https://github.com/ceramicnetwork/js-ceramic/pull/1628
=> feat(cli): Add daemon config file

packages/http-client/src/ceramic-http-client.ts
=> feat: Named export of CeramicClient

packages/blockchain-utils-linking/package.json, packages/blockchain-utils-linking/src/__tests__/__snapshots__/near.test.ts.snap, packages/blockchain-utils-linking/src/__tests__/near.test.ts, packages/blockchain-utils-linking/src/near.ts, packages/blockchain-utils-validation/package.json, packages/blockchain-utils-validation/src/blockchains/__tests__/near.test.ts, packages/blockchain-utils-validation/src/blockchains/near.ts, packages/canary-integration/src/__tests__/caip10/near.test.ts
From https://github.com/ceramicnetwork/js-ceramic/pull/1728
Now tests do actually pass.
=> feat: Transplant Near support

packages/blockchain-utils-linking/src/__tests__/ethereum.test.ts, packages/blockchain-utils-linking/src/ethereum.ts
Note: I tried to import the @walletconnect/ethereum-provider package as a dev dependency for the test as this was the library that uncovered the bug but it makes the tests hang. I did manual happy path tests.
=> fix(blockchain-utils-linking): Support eip1193 provider.request

.github/workflows/docker-image.yml, .github/workflows/docs.yaml
Include a summary of the change and which issue it addresses in the title of the PR. 
=> merge main -> develop

.github/workflows/docker-image.yml, .github/workflows/docs.yaml
Include a summary of the change and which issue it addresses in the title of the PR. 
=> main -> develop

packages/blockchain-utils-linking/src/__tests__/__snapshots__/ethereum.test.ts.snap, packages/blockchain-utils-linking/src/__tests__/ethereum.test.ts, packages/blockchain-utils-linking/src/ethereum.ts
Fixes https://app.circleci.com/pipelines/github/ceramicnetwork/js-ceramic/4495/workflows/ddeeaed8-7555-4687-9b90-f25b0fdf218a/jobs/4761
=> Fix build tests with OCAP requestCapability

packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/__tests__/local-pin-api.test.ts, packages/core/src/local-pin-api.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/running-state.ts, packages/core/src/store/__tests__/pin-store.test.ts, packages/core/src/store/__tests__/state-store-integration.test.ts, packages/core/src/store/pin-store.ts
builds on https://github.com/ceramicnetwork/js-ceramic/pull/1820
=> fix(core): Reset RunningState pinned state on unpin

packages/cli/src/ceramic-daemon.ts
Should address #1870
It has not been tested.
=> chore(cli): set "Access-Control-Max-Age"

packages/core/src/ceramic.ts, packages/ipfs-daemon/src/ipfs-daemon.ts
Reverts ceramicnetwork/js-ceramic#1878
=> Revert "DEBUG DO NOT PUBLISH: add env var to disable peer discovery"

packages/core/src/state-management/repository.ts, packages/core/src/state-management/running-state.ts, packages/core/src/state-management/state-manager.ts
Small code cleanup, no functional change
=> chore(core): Cleanup stream load code

packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/common/package.json, packages/common/src/utils/http-utils.ts
=> Add timeout to fetch json

packages/core/src/__tests__/ceramic.test.ts, packages/core/src/state-management/execution-queue.ts, packages/core/src/state-management/state-manager.ts
This undoes commit 3290a66db7f4063aac1df3781bef2962442740e2
=> fix(core): Load commits serially again

package-lock.json, packages/canary-integration/src/__tests__/deterministic-tile.test.ts, packages/stream-tile-handler/src/__tests__/tile-document.test.ts, packages/stream-tile/package.json, packages/stream-tile/src/tile-document.ts
Non-deterministic streams are all right.
See https://github.com/ceramicnetwork/ceramic/issues/205 for discussion.
BTW, for all of our tests cases, cbor-encoding takes 0-1ms.
=> feat: Only allow valid CBOR in deterministic streams

packages/3id-did-resolver/README.md, packages/blockchain-utils-linking/README.md, packages/blockchain-utils-validation/README.md, packages/cli/README.md, packages/common/README.md, packages/core/README.md, packages/http-client/README.md, packages/ipfs-daemon/README.md, packages/ipfs-topology/README.md, packages/key-did-resolver/README.md, packages/logger/README.md, packages/pinning-aggregation/README.md, packages/pinning-ipfs-backend/README.md, packages/pinning-powergate-backend/README.md, packages/pkh-did-resolver/README.md, packages/stream-caip10-link-handler/README.md, packages/stream-caip10-link/README.md, packages/stream-tile-handler/README.md, packages/stream-tile/README.md, packages/streamid/README.md
Updated readmes of all repos with relevant links to documentation and badges.
=> chore: Update readmes

packages/3id-did-resolver/package.json, packages/canary-integration/package.json, packages/cli/package.json, packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/common/package.json, packages/common/src/utils/test-utils.ts, packages/core/package.json, packages/core/src/pubsub/__tests__/message-bus.test.ts, packages/core/src/pubsub/__tests__/pubsub.test.ts, packages/core/src/state-management/__tests__/anchor-update.ts, packages/core/src/state-management/state-manager.ts, packages/http-client/package.json, packages/http-client/src/__tests__/document.test.ts, packages/ipfs-topology/package.json, packages/key-did-resolver/package.json, packages/pinning-aggregation/package.json, packages/pinning-ipfs-backend/package.json, packages/pinning-powergate-backend/package.json, packages/stream-caip10-link-handler/package.json, packages/stream-caip10-link/package.json, packages/stream-tile-handler/package.json, packages/stream-tile/package.json, packages/streamid/package.json
- Update various dependencies
- Drop `@types/node` where applicable
- Replace deprecated rxjs `.toPromise` with `firstValueFrom` and `lastValueFrom`
- Remove unused `TestUtils.registerChangeListener`
=> chore: Update dependencies

Dockerfile.daemon
Fixes Docker builds and optimizes
=> Fix Dockerfile builds

packages/cli/src/s3-state-store.ts
Or rather adjust to the fact LevelUp exports class right away.
=> chore: Use proper import for LevelUp

packages/blockchain-utils-validation/src/blockchains/__tests__/ethereum.test.ts, packages/canary-integration/src/__tests__/caip10/ethereum.test.ts
Make tests work for contract-based Ethereum wallet.
=> feat: Restore mocked ethereum tests

package-lock.json, package.json, packages/3id-did-resolver/package.json, packages/blockchain-utils-linking/package.json, packages/blockchain-utils-validation/package.json, packages/canary-integration/package.json, packages/cli/package.json, packages/common/package.json, packages/common/scripts/schema_generator.sh, packages/core/package.json, packages/http-client/package.json, packages/ipfs-daemon/package.json, packages/ipfs-topology/package.json, packages/key-did-resolver/package.json, packages/logger/package.json, packages/pinning-aggregation/package.json, packages/pinning-ipfs-backend/package.json, packages/pinning-powergate-backend/package.json, packages/pkh-did-resolver/package.json, packages/stream-caip10-link-handler/package.json, packages/stream-caip10-link/package.json, packages/stream-tile-handler/package.json, packages/stream-tile/package.json, packages/streamid/package.json
So that it can work on windows.
=> chore: use cross-platform rimraf

packages/common/package-lock.json, packages/common/package.json, packages/common/src/loggers.ts
Change it back to jet-logger from overjet-logger
Tests passing
=> chore (common): use jet-logger 

packages/core/src/utils.ts
More details to come...
Reference: https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs-http-client/src/block/put.js
=> fix: socket hangup bug

packages/common/src/utils/http-utils.ts
Its so easy to forget =( especially when everything builds fine
=> fix(common): add file extension to local dependency

packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon-config.ts, packages/core/src/ceramic.ts
DO NOT MERGE THIS PR VIA GITHUB
it would squash the two commits into one and make the history between branches be out of sync
=> feat(cli): Add stream cache size to config file (#2115)

.github/workflows/deploy-branch.yml, .github/workflows/docker-image.yml
Develop branch updates will go to 3BL qa infra as well as dev infra
=> Update CI/CD for qa environment

packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon-config.ts, packages/core/src/ceramic.ts
builds on https://github.com/ceramicnetwork/js-ceramic/pull/2146
=> feat(core,cli): Remove unused 'validate-streams' config option

packages/ipfs-topology/src/ipfs-topology.ts
=> feat(ipfs-topology): Do not connect to peerlist nodes at startup

packages/cli/src/ceramic-cli-utils.ts
Quick fix for error on enabling metrics 
=> the environment variable for enabling metrics needs to be cast to bool

packages/blockchain-utils-linking/src/__tests__/__snapshots__/ethereum.test.ts.snap
=> fix(blockchain-utils-linking): patch ethereum requestCap test failing due to cacao bump

packages/blockchain-utils-linking/src/__tests__/__snapshots__/ethereum.test.ts.snap, packages/common/src/utils/stream-utils.ts, packages/core/src/__tests__/state-manager.test.ts, packages/core/src/state-management/repository.ts
=> fix(core): Allow fast-forward of a stream state if newer commit is anchored

packages/cli/src/ceramic-daemon.ts
The comment was copy pasted from another function so just updated it here.
=> clean: update doc comment for request anchor method

packages/core/src/indexing/postgres/postgres-index-api.ts, packages/core/src/indexing/sqlite/sqlite-index-api.ts, packages/stream-model-instance/src/model-instance-document.ts, packages/stream-tests/src/__tests__/basic-indexing.test.ts, packages/stream-tests/src/create-ceramic.ts, packages/stream-tests/src/create_did.ts
Includes additional test coverage of count queries and queries with relations
=> chore(core, stream-tests): Testing and improved error message for count queries on unindexed streams

packages/cli/src/__tests__/admin-api.test.ts, packages/cli/src/ceramic-daemon.ts, packages/core/src/local-admin-api.ts, packages/http-client/src/remote-admin-api.ts
No functionality change, just running prettier on some recently modified files
=> chore(cli,core,http-client): Prettier code cleanup

package.json, packages/3id-did-resolver/package.json, packages/blockchain-utils-linking/package.json, packages/blockchain-utils-validation/package.json, packages/cli/package.json, packages/common/package.json, packages/core/package.json, packages/http-client/package.json, packages/ipfs-daemon/package.json, packages/ipfs-topology/package.json, packages/key-did-resolver/package.json, packages/logger/package.json, packages/metrics/package.json, packages/pkh-did-resolver/package.json, packages/stream-caip10-link-handler/package.json, packages/stream-caip10-link/package.json, packages/stream-model-handler/package.json, packages/stream-model-instance-handler/package.json, packages/stream-model-instance/package.json, packages/stream-model/package.json, packages/stream-tile-handler/package.json, packages/stream-tile/package.json
Merge PR so tests will run.
cc @stbrody @ukstv @deadlyicon
=> added github links and updated homepage for all npm packages (#2380)

packages/cli/src/ceramic-daemon.ts, packages/core/src/ceramic.ts, packages/core/src/dispatcher.ts, packages/metrics/src/metrics-setup.ts
We want to see charts of IPFS timeouts, other errors, and also pin success/failure
Tests pass
=> add metrics for IPFS timeouts and other things - PLAT-849

packages/metrics/package.json, packages/metrics/src/metrics-setup.ts
PrometheusExporter threw errors in integration tests; need to catch; however, in the latest version of the PrometheusExporter the error seems not possible, so upgrading.
- [x ] ran locally
=> Fix/address_prometheus_errors PLAT-1093

packages/core/src/indexing/build-indexing.ts, packages/core/src/indexing/config.ts, packages/core/src/indexing/postgres/__tests__/insertion-order.test.ts, packages/core/src/indexing/postgres/__tests__/postgres-index-api.test.ts, packages/core/src/indexing/postgres/init-tables.ts, packages/core/src/indexing/postgres/migrations/1-create-model-table.ts, packages/core/src/indexing/postgres/migrations/cdb-schema-verification.ts, packages/core/src/indexing/postgres/postgres-index-api.ts, packages/core/src/indexing/sqlite/__tests__/insertion-order.test.ts, packages/core/src/indexing/sqlite/__tests__/sqlite-index-api.test.ts, packages/core/src/indexing/sqlite/init-tables.ts, packages/core/src/indexing/sqlite/migrations/1-create-model-table.ts, packages/core/src/indexing/sqlite/migrations/cdb-schema-verfication.ts, packages/core/src/indexing/sqlite/sqlite-index-api.ts, packages/core/src/initialization/make-index-api.ts
=> feat(core): persist and check network used for indexing

packages/core/src/indexing/__tests__/build-indexing.test.ts
=> chore(core): add test for building indexing with postgres

packages/cli/src/__tests__/instrument-requests.test.ts, packages/cli/src/daemon-config.ts, packages/cli/src/daemon/instrument-requests.ts, packages/core/src/store/__tests__/level-store.test.ts, packages/core/src/store/stream-state-store.ts
=> remove streamid from endpoint before recording count

packages/stream-tests/src/__tests__/basic-indexing.test.ts
Builds on https://github.com/ceramicnetwork/js-ceramic/pull/2609.  Expected to be merged into that PR first before being merged into develop
=> Add test that indexing relations works after node restart

packages/anchor-listener/src/utils.ts, packages/anchor-utils/src/constants.ts
We assume we are listening to the contract
=> feat(anchor-utils, anchor-listener): Add tx type to anchor proof

packages/core/src/ceramic.ts, packages/core/src/sync/sync-api.ts
=> feat(core): make sync flag work

packages/core/src/__tests__/ceramic.test.ts, packages/ipfs-topology/src/ipfs-topology.ts
I'm not totally sure who's owning the gateway deprecation.  Put @oed and @federicorinaldi as the approvers for now.
CC @smrz2001 @v-stickykeys @willex
=> feat(ipfs-topology): Remove gateway multiaddrs from bootstrap list

.circleci/config.yml, DEVELOPMENT.md, package.json
=> Prettier Check

packages/core/src/state-management/__tests__/job-queue.test.ts, packages/core/src/state-management/job-queue.ts, packages/core/src/sync/__tests__/__snapshots__/sync-api.test.ts.snap, packages/core/src/sync/__tests__/sync-api.test.ts, packages/core/src/sync/sync-api.ts
Temp logging message before we have a node status endpoint
=> feat(core): logging message for sync status

packages/anchor-utils/package.json, packages/cli/src/__tests__/admin-api.test.ts, packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/cli/src/__tests__/ceramic-multi-daemon.test.ts, packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts, packages/common/src/ceramic-api.ts, packages/common/src/utils/test-utils.ts, packages/core/src/__tests__/ceramic-pinning.test.ts, packages/core/src/ceramic.ts, packages/core/src/indexing/database-index-api.ts, packages/core/src/local-admin-api.ts, packages/core/src/state-management/__tests__/cache-eviction.test.ts, packages/core/src/state-management/__tests__/repository.test.ts, packages/core/src/store/__tests__/state-store-integration.test.ts, packages/http-client/src/__tests__/remote-admin-api.test.ts, packages/http-client/src/ceramic-http-client.ts, packages/http-client/src/remote-admin-api.ts, packages/http-client/src/remote-pin-api.ts, packages/http-client/src/utils.ts, packages/stream-tests/src/__tests__/admin-api.test.ts, packages/stream-tests/src/__tests__/basic-indexing.test.ts, packages/stream-tests/src/__tests__/deterministic-model-instance-document.test.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts
=> feat: Pin access control

packages/cli/src/__tests__/admin-api.test.ts, packages/core/src/indexing/__tests__/database-index-api.test.ts, packages/core/src/indexing/database-index-api.ts, packages/core/src/indexing/local-index-api.ts
Moved re-indexing to the CLI call as it prevented node startup otherwise.
=> fix: re-indexing error on startup

packages/core/src/state-management/job-queue.ts, packages/core/src/sync/__tests__/__snapshots__/sync-api.test.ts.snap, packages/core/src/sync/__tests__/sync-api.test.ts, packages/core/src/sync/interfaces.ts, packages/core/src/sync/sync-api.ts, packages/core/src/sync/workers/__tests__/sync.test.ts, packages/core/src/sync/workers/rebuild-anchor.ts, packages/core/src/sync/workers/sync.ts
Use the interface of Job queue when possible
Add comments to status
Address comments for logger
=> fix(core): logging and job queue

.github/workflows/ci.yml, .github/workflows/reusable-release.yml, package.json
Will test the workflows before merging
=> fix: align hotfix workflow with release workflow and push/deploy image

packages/core/src/sync/workers/__tests__/rebuild-anchor.test.ts, packages/core/src/sync/workers/__tests__/sync.test.ts
New StreamID after redeploying `SmokeTestModel` with version field to keep in sync with E2E tests.
=> chore: stream id update for testing model to keep in sync with E2E test

packages/core/src/pubsub/__tests__/incoming-channel.test.ts, packages/core/src/pubsub/incoming-channel.ts
small reword to improve clarity to end users
=> chore(core): Update log warning text when no pubsub messages are being received

packages/anchor-listener/src/loader.ts, packages/core/src/local-admin-api.ts, packages/core/src/sync/__tests__/sync-api.test.ts, packages/core/src/sync/interfaces.ts, packages/core/src/sync/sync-api.ts
1. not keeping track of ongoing syncs corretly
2. Must sync after the index is established
3. increase numbers
=> fix(core, anchor-listener): fix hds bugs

packages/core/src/sync/workers/sync.ts, packages/ipfs-daemon/src/create-ipfs.ts
Runs prettier (not sure how ci is failing on this)
=> chore: run prettier

packages/core/package.json, packages/core/src/pubsub/pubsub-message.ts
@ukstv @stbrody any idea how to debug the tests please?
All I get is `ERROR: TypeError: terminated` when enabling the logs, which I expect is caused by the codec validation, but as there is no further information about the error I have no idea where it originates from?
=> Use codecs for pubsub

packages/anchor-utils/src/merkle/merkle-tree-factory.ts, packages/anchor-utils/src/merkle/merkle-tree.ts
=> chore: Interfaces for Merkle tree and factory

packages/cli/src/ceramic-cli-utils.ts, packages/core/src/indexing/__tests__/database-index-api.test.ts, packages/core/src/indexing/database-index-api.ts, packages/core/src/indexing/local-index-api.ts, packages/core/src/sync/__tests__/sync-api.test.ts
Cleanup parts of indexing in preparation for adding field indices.
=> CDB-2492: Indexing cleanup

package.json, packages/cli/package.json, packages/core/package.json, packages/core/src/indexing/migrations/1-create-model-table.ts
=> Update observability to 1.4.1, fix index btree type test

packages/cli/package.json, packages/core/package.json, packages/core/src/indexing/migrations/1-create-model-table.ts
testing hotfix to current RC that will be promoted to prod release tomorrow
=> Update observability to 1.4.1, fix index btree type test (#2855)

packages/cli/src/daemon/error-handler.ts
=> chore(cli): Report user-friendly error on http connection being aborted

packages/common/src/ceramic-api.ts, packages/core/src/indexing/database-index-api.ts, packages/http-client/src/__tests__/remote-admin-api.test.ts, packages/http-client/src/remote-admin-api.ts
Makes remote client backwards compat. Additionally addresses other small review comments.
=> bug(http-client): CDB-2492 Make remote client backwards compat

packages/cli/src/ceramic-daemon.ts, packages/core/src/indexing/__tests__/database-index-api.test.ts, packages/core/src/indexing/__tests__/query-filter-converter.test.ts, packages/core/src/indexing/__tests__/query-filter-parser.test.ts, packages/core/src/indexing/query-filter-converter.ts, packages/stream-tests/src/__tests__/basic-indexing.test.ts
Add additional tests for null queries not working. Additionall test string based queries.
=> bug(core): CDB-2601 Handle issues with null queries

packages/codecs/src/anchor.ts, packages/core/src/state-management/state-manager.ts
Unconditionally import witness CAR.
Do not merge until CAS-CAR is released on prod.
=> chore: Make CAR file required

packages/core/src/sync/__tests__/__snapshots__/sync-api.test.ts.snap, packages/core/src/sync/sync-api.ts
We haven't been logging any statuses
=> fix(core): empty sync statuses

packages/core/src/ceramic.ts
=> allow use of the cas-direct address

packages/core/src/ceramic.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/state-manager.ts
Tested locally by creating and updating a stream using the CLI
=> Add logs to streams writes steps

packages/core/src/sync/workers/rebuild-anchor.ts
Currently HDS uses a Postgres-based job queue to schedule handling individual anchors in series, which effectively limits concurrency.
When processing an anchor, the logic loads the genesis commits from IPFS for all the streams present in the anchor, which can be up to 1024.
The current logic processes all the anchor streams in parallel, which means there's up to 1024 concurrent loads to IPFS, which is unfortunately too much for IPFS to handle.
This PR adds a concurrency limit to the IPFS load using a queue, with a configured concurrency of 16 which seems to work well running locally on my laptop.
Eventually we could make this concurrency configurable but hopefully it works well in most cases so we can avoid needing another configuration option.
=> fix(core): limit IPFS load of HDS sync

packages/cli/src/ceramic-cli-utils.ts, packages/cli/src/ceramic-daemon.ts
follow-up to https://github.com/ceramicnetwork/js-ceramic/pull/2888
=> Add env var to disable peer data sync

packages/cli/package.json, packages/core/package.json, packages/stream-tests/package.json
=> chore: Update key-did-provider-ed25519

packages/cli/package.json, packages/cli/src/ceramic-daemon.ts
Would not move a needle. Just a peculiar not leveraging of the existing stuff.
=> chore: Leverage generated version

packages/core/src/__tests__/state-manager.test.ts, packages/core/src/conflict-resolution.ts, packages/core/src/dispatcher.ts, packages/core/src/state-management/__tests__/repository.test.ts, packages/core/src/stream-loading/__tests__/stream-loader.test.ts, packages/core/src/stream-loading/state-manipulator.ts, packages/core/src/stream-loading/stream-loader.ts
builds on https://github.com/ceramicnetwork/js-ceramic/pull/2946
=> feat: Add functionality to StreamLoader to load at a CommitID

packages/cli/src/__tests__/ceramic-daemon.test.ts, packages/common/src/anchor-service.ts, packages/common/src/context.ts, packages/common/src/utils/test-utils.ts, packages/core/src/__tests__/ceramic-anchor.test.ts, packages/core/src/__tests__/initialization.test.ts, packages/core/src/anchor/ethereum/__tests__/authenticated-anchor-service.test.ts, packages/core/src/anchor/ethereum/__tests__/ethereum-anchor-service.retry-failure.test.ts, packages/core/src/anchor/ethereum/__tests__/ethereum-did-auth-anchor-service.retry-failure.test.ts, packages/core/src/anchor/ethereum/ethereum-anchor-service.ts, packages/core/src/anchor/ethereum/ethereum-anchor-validator.ts, packages/core/src/anchor/memory/in-memory-anchor-service.ts, packages/core/src/ceramic.ts, packages/core/src/initialization/anchoring.ts, packages/core/src/stream-loading/__tests__/stream-loader.test.ts, packages/stream-tests/src/__tests__/capability.test.ts, packages/stream-tests/src/__tests__/history-sync.test.ts, packages/stream-tests/src/__tests__/node-status.test.ts
- No anchorService in context,
- validator is a part of AnchorService,
- AnchorService creation through opaque functions.
=> chore: Clean up anchoring initialization

packages/core/src/stream-loading/__tests__/stream-loader.test.ts
failure snuck in from merge conflict with https://github.com/ceramicnetwork/js-ceramic/commit/3e42949f4059113068e6f9ebd43f5950ca81f253
=> fix: Fix StreamLoader test

packages/common/src/stream.ts, packages/common/src/utils/signature_utils.ts, packages/core/src/state-management/__tests__/repository.test.ts, packages/core/src/state-management/repository-internals.ts, packages/core/src/state-management/repository.ts, packages/core/src/stream-loading/__tests__/stream-loader.test.ts, packages/core/src/stream-loading/state-manipulator.ts, packages/core/src/stream-loading/stream-loader.ts, packages/stream-tests/src/__tests__/capability.test.ts, packages/stream-tests/src/__tests__/ceramic_sync_disabled.test.ts, packages/stream-tests/src/__tests__/invalid_tip.test.ts, packages/stream-tests/src/__tests__/model.test.ts
This also addresses https://linear.app/3boxlabs/issue/CDB-2732/dont-throw-error-when-loading-a-stream-if-the-tip-isnt-accessible-via
=> feat: Use StreamLoader for loading streams

packages/common/src/stream.ts, packages/common/src/utils/signature_utils.ts, packages/core/src/state-management/__tests__/repository.test.ts, packages/core/src/state-management/repository-internals.ts, packages/core/src/state-management/repository.ts, packages/core/src/stream-loading/__tests__/stream-loader.test.ts, packages/core/src/stream-loading/state-manipulator.ts, packages/core/src/stream-loading/stream-loader.ts, packages/stream-tests/src/__tests__/capability.test.ts, packages/stream-tests/src/__tests__/ceramic_sync_disabled.test.ts, packages/stream-tests/src/__tests__/invalid_tip.test.ts, packages/stream-tests/src/__tests__/model.test.ts
Builds on https://github.com/ceramicnetwork/js-ceramic/pull/2963
=> feat: Update loading at a CommitID to use the StreamLoader

packages/core/src/conflict-resolution.ts, packages/core/src/state-management/repository.ts, packages/core/src/state-management/state-manager.ts
Builds on https://github.com/ceramicnetwork/js-ceramic/pull/2967
=> chore: Cleanup code for loading atTime

packages/cli/src/ceramic-daemon.ts
=> feat: Add admin-DID protected HTTP endpoint for shutting down a node

packages/cli/src/ceramic-daemon.ts
Removed the deprecated documents router
=> feat(cli): Remove support for doc id

DEVELOPMENT.md
When cloning and setting up the project for the first time I noticed the uint tests were failing even after following all the `Project setup` instructions, turns out I needed to spin up a Docker container in order for the uint tests to be succesful.
In this PR I'm including the directions to ensure all tests run as they should, and also the commands to run, in case the user is not familiar with Docker terminology.
Is it worth mentioning that the `DEVELOPMENT_LOCAL` does mention how to build the image and run the container, but is use in the context of running your own local ceramic instance, and from that it is not clear this is an actual requirement when running the test.
N/A
=> Update DEVELOPMENT file

packages/common/src/stream-state-subject.ts
Fix spelling inside documentation.
=> Update stream-state-subject.ts typo

packages/indexing/src/migrations/1-create-model-table.ts, packages/indexing/src/migrations/cdb-schema-verification.ts, packages/indexing/src/tables-manager.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts
Minimum changes necessary I think if we go with this approach
=> feat(indexing): Support optional relations in MIDs

packages/core/src/ancillary/task-queue.ts, packages/core/src/state-management/execution-queue.ts, packages/core/src/state-management/repository.ts
- Label `forStream().run`
- Fix numbering for EQ tasks
=> chore: Label EQ runs

packages/streamid/src/__tests__/event-id.test.ts, packages/streamid/src/event-id.ts, packages/streamid/src/index.ts
Now matches the rust-ceramic spec 
Ported tests over
=> feat(streamid): update event id

packages/codecs/package.json, packages/common/src/stream.ts, packages/core/src/state-management/repository.ts, packages/indexing/src/__tests__/database-index-api.test.ts, packages/indexing/src/database-index-api.ts, packages/indexing/src/local-index-api.ts, packages/stream-model-instance-handler/src/__tests__/model-instance-document-handler.test.ts, packages/stream-model-instance-handler/src/model-instance-document-handler.ts, packages/stream-model-instance-handler/src/schema-utils.ts, packages/stream-model-instance/src/model-instance-document.ts, packages/stream-tests/package.json, packages/stream-tests/src/__tests__/caip10/tezos.test.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts, packages/stream-tests/src/create-ceramic.ts
This reverts commit fed99a6e8ef434838479fc938da4cf6d1e66b029.
=> Revert "feat: Add shouldIndex metadata flag (#3122)"

packages/common/src/utils/stream-utils.ts, packages/stream-model-instance/src/model-instance-document.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts
I think there's a decent chance this fixes https://linear.app/3boxlabs/issue/WS2-2979/orbis-codec-issue as well.  FYI @JulissaDantes
=> fix: proper serialization/deserialization of context field

packages/codecs/package.json, packages/common/src/stream.ts, packages/core/src/state-management/repository.ts, packages/indexing/src/__tests__/database-index-api.test.ts, packages/indexing/src/database-index-api.ts, packages/stream-model-instance-handler/src/__tests__/model-instance-document-handler.test.ts, packages/stream-model-instance-handler/src/model-instance-document-handler.ts, packages/stream-model-instance/src/model-instance-document.ts, packages/stream-tests/src/__tests__/capability.test.ts, packages/stream-tests/src/__tests__/cross-node-indexing.test.ts, packages/stream-tests/src/__tests__/model-instance-document.test.ts
Again.
**BEWARE** This is a breaking change for ModelInstanceDocument API.
=> feat: Add shouldIndex metadata flag

packages/stream-model-instance-handler/package.json
Should address the issue reported in Discord
=> fix(stream-model-instance-handler): move stream-model to dependencies

packages/core/src/__tests__/recon.test.ts, packages/core/src/recon.ts, packages/core/src/state-management/repository.ts
feed limit is 1000, can make configurable one day
=> fix: remove parsing of resume token and add unit tests for recon

packages/anchor-utils/src/merkle/merkle-tree-factory.ts
Record the merkel tree depth of an anchor.
=> feat: add log for anchor-util merkel tree depth

packages/core/src/__tests__/ceramic-api.test.ts
Uncovers actual flakiness of a test, and makes it pass. Note: actual fix is down the line.
=> test: Indexing correction

packages/core/src/store/__tests__/feed-aggregation-store.test.ts, packages/core/src/store/feed-aggregation-store.ts
=> fix: Do not transfer 0 to a next ms after initialization

packages/core/src/store/pin-store-factory.ts
Two dag retrievals in store do not have offline mode set. 
There is one more in 3id-legacy-resolver, but i don't this should affect things as its legacy
=> fix: add offline mode to ipfs dag retrievals in pin store

packages/cli/package.json, packages/common/package.json, packages/core/package.json
The previous version of node-metrics could error exit if certain parameters that were expected to be strings were null.
- [ x] unit tests
- [x ] I have tagged the relevant reviewers and interested parties
=> bump to node-metrics with better non-string handling

packages/cli/src/__tests__/daemon-config.test.ts, packages/cli/src/ceramic-daemon.ts, packages/cli/src/daemon-config.ts
Disable node metrics by default
=> feat: disable node metrics by default

packages/ipfs-topology/src/ipfs-topology.ts
We have new bootstrap peers this updates to use them. See 
https://github.com/ceramicnetwork/rust-ceramic/pull/428 as well
=> feat: add new mainnet and tnet bootstrap peers

packages/ipfs-daemon/src/rust-ipfs.ts, packages/ipfs-topology/src/ipfs-topology.ts
=> feat: add devqa bootstrap peers

packages/cli/src/ceramic-daemon.ts, packages/core/src/ceramic.ts
Should be no functional changes, just code motion.
Doing this to make https://linear.app/3boxlabs/issue/AES-206/re-enable-nodemetrics-by-default easier - since we need to be able to subscribe the node to the NodeMetrics data model, which can only be done from within Ceramic core, there's no api to do that in the Daemon.
Also it just feels like this is where this code belongs anyway.
=> chore: Push metrics handling down from cli package into core package instead

.github/workflows/ci.yml, .github/workflows/reusable-release.yml
We're moving away from dagger and using k8s deployments and removing the verify step for now. It needs updating in order to support the remote ipfs requirement in #3261. Rather than change it, we remove it for now and replace it in a follw up.
=> chore: remove dagger image verify step from CI 

packages/stream-tests/src/__tests__/cross-node-indexing.test.ts
Should fix failures like https://app.circleci.com/pipelines/github/ceramicnetwork/js-ceramic/13816/workflows/5a278f1e-8f2f-4ed6-8267-6cf28a4cb995/jobs/20676
=> chore: Improve test stability
